Repository openforis/fra-platform, pull requests merged in 2020-10, with the labels that each got.

#541 contentCheck: disturbances
  common/i18n/resources/en/contentCheck.js
  webapp/app/assessment/fra/sections/contentCheck/section.js
  webapp/app/assessment/fra/sections/contentCheck/tableSpec/disturbances.js
  webapp/app/assessment/fra/sections/contentCheck/tableSpec/index.js
Labels: refactor

#547 dataExport/bulkDownload: add README.txt
  server/dataExport/README.txt
  server/dataExport/api.js
  webapp/app/components/navigation/navigation.js
Labels: enhancement

#549 migrations: content-check-extent-view-up fix invalid years to null
  server/db/migration/migrations/sqls/20200923094820-content-check-extent-view-up.sql
Labels: bug

#553 hotfix: countrySelect null check
  webapp/app/dataExport/components/countrySelect/countrySelect.js
Labels: bug

#560 Fix/home country selector
  package.json
  webapp/app/landing/Introduction/introduction.less
  yarn.lock
Labels: bug

#544 Feature/custom regions
  common/country/area.js
  common/country/country.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru/area.js
  server/assessment/sendAssessmentNotification.js
  server/assessment/service/csvOutput.js
  server/assessment/service/exportService.js
  server/country/api.js
  server/country/countryRepository.js
  server/country/countryService.js
  server/db/migration/migrations/20200930084905-custom-regions.js
  server/db/migration/migrations/20201001104113-country-remove-region-region-iso.js
  server/db/migration/migrations/20201013053954-drop-country-extra-columns.js
  server/db/migration/migrations/sqls/20200930084905-custom-regions-down.sql
  server/db/migration/migrations/sqls/20200930084905-custom-regions-up.sql
  server/db/migration/migrations/sqls/20201001104113-country-remove-region-region-iso-down.sql
  server/db/migration/migrations/sqls/20201001104113-country-remove-region-region-iso-up.sql
  server/db/migration/migrations/sqls/20201013053954-drop-country-extra-columns-down.sql
  server/db/migration/migrations/sqls/20201013053954-drop-country-extra-columns-up.sql
  server/userChat/userChatApi.js
  webapp/app/admin/components/usersManagementView.js
  webapp/app/assessment/fra/print/fraPrintView.js
  webapp/app/country/actions.js
  webapp/app/country/countryState.js
  webapp/app/countryLanding/views/manageCollaboratorsView.js
  webapp/app/dataExport/useDataExportState.js
  webapp/app/user/userManagement/edit/countrySelectionModal.js
  webapp/app/user/userManagement/edit/editUserForm.js
  webapp/app/user/userManagement/list/usersTable.js
  webapp/app/user/userManagement/list/usersTableCVS.js
  webapp/app/user/userManagement/list/usersTableFilter.js
  webapp/components/countrySelection/components/countryListDownload.js
  webapp/components/countrySelection/components/countryListRoleSection.js
Labels: enhancement

#567 fix create view forest_characteristics_view
  server/db/migration/migrations/sqls/20200129121445-forest-characteristics-view-up.sql
Labels: bug

#568 Custom regions
  common/country/area.js
  common/country/country.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru/area.js
  server/assessment/sendAssessmentNotification.js
  server/assessment/service/csvOutput.js
  server/assessment/service/exportService.js
  server/country/api.js
  server/country/countryRepository.js
  server/country/countryService.js
  server/db/migration/migrations/20200930084905-custom-regions.js
  server/db/migration/migrations/20201001104113-country-remove-region-region-iso.js
  server/db/migration/migrations/20201013053954-drop-country-extra-columns.js
  server/db/migration/migrations/sqls/20200930084905-custom-regions-down.sql
  server/db/migration/migrations/sqls/20200930084905-custom-regions-up.sql
  server/db/migration/migrations/sqls/20201001104113-country-remove-region-region-iso-down.sql
  server/db/migration/migrations/sqls/20201001104113-country-remove-region-region-iso-up.sql
  server/db/migration/migrations/sqls/20201013053954-drop-country-extra-columns-down.sql
  server/db/migration/migrations/sqls/20201013053954-drop-country-extra-columns-up.sql
  server/userChat/userChatApi.js
  webapp/app/actions.js
  webapp/app/admin/components/usersManagementView.js
  webapp/app/appState.js
  webapp/app/assessment/fra/print/fraPrintView.js
  webapp/app/country/actions.js
  webapp/app/country/countryState.js
  webapp/app/countryLanding/views/manageCollaboratorsView.js
  webapp/app/dataExport/useDataExportState.js
  webapp/app/hooks/index.js
  webapp/app/hooks/useRegions.js
  webapp/app/landing/Introduction/AreaSelector/AreaSelector.js
  webapp/app/reducer.js
  webapp/app/user/userManagement/edit/countrySelectionModal.js
  webapp/app/user/userManagement/edit/editUserForm.js
  webapp/app/user/userManagement/list/usersTable.js
  webapp/app/user/userManagement/list/usersTableCVS.js
  webapp/app/user/userManagement/list/usersTableFilter.js
  webapp/components/countrySelection/components/countryList.js
  webapp/components/countrySelection/components/countryListDownload.js
  webapp/components/countrySelection/components/countryListRoleSection.js
Labels: enhancement

#573 navigation/section: sort keys
  webapp/app/components/navigation/components/assessment/section/section.js
Labels: bug

#579 Refactor/dispatch update region countries
  webapp/app/actions.js
  webapp/app/reducer.js
  webapp/store/app/actions/index.js
  webapp/store/app/hooks/index.js
Labels: refactor

#591 navigation: fix overflow issue
  webapp/app/components/navigation/components/assessment/section/section.less
Labels: bug

#585 Landing/PanEuropeanLinks: replace area selector with link to assessme…
  common/i18n/resources/en.js
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.js
  webapp/pages/Landing/PanEuropeanLinks/PanEuropeanLinks.js
Labels: enhancement

#584 PanEuropeanHome: remove fao logo, text left of swiss logo
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/PanEuropeanHome.js
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/panEuropeanHome.less
Labels: enhancement

#580 Refactor/issue 576
  webapp/app/assessment/components/dataTable/table/cellOdpHeader.js
  webapp/app/assessment/components/section/components/customHeader/extentOfForest.js
  webapp/app/assessment/fra/sections/originalDataPoint/actions/actions.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/components/originalData/originalData.js
  webapp/app/countryLanding/views/recentActivityView/recentActivityView.js
  webapp/app/notfound.js
  webapp/main/basePaths.js
Labels: refactor
