Repository openforis/fra-platform, pull requests merged in 2020-11, with the labels that each got.

#596 i18n/en: panEuropean landing and entry link
  common/i18n/resources/en.js
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/PanEuropeanHome.js
Labels: enhancement

#598 Feature/issue 592
  common/country/area.js
  common/country/country.js
  common/i18n/resources/en.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/area.js
  server/country/countryRepository.js
  server/db/migration/create-migration.sh
  server/db/migration/migrations/20201028080433-forest-europe-region.js
  server/db/migration/migrations/sqls/20201028080433-forest-europe-region-down.sql
  server/db/migration/migrations/sqls/20201028080433-forest-europe-region-up.sql
  server/panEuropean/panEuropeanApi.js
  tools/fraCountriesSqlCreator.js
  webapp/app/dataExport/useDataExportState.js
  webapp/components/countrySelection/components/CountryListPanEuropean/CountryListPanEuropean.js
  webapp/pages/Landing/PanEuropeanLinks/PanEuropeanLinks.js
  webapp/store/app/hooks/index.js
Labels: enhancement

#590 Pan European Header
  webapp/components/Header/FraHeader/FraHeader.js
  webapp/components/Header/FraHeader/index.js
  webapp/components/Header/Header.js
  webapp/components/Header/Logo/Logo.js
  webapp/components/Header/Logo/index.js
  webapp/components/Header/PanEuropeanHeader/PanEuropeanHeader.js
  webapp/components/Header/PanEuropeanHeader/index.js
  webapp/components/Header/PanEuropeanHeader/style.less
Labels: enhancement

#600 Dead code cleanup
  test/unit/tableTest.js
  webapp/app/appViewExport.js
  webapp/app/assessment/components/traditionalTable/actions.js
  webapp/app/assessment/components/traditionalTable/calculatedCellType.js
  webapp/app/assessment/components/traditionalTable/cellTypes.js
  webapp/app/assessment/components/traditionalTable/decimalCellType.js
  webapp/app/assessment/components/traditionalTable/integerCellType.js
  webapp/app/assessment/components/traditionalTable/paste.js
  webapp/app/assessment/components/traditionalTable/reducer.js
  webapp/app/assessment/components/traditionalTable/singleTraditionalTableView.js
  webapp/app/assessment/components/traditionalTable/table.js
  webapp/app/assessment/components/traditionalTable/textCellType.js
  webapp/app/assessment/components/traditionalTable/textSelectType.js
  webapp/app/assessment/components/traditionalTable/traditionalTable.js
  webapp/app/assessment/components/traditionalTable/validators.js
  webapp/app/assessment/components/traditionalTable/verticallyGrowingTextCellType.js
  webapp/app/assessment/components/traditionalTable/yesNoSelectType.js
  webapp/app/assessment/fra/sections/extentOfForest/reducers.js
  webapp/app/assessment/fra/sections/forestCharacteristics/reducer.js
  webapp/app/assessment/fra/sections/growingStock/reducer.js
  webapp/app/countryLanding/views/contentCheck/contentCheckView.js
  webapp/app/countryLanding/views/contentCheck/disturbances.js
  webapp/app/countryLanding/views/contentCheck/extent.js
  webapp/app/countryLanding/views/contentCheck/forestGSBiomassCarbon.js
  webapp/app/countryLanding/views/contentCheck/forestOwnership.js
  webapp/app/countryLanding/views/contentCheck/managementRightsOfPublicForests.js
  webapp/app/countryLanding/views/contentCheck/periodicChangeRate.js
  webapp/app/countryLanding/views/contentCheck/primaryDesignatedManagementObjective.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/areaAffectedByFire.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/biomassStock.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/carbonStock.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/designatedManagementObjective.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/disturbances.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/forestAreaWithinProtectedAreas.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/forestOwnership.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/holderOfManagementRights.js
  webapp/app/countryLanding/views/contentCheck/tableSpec/specificForestCategories.js
  webapp/app/countryLanding/views/contentCheck/tableWithOdp/actions.js
  webapp/app/countryLanding/views/contentCheck/tableWithOdp/reducerFunctions.js
  webapp/app/countryLanding/views/contentCheck/totalAreaDesignatedManagementObjective.js
Labels: refactor

#606 bundle: Separate bundles for user and and admin
  webapp/app/actions.js
  webapp/app/appViewExport.js
  webapp/app/assessment/assessmentState.js
  webapp/app/assessment/fra/fraState.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataListView.js
  webapp/app/assessment/panEuropean/sections/indicators/actions.js
  webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js
  webapp/app/assessment/panEuropean/sections/indicators/reducer.js
  webapp/app/assessment/panEuropean/sections/indicators/style.less
  webapp/app/components/audit/actions.js
  webapp/app/countryLanding/views/linksView.js
  webapp/app/countryLanding/views/manageCollaboratorsView.js
  webapp/app/countryLanding/views/messageBoard/messageBoardPanel.js
  webapp/app/countryLanding/views/messageBoard/users.js
  webapp/app/user/userManagement/edit/editUserForm.js
  webapp/app/user/userManagement/editUserView.js
  webapp/app/user/userManagement/list/usersTableFilterWrapper.js
  webapp/components/Header/PanEuropeanHeader/style.less
  webapp/components/Header/UserLinks/LinksFRA/LinksFRA.js
  webapp/components/hooks/useUserInfo.js
  webapp/main/rootReducer.js
  webapp/pages/Admin/Admin.js
  webapp/pages/Admin/adminView.js
  webapp/pages/Admin/components/DataExportView/dataExportView.js
  webapp/pages/Admin/components/DataExportView/index.js
  webapp/pages/Admin/components/Menu.js
  webapp/pages/Admin/components/UserManagementView/index.js
  webapp/pages/Admin/components/UserManagementView/usersManagementView.js
  webapp/pages/Admin/components/UserManagementView/usersTableFilter.js
  webapp/pages/Admin/components/UserManagementView/usersTableFilter.less
  webapp/pages/Admin/components/UserManagementView/usersTableFilterWrapper.js
  webapp/pages/Admin/components/dataExportView.js
  webapp/pages/Admin/components/usersCount.js
  webapp/pages/Admin/components/versioning/NewVersionForm.js
  webapp/pages/Admin/components/versioning/versioningView.js
  webapp/pages/Admin/export.js
  webapp/pages/Admin/index.js
  webapp/pages/Admin/reducer.js
  webapp/pages/Admin/style.less
  webapp/pages/Assessment/Assessment.js
  webapp/pages/Landing/PanEuropeanLinks/PanEuropeanLinks.js
  webapp/pages/PageRoutes/PageRoutes.js
  webapp/pages/User/User.js
  webapp/pages/User/export.js
  webapp/pages/User/index.js
  webapp/store/admin/actions.js
  webapp/store/admin/index.js
  webapp/store/admin/reducer.js
  webapp/store/admin/state.js
  webapp/store/user/actions.js
  webapp/store/user/index.js
  webapp/store/user/reducer.js
  webapp/store/user/state.js
Labels: enhancement

#610 panEuropean: fix issues in sectionSpec(s)
  common/assessment/panEuropean.js
  webapp/app/assessment/components/section/sectionSpec/variables.js
  webapp/app/assessment/panEuropean/sections/table_1_1b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_2a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_2b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_2c/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_3a1/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_3a2/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_3b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_4a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_1_4b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_2_4/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_2_5/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_3_1/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_3_2/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_3_3/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_3_4/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_1/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_2a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_2b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_3a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_3b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_4a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_4b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_4c/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_5/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_8/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_4_9/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_5_1/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_1/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_10a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_10b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_10c/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_10d/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_2/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_3/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_4a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_4b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_5a/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_5b/sectionSpec.js
  webapp/app/assessment/panEuropean/sections/table_6_6/sectionSpec.js
  webapp/app/dataExport/components/columnSelect/columnSelect.js
  webapp/app/dataExport/utils/panEuropeanMappings.js
Labels: bug

#613 Hide forest europe
  webapp/components/countrySelection/components/CountryListFra/CountryListFra.js
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.js
Labels: bug

#614 footer: Add send feedback when user not logged
  webapp/components/footer/components/sendFeedback.js
  webapp/components/footer/footer.js
Labels: enhancement

#615 resultsTable: remove extra colSpan
  webapp/app/dataExport/components/resultsTable/resultsTable.js
Labels: bug

#616 add google analytics
  web-resources/index.html
Labels: enhancement

#622 add github actions
  .github/workflows/run_tests.js.yml
Labels: enhancement, infrastructure

#623 github/actions: extract version
  .github/workflows/heroku-dev.yml
  .github/workflows/test.js.yml
Labels: infrastructure

#626 google-analytics: event tracking
  web-resources/index.html
Labels: enhancement

#624 Create heroku-prod.js.yml
  .github/workflows/heroku-prod.js.yml
  .travis.yml
Labels: infrastructure

#630 dataExport: 3a fix no_unknown variable missing data
  server/dataExport/dataExportRepository.js
  server/db/migration/migrations/20201124131843-primary-designated-management-objective-view.js
  server/db/migration/migrations/sqls/20201124131843-primary-designated-management-objective-view-down.sql
  server/db/migration/migrations/sqls/20201124131843-primary-designated-management-objective-view-up.sql
Labels: bug
