Repository openforis/fra-platform, pull requests merged in 2020-04, with the labels that each got.

#209 description/title: FIX: error as defaultProp
  webapp/app/assessment/components/section/components/descriptions/components/components/title.js
Labels: bug

#213 table.js: display csv export if tableRef not null
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/components/buttonTableExport/buttonTableExport.js
  webapp/components/buttonTableExport/buttonTableExport.less
Labels: bug

#221 odp actions: use history not window.location
  server/odp/api.js
  webapp/app/assessment/fra/sections/originalDataPoint/actions/actions.js
  webapp/app/assessment/fra/sections/originalDataPoint/actions/updateSectionTables.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/components/buttonBar.js
Labels: enhancement, refactor

#225 yearSelection: disable existing odp years in odp view (#220)
  webapp/app/assessment/fra/sections/extentOfForest/actions.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/components/yearSelection.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/originalDataPointView.js
Labels: bug

#228 Chart: removed placeholder in print view
  webapp/app/assessment/components/dataTable/chart/chartContainer.js
  webapp/app/assessment/components/dataTable/chart/useChartData.js
  webapp/main/routes.js
Labels: enhancement

#229 Fixed DataPathChart transition
  webapp/app/assessment/components/dataTable/chart/components/dataPath.js
  webapp/app/assessment/components/dataTable/chart/components/dataTrend.js
  webapp/components/hooks/index.js
  webapp/components/hooks/usePrevious.js
Labels: bug, enhancement

#230 Fix admin paths
  .eslintignore
  .gitignore
  .prettierignore
  server/user/userApi.js
  webapp/app/admin/components/versioning/NewVersionForm.js
  webapp/app/admin/components/versioning/VersioningViewTable.js
  webapp/app/components/header/components/userInfo.js
  webapp/app/routes.js
  webapp/main/basePaths.js
  webapp/main/routes.js
Labels: refactor

#238 DataTable: Refactored folder structure
  webapp/app/assessment/components/dataTable/actions/index.js
  webapp/app/assessment/components/dataTable/actions/persist.js
  webapp/app/assessment/components/dataTable/actions/update.js
  webapp/app/assessment/components/dataTable/table/cellOdpHeader.js
  webapp/app/assessment/components/dataTable/table/row/index.js
  webapp/app/assessment/components/dataTable/table/row/row.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/calculated.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/cell.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/index.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/number.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/placeholder.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/select.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/text.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/useClassName.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cellOdp/cellOdp.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cellOdp/index.js
  webapp/app/assessment/components/dataTable/table/row/rowData/index.js
  webapp/app/assessment/components/dataTable/table/row/rowData/rowData.js
  webapp/app/assessment/components/dataTable/table/row/rowData/useClassName.js
  webapp/app/assessment/components/dataTable/table/row/rowNoticeMessage.js
  webapp/app/assessment/components/dataTable/table/row/rowValidation.js
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/app/assessment/fra/sections/forestAreaChange/actions.js
  webapp/app/assessment/fra/sections/growingStock/actions.js
Labels: enhancement, refactor

#239 DataTableCell: Added onChange hook with Sanitizer
  webapp/app/assessment/components/dataTable/actions/persist.js
  webapp/app/assessment/components/dataTable/actions/update.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/cell.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/number.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/sanitizer.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/select.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/text.js
  webapp/app/assessment/components/dataTable/table/row/rowData/cell/useOnChange.js
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/keysType.js
  webapp/app/assessment/fra/sections/forestAreaChange/actions.js
  webapp/app/assessment/fra/sections/growingStock/actions.js
  webapp/app/assessment/fra/sections/growingStock/sectionSpec.js
Labels: enhancement, refactor

#244 Refactor/issue 142
  .eslintrc.json
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/app/components/navigation/components/assessment/assessment.js
  webapp/app/components/navigation/components/assessment/section/navigationLink.js
  webapp/app/components/navigation/components/assessment/section/section.js
  webapp/app/components/navigation/navigation.js
  webapp/app/country/reviewStatusState.js
Labels: refactor

#245 NumberUtils: added greaterThanWithTolerance
  common/bignumberUtils.js
  webapp/app/assessment/assessmentStateValidator.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestValidatorState.js
  webapp/app/assessment/fra/sections/otherLandWithTreeCover/otherLandWithTreeCoverValidatorState.js
  webapp/app/assessment/fra/sections/specificForestCategories/specificForestCategoriesValidatorState.js
Labels: refactor
