Repository openforis/fra-platform, pull requests merged in 2020-03, with the labels that each got.

#77 Upgraded dependencies / updated usage of uuid/v4
  package.json
  server/user/userRepository.js
  webapp/components/cacheBust.js
  webapp/originalDataPoint/originalDataPoint.js
  yarn.lock
Labels: dependencies

#78 i18n: load only current language translation file
  common/i18n/i18nFactory.js
Labels: enhancement

#85 doc: added webapp folder structure
  doc/dir/webapp.md
  doc/redux/state.md
Labels: documentation

#98 commentsEditor: functional components
  webapp/app/assessment/fra/sections/originalDataPoint/components/commentsEditor.js
  webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView.js
Labels: enhancement

#106 Hotfix/remove validations from public
  webapp/app/assessment/components/traditionalTable/calculatedCellType.js
  webapp/app/assessment/components/traditionalTable/cellTypes.js
  webapp/app/assessment/components/traditionalTable/decimalCellType.js
  webapp/app/assessment/components/traditionalTable/traditionalTable.js
  webapp/app/assessment/fra/sections/forestAreaChange/forestAreaChange.js
  webapp/app/assessment/fra/sections/growingStock/growingStockView.js
Labels: enhancement

#109 Feature/statistical factsheets
  .env.template
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  server/serverInit.js
  webapp/app/appView.js
  webapp/app/components/countrySelection/components/countrySelection.js
  webapp/app/components/header/components/AppLinks.js
  webapp/app/components/header/header.js
  webapp/app/components/header/header.less
  webapp/app/landing/landingView.js
  webapp/app/statisticalFactsheets/index.js
  webapp/app/statisticalFactsheets/statisticalFactsheets.js
  webpack.config.babel.js
Labels: enhancement

#111 Allow GET methods
  server/auth/authApiMiddleware.js
  server/utils/requestUtils.js
Labels: bug

#113 forestCharacteristicsView: hide use original data point button in pub…
  webapp/app/appView.less
  webapp/app/assessment/fra/sections/forestCharacteristics/forestCharacteristicsView.js
  webapp/app/components/header/components/adminLinks.js
  webapp/app/landing/landingView.js
Labels: enhancement

#145 Added basePaths that includes all application route paths
  common/assessment/sections.js
  webapp/app/assessment/components/dataTable/table/rowData.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/components/header/components/AppLinks.js
  webapp/app/components/header/header.js
  webapp/app/components/navigation/components/assessment/section/item.js
  webapp/app/routes.js
  webapp/main/basePaths.js
  webapp/main/routes.js
Labels: enhancement, refactor

#148 Table 1a - added chart
  common/objectUtils.js
  webapp/app/assessment/components/dataTable/chart/chart.js
  webapp/app/assessment/components/dataTable/chart/chartContainer.js
  webapp/app/assessment/components/dataTable/chart/chartWrapper.js
  webapp/app/assessment/components/dataTable/chart/components/dataPath.js
  webapp/app/assessment/components/dataTable/chart/components/dataPoints.js
  webapp/app/assessment/components/dataTable/chart/components/dataTrend.js
  webapp/app/assessment/components/dataTable/chart/components/legend.js
  webapp/app/assessment/components/dataTable/chart/components/noDataPlaceholder.js
  webapp/app/assessment/components/dataTable/chart/components/odpTicks.js
  webapp/app/assessment/components/dataTable/chart/components/xAxis.js
  webapp/app/assessment/components/dataTable/chart/components/yAxis.js
  webapp/app/assessment/components/dataTable/chart/index.js
  webapp/app/assessment/components/dataTable/chart/style.less
  webapp/app/assessment/components/dataTable/dataTable.js
  webapp/app/assessment/components/dataTable/table/cell/calculated.js
  webapp/app/assessment/components/dataTable/table/row.js
  webapp/app/assessment/components/print/style.less
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestView.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/forestCharacteristics/forestCharacteristicsView.js
Labels: refactor

#152 Table 1a Refactor
  common/assessment/fra.js
  common/fraUtils.js
  webapp/app/assessment/actions.js
  webapp/app/assessment/assessmentState.js
  webapp/app/assessment/components/dataTable/actions.js
  webapp/app/assessment/components/dataTable/dataTable.js
  webapp/app/assessment/components/dataTable/dataTable.less
  webapp/app/assessment/components/dataTable/generateValues/fieldsOption.js
  webapp/app/assessment/components/dataTable/generateValues/generateValues.js
  webapp/app/assessment/components/dataTable/generateValues/generateValues.less
  webapp/app/assessment/components/dataTable/generateValues/index.js
  webapp/app/assessment/components/dataTable/generateValues/methods.js
  webapp/app/assessment/components/dataTable/generateValues/useGenerateValulesState.js
  webapp/app/assessment/components/dataTable/table/cell/cellOdp.js
  webapp/app/assessment/components/dataTable/table/cell/cellOdpHeader.js
  webapp/app/assessment/components/dataTable/table/cell/decimal.js
  webapp/app/assessment/components/dataTable/table/rowData.js
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/components/customHeader/customHeader.js
  webapp/app/assessment/components/section/components/customHeader/extentOfForest.js
  webapp/app/assessment/components/section/components/customHeader/index.js
  webapp/app/assessment/components/section/components/title/extentOfForest.js
  webapp/app/assessment/components/section/components/title/index.js
  webapp/app/assessment/components/section/components/title/title.js
  webapp/app/assessment/components/section/sectionSpec.js
  webapp/app/assessment/fra/components/tableWithOdp/actions.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/designatedManagementObjectiveState.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/actions.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/originalDataPoint/actions.js
  webapp/app/assessment/reducer.js
  webapp/app/routes.js
  webapp/main/basePaths.js
Labels: enhancement, refactor

#157 Refactor/section spec
  webapp/app/assessment/components/dataTable/dataTable.js
  webapp/app/assessment/components/dataTable/generateValues/generateValues.js
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/sectionSpec.js
  webapp/app/assessment/components/section/sectionSpec/colSpec.js
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/keysType.js
  webapp/app/assessment/components/section/sectionSpec/rowSpec.js
  webapp/app/assessment/components/section/sectionSpec/sectionSpec.js
  webapp/app/assessment/components/section/sectionSpec/tableSectionSpec.js
  webapp/app/assessment/components/section/sectionSpec/tableSpec.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/forestCharacteristics/sectionSpec.js
Labels: refactor

#158 Table 3b: added section spec
  common/assessment/fra.js
  webapp/app/assessment/assessmentStateValidator.js
  webapp/app/assessment/components/dataTable/table/cell/cell.js
  webapp/app/assessment/components/dataTable/table/cell/useCellClassName.js
  webapp/app/assessment/components/section/sectionSpec/colSpec.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/forestAreaWithinProtectedAreasValidatorState.js
  webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/sectionSpec.js
Labels: enhancement, refactor

#159 Refactor/table 2a
  common/assessment/fra.js
  webapp/app/assessment/components/dataTable/actions.js
  webapp/app/assessment/components/dataTable/dataTable.js
  webapp/app/assessment/components/dataTable/table/cell/cell.js
  webapp/app/assessment/components/dataTable/table/cell/cellOdp.js
  webapp/app/assessment/components/dataTable/table/cell/cellOdpHeader.js
  webapp/app/assessment/components/dataTable/table/cell/decimal.js
  webapp/app/assessment/components/dataTable/table/row.js
  webapp/app/assessment/components/dataTable/table/rowData.js
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/sectionSpec/tableSpec.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/components/traditionalTable/validators.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/forestCharacteristics/actions.js
  webapp/app/assessment/fra/sections/forestCharacteristics/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStock/actions.js
  webapp/app/assessment/fra/sections/growingStock/growingStock.js
  webapp/app/assessment/fra/sections/growingStock/growingStockState.js
  webapp/app/assessment/fra/sections/growingStock/growingStockValidatorState.js
  webapp/app/assessment/fra/sections/growingStock/sectionSpec.js
Labels: enhancement, refactor

#161 Refactor/table 2b
  common/assessment/fra.js
  webapp/app/assessment/components/dataTable/table/cell/calculated.js
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/components/descriptions/descriptions.js
  webapp/app/assessment/components/section/components/descriptions/index.js
  webapp/app/assessment/components/section/components/title/title.js
  webapp/app/assessment/components/section/sectionSpec/colSpec.js
  webapp/app/assessment/components/section/sectionSpec/rowSpec.js
  webapp/app/assessment/components/section/sectionSpec/sectionSpec.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/contactPersons/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStock/growingStockState.js
  webapp/app/assessment/fra/sections/growingStockComposition/growingStockCompositionState.js
  webapp/app/assessment/fra/sections/growingStockComposition/growingStockCompositionValidatorState.js
  webapp/app/assessment/fra/sections/growingStockComposition/sectionSpec.js
  webapp/app/notfound.js
Labels: enhancement, refactor

#164 Navigation: fixed automatic section item selection on component mount
  webapp/app/components/navigation/components/assessment/section/section.js
  webapp/app/components/navigation/components/assessment/section/section.less
Labels: bug

#165 Refactor/table 1c
  common/assessment/fra.js
  webapp/app/assessment/assessmentStateValidator.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/forestAreaChange/actions.js
  webapp/app/assessment/fra/sections/forestAreaChange/forestAreaChangeState.js
  webapp/app/assessment/fra/sections/forestAreaChange/forestAreaChangeValidatorState.js
  webapp/app/assessment/fra/sections/forestAreaChange/sectionSpec.js
Labels: refactor

#167 User edit: fixed edit user role
  webapp/userManagement/edit/editUserForm.js
  yarn.lock
Labels: bug

#168 Refactor/table 7c
  common/assessment/fra.js
  webapp/app/assessment/components/dataTable/table/cell/cell.js
  webapp/app/assessment/components/dataTable/table/cell/decimal.js
  webapp/app/assessment/components/dataTable/table/cell/number.js
  webapp/app/assessment/components/dataTable/table/cell/select.js
  webapp/app/assessment/components/dataTable/table/cell/useCellClassName.js
  webapp/app/assessment/components/dataTable/table/row.js
  webapp/app/assessment/components/dataTable/table/rowData.js
  webapp/app/assessment/components/dataTable/table/table.js
  webapp/app/assessment/components/section/sectionSpec/colSpec.js
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/keysType.js
  webapp/app/assessment/components/section/sectionSpec/rowSpec.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/nonWoodForestProductsRemovals/nonWoodForestProductsRemovalsState.js
  webapp/app/assessment/fra/sections/nonWoodForestProductsRemovals/sectionSpec.js
  webapp/main/styles/fraTable.less
Labels: enhancement, refactor

#170 Refactor/table 7b
  common/assessment/fra.js
  webapp/app/assessment/assessmentStateValidator.js
  webapp/app/assessment/components/dataTable/table/cell/cell.js
  webapp/app/assessment/components/dataTable/table/cell/number.js
  webapp/app/assessment/components/dataTable/table/cell/placeholder.js
  webapp/app/assessment/components/dataTable/table/cell/text.js
  webapp/app/assessment/components/dataTable/table/cell/useCellClassName.js
  webapp/app/assessment/components/dataTable/table/rowData.js
  webapp/app/assessment/components/dataTable/table/rowNoticeMessage.js
  webapp/app/assessment/components/description/description.js
  webapp/app/assessment/components/section/sectionSpec/colSpec.js
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/keysType.js
  webapp/app/assessment/components/section/sectionSpec/rowSpec.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/areaAffectedByFire/areaAffectedByFireValidatorState.js
  webapp/app/assessment/fra/sections/areaAffectedByFire/sectionSpec.js
  webapp/app/assessment/fra/sections/degradedForest/sectionSpec.js
  webapp/app/assessment/fra/sections/disturbances/disturbancesState.js
  webapp/app/assessment/fra/sections/disturbances/sectionSpec.js
  webapp/app/assessment/fra/sections/employment/employmentValidatorState.js
  webapp/app/assessment/fra/sections/employment/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js
  webapp/app/assessment/fra/sections/graduationOfStudents/sectionSpec.js
  webapp/main/styles/fraTable.less
Labels: enhancement, refactor

#173 refactor table 1d
  common/assessment/fra.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/assessment/fra/sections/annualReforestation/annualReforestationValidatorState.js
  webapp/app/assessment/fra/sections/annualReforestation/sectionSpec.js
Labels: refactor

#174 PositiveOrZeroValidator: fixed display of message by passing rowIdx f…
  webapp/app/assessment/assessmentStateValidator.js
  webapp/app/assessment/fra/sections/areaAffectedByFire/areaAffectedByFireValidatorState.js
  webapp/app/assessment/fra/sections/employment/employmentValidatorState.js
  webapp/app/assessment/fra/sections/forestAreaChange/forestAreaChangeValidatorState.js
  webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/forestAreaWithinProtectedAreasValidatorState.js
Labels: bug

#188 forestCharacteristics: fixed unnecessary re-loading of data after tog…
  webapp/app/assessment/assessmentState.js
  webapp/app/assessment/components/dataTable/actions.js
  webapp/app/assessment/fra/sections/forestCharacteristics/actions.js
  webapp/app/assessment/fra/sections/forestCharacteristics/forestCharacteristicsState.js
  webapp/app/assessment/fra/sections/forestCharacteristics/sectionSpec.js
  webapp/app/components/autosave/actions.js
Labels: enhancement

#189 reduxBatch: added batching capabilities to use with redux-thunk
  package.json
  server/eof/api.js
  webapp/app/appView.js
  webapp/app/assessment/components/dataTable/actions.js
  webapp/app/assessment/components/dataTable/useDataTableFetch.js
  webapp/app/assessment/fra/sections/forestAreaChange/actions.js
  webapp/app/assessment/fra/sections/growingStock/actions.js
  webapp/app/country/actions.js
  webapp/main/reduxBatch.js
  webapp/main/store.js
  yarn.lock
Labels: enhancement

#187 descrption refactor inital commit
  webapp/app/appViewExport.js
  webapp/app/assessment/components/description/DescriptionEditor.js
  webapp/app/assessment/components/description/actions.js
  webapp/app/assessment/components/description/analysisDescriptions.js
  webapp/app/assessment/components/description/commentableDescription.js
  webapp/app/assessment/components/description/description.js
  webapp/app/assessment/components/description/descriptionState.js
  webapp/app/assessment/components/description/nationalDataDescriptions.js
  webapp/app/assessment/components/description/reducers.js
  webapp/app/assessment/components/section/assessmentSectionView.js
  webapp/app/assessment/components/section/components/descriptions/components/analysisDescriptions.js
  webapp/app/assessment/components/section/components/descriptions/components/commentableDescription.js
  webapp/app/assessment/components/section/components/descriptions/components/components/title.js
  webapp/app/assessment/components/section/components/descriptions/components/components/toggle.js
  webapp/app/assessment/components/section/components/descriptions/components/description.js
  webapp/app/assessment/components/section/components/descriptions/components/description.less
  webapp/app/assessment/components/section/components/descriptions/components/generalComments.js
  webapp/app/assessment/components/section/components/descriptions/components/nationalDataDescriptions.js
  webapp/app/assessment/components/section/components/descriptions/components/useDescription.js
  webapp/app/assessment/components/section/components/descriptions/descriptions.js
  webapp/app/assessment/components/traditionalTable/singleTraditionalTableView.js
  webapp/app/assessment/fra/sections/biomassStock/biomassStockView.js
  webapp/app/assessment/fra/sections/carbonStock/carbonStockView.js
  webapp/app/assessment/fra/sections/contactPersons/contactPersonsView.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/designatedManagementObjectiveView.js
  webapp/app/assessment/fra/sections/extentOfForest/extentOfForestView.js
  webapp/app/assessment/fra/sections/forestCharacteristics/forestCharacteristicsView.js
  webapp/app/assessment/fra/sections/graduationOfStudents/graduationOfStudentsPrintView.js
  webapp/app/assessment/fra/sections/growingStock/growingStockView.js
  webapp/app/assessment/fra/sections/growingStockComposition/growingStockCompositionView.js
  webapp/app/assessment/fra/sections/nonWoodForestProductsRemovals/nonWoodForestProductsRemovalsView.js
  webapp/components/hooks/useAsync.js
  webapp/components/hooks/useGetRequest.js
  webapp/components/hooks/useIsMounted.js
  webapp/components/hooks/useOnUpdate.js
  webapp/components/hooks/usePostRequest.js
  webapp/components/richTextEditor.js
  webapp/utils/functionUtils.js
Labels: refactor

#195 description: get/post only needed data
  server/descriptions/api.js
  server/descriptions/descriptionsRepository.js
  webapp/app/assessment/components/section/components/descriptions/components/useDescription.js
Labels: refactor

#196 assessmentSection: extracted view component / fetching data in assess…
  webapp/app/assessment/components/dataTable/actions.js
  webapp/app/assessment/components/dataTable/dataTable.js
  webapp/app/assessment/components/dataTable/useDataTableFetch.js
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSection.js
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSectionView.js
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSectionView.less
  webapp/app/assessment/components/section/assessmentSectionView/index.js
  webapp/app/assessment/components/section/assessmentSectionView/useSectionTables.js
  webapp/app/assessment/components/section/sectionSpecs.js
  webapp/app/country/actions.js
  webapp/main/store.js
Labels: enhancement, refactor
