Repository openforis/fra-platform, pull requests merged in 2020-06, with the labels that each got.

#311 dataExport: added 'hasSelection', hide/display table on change
  webapp/app/dataExport/dataExport.js
  webapp/app/dataExport/useDataExportState.js
Labels: bug

#312 Bug/issue 310
  server/dataExport/api.js
  server/db/migration/migrations/20200603103235-growing-stock-view.js
  server/db/migration/migrations/sqls/20200317163130-growing-stock-total-view-down.sql
  server/db/migration/migrations/sqls/20200317163130-growing-stock-total-view-up.sql
  server/db/migration/migrations/sqls/20200508164503-statistical-factsheets-view-up.sql
  server/db/migration/migrations/sqls/20200603103235-growing-stock-view-down.sql
  server/db/migration/migrations/sqls/20200603103235-growing-stock-view-up.sql
Labels: bug

#313 resultsTable: render row without value
  webapp/app/dataExport/components/resultsTable/resultsTable.js
Labels: bug

#318 Bug/issue 314
  server/dataExport/dataExportRepository.js
  server/db/migration/migrations/sqls/20200603103235-growing-stock-view-up.sql
  webapp/app/assessment/fra/sections/employment/sectionSpec.js
  webapp/app/assessment/fra/sections/graduationOfStudents/sectionSpec.js
  webapp/app/dataExport/components/columnSelect/columnSelect.js
  webapp/app/dataExport/components/columnSelect/index.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/components/variableSelect/variableSelect.js
  webapp/app/dataExport/dataExport.js
  webapp/app/dataExport/useDataExportState.js
  webapp/app/dataExport/utils/format.js
  webapp/components/buttonCheckBox/buttonCheckBox.js
Labels: bug

#323 Feature/issue 254
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/tableSpec.js
  webapp/app/assessment/components/section/sectionSpec/unitSpec.js
  webapp/app/assessment/fra/sections/annualReforestation/sectionSpec.js
  webapp/app/assessment/fra/sections/areaAffectedByFire/sectionSpec.js
  webapp/app/assessment/fra/sections/areaOfPermanentForestEstate/sectionSpec.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/sectionSpec.js
  webapp/app/assessment/fra/sections/disturbances/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/sectionSpec.js
  webapp/app/assessment/fra/sections/forestCharacteristics/sectionSpec.js
  webapp/app/assessment/fra/sections/forestOwnership/sectionSpec.js
  webapp/app/assessment/fra/sections/holderOfManagementRights/sectionSpec.js
  webapp/app/assessment/fra/sections/otherLandWithTreeCover/sectionSpec.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/components/resultsTable/resultsTable.less
  webapp/app/dataExport/utils/format.js
Labels: enhancement

#341 biomassStock: fix deadWood typo
  webapp/app/assessment/fra/sections/biomassStock/sectionSpec.js
Labels: bug

#340 forestAreaChange: hide forest_area_net_change from dataExport
  webapp/app/assessment/fra/sections/forestAreaChange/sectionSpec.js
Labels: enhancement

#339 columnSelect: select all
  webapp/app/dataExport/components/columnSelect/columnSelect.js
  webapp/app/dataExport/components/countrySelect/countrySelect.js
  webapp/app/dataExport/components/countrySelect/countrySelect.less
  webapp/app/dataExport/dataExport.less
Labels: enhancement

#342 Feature/issue 328
  webapp/app/assessment/components/section/sectionSpec/unitSpec.js
  webapp/app/assessment/fra/sections/biomassStock/sectionSpec.js
  webapp/app/assessment/fra/sections/carbonStock/sectionSpec.js
  webapp/app/assessment/fra/sections/forestAreaChange/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStock/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStockComposition/sectionSpec.js
  webapp/app/assessment/fra/sections/specificForestCategories/sectionSpec.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
Labels: enhancement

#344 i18n: 'Variable' => 'FRA Variable'
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
Labels: enhancement

#345 Hotfix/issue 330
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/components/variableSelect/variableSelect.js
  webapp/app/dataExport/utils/format.js
Labels: enhancement

#346 Improvements for Data Export - timestamp, desk study
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  server/assessment/assessmentRepository.js
  server/country/countryRepository.js
  server/country/countryService.js
  webapp/app/assessment/components/section/sectionSpec/unitSpec.js
  webapp/app/dataExport/components/countrySelect/countrySelect.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/components/resultsTable/resultsTable.less
  webapp/app/dataExport/utils/format.js
  webapp/components/buttonCheckBox/buttonCheckBox.js
  webapp/components/buttonCheckBox/buttonCheckBox.less
Labels: enhancement

#348 Feature/statistical factsheets template
  webapp/app/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.js
  webapp/app/statisticalFactsheets/CarbonGrowingStock/carbonGrowingStock.less
  webapp/app/statisticalFactsheets/CarbonGrowingStock/index.js
  webapp/app/statisticalFactsheets/ForestArea/ForestArea.js
  webapp/app/statisticalFactsheets/ForestArea/forestArea.less
  webapp/app/statisticalFactsheets/ForestArea/index.js
  webapp/app/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.js
  webapp/app/statisticalFactsheets/ForestAreaPercent/forestAreaPercent.less
  webapp/app/statisticalFactsheets/ForestAreaPercent/index.js
  webapp/app/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js
  webapp/app/statisticalFactsheets/ForestAreaWithinProtectedAreas/forestAreaWithinProtectedAreas.less
  webapp/app/statisticalFactsheets/ForestAreaWithinProtectedAreas/index.js
  webapp/app/statisticalFactsheets/ForestOwnership/ForestOwnership.js
  webapp/app/statisticalFactsheets/ForestOwnership/forestOwnership.less
  webapp/app/statisticalFactsheets/ForestOwnership/index.js
  webapp/app/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.js
  webapp/app/statisticalFactsheets/NaturallyRegeneratingForest/index.js
  webapp/app/statisticalFactsheets/NaturallyRegeneratingForest/naturallyRegeneratingForest.less
  webapp/app/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.js
  webapp/app/statisticalFactsheets/PrimaryDesignatedManagementObjective/index.js
  webapp/app/statisticalFactsheets/PrimaryDesignatedManagementObjective/primaryDesignatedManagementObjective.less
  webapp/app/statisticalFactsheets/PrimaryForest/PrimaryForest.js
  webapp/app/statisticalFactsheets/PrimaryForest/index.js
  webapp/app/statisticalFactsheets/PrimaryForest/primaryForest.less
  webapp/app/statisticalFactsheets/statisticalFactsheets.js
  webapp/app/statisticalFactsheets/statisticalFactsheets.less
Labels: enhancement

#361 Statistical Factsheets Table component and API changes
  common/i18n/resources/en.js
  server/statisticalFactsheets/api.js
  server/statisticalFactsheets/statisticalFactsheetsRepository.js
  webapp/app/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.js
  webapp/app/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.js
  webapp/app/statisticalFactsheets/components/table/index.js
  webapp/app/statisticalFactsheets/components/table/table.js
  webapp/app/statisticalFactsheets/utils/apiUtils.js
  webapp/components/hooks/index.js
Labels: enhancement

#365 Feature/issue 351
  common/i18n/resources/en.js
  package.json
  webapp/app/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.js
  webapp/app/statisticalFactsheets/ForestArea/ForestArea.js
  webapp/app/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js
  webapp/app/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.js
  webapp/app/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.js
  webapp/app/statisticalFactsheets/components/chart/Chart.js
  webapp/app/statisticalFactsheets/components/chart/index.js
  webapp/app/statisticalFactsheets/components/table/table.js
  webapp/app/statisticalFactsheets/hooks/useStatisticalFactsheetsState.js
  webapp/app/statisticalFactsheets/utils/apiUtils.js
  webapp/app/statisticalFactsheets/utils/chartUtils.js
  yarn.lock
Labels: enhancement

#368 Feature/issue 352
  common/i18n/resources/en.js
  webapp/app/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.js
  webapp/app/statisticalFactsheets/ForestOwnership/ForestOwnership.js
  webapp/app/statisticalFactsheets/PrimaryForest/PrimaryForest.js
  webapp/app/statisticalFactsheets/statisticalFactsheets.js
  webapp/app/statisticalFactsheets/utils/chartUtils.js
Labels: enhancement

#369 Hotfix/issue 362
  webapp/app/statisticalFactsheets/components/table/table.js
  webapp/app/statisticalFactsheets/utils/chartUtils.js
Labels: bug, enhancement
