Repository openforis/fra-platform, pull requests merged in 2020-05, with the labels that each got.

#266 Dependencies upgrade
  package.json
  yarn.lock
Labels: dependencies

#269 Heroku deploy fixes
  .travis.yml
  package.json
  webpack.config.babel.js
Labels: bug

#273 Feature/export route and view
  common/i18n/resources/en.js
  webapp/app/appView.js
  webapp/app/appView.less
  webapp/app/assessment/components/section/sectionSpec/index.js
  webapp/app/assessment/components/section/sectionSpec/sectionSpec.js
  webapp/app/assessment/fra/sections/contactPersons/sectionSpec.js
  webapp/app/assessment/fra/sections/nonWoodForestProductsRemovals/sectionSpec.js
  webapp/app/assessment/fra/sections/sustainableDevelopment/sectionSpec.js
  webapp/app/components/header/components/AppLinks.js
  webapp/app/components/navigation/components/assessment/assessment.js
  webapp/app/components/navigation/components/assessment/header/buttonToggleAll.js
  webapp/app/components/navigation/components/assessment/header/header.js
  webapp/app/components/navigation/components/assessment/header/lock.js
  webapp/app/components/navigation/components/assessment/header/titleAssessment.js
  webapp/app/components/navigation/components/assessment/section/navigationLink.js
  webapp/app/components/navigation/components/assessment/section/section.js
  webapp/app/components/navigation/components/linkLanding.js
  webapp/app/components/navigation/navigation.js
  webapp/app/dataExport/dataExport.js
  webapp/app/dataExport/index.js
  webapp/app/routes.js
  webapp/components/hooks/index.js
  webapp/components/hooks/useIsDataExportView.js
  webapp/main/basePaths.js
  webapp/main/routes.js
Labels: enhancement

#275 Safari bug: appView: use calc() instead of fr
  webapp/app/appView.less
Labels: bug

#282 useDataExportState: initial commit
  webapp/app/dataExport/useDataExportState.js
Labels: enhancement

#285 Data Export: Country selection
  common/i18n/resources/en.js
  server/country/api.js
  webapp/app/appView.js
  webapp/app/dataExport/countrySelect/countrySelect.js
  webapp/app/dataExport/countrySelect/countrySelect.less
  webapp/app/dataExport/countrySelect/index.js
  webapp/app/dataExport/dataExport.js
  webapp/app/dataExport/dataExport.less
  webapp/app/dataExport/useDataExportState.js
  webapp/main/basePaths.js
Labels: enhancement

#283 dataExport api: initial commit
  server/apiRouter.js
  server/dataExport/api.js
  server/dataExport/dataExportRepository.js
Labels: enhancement

#292 Feature/issue 290
  webapp/app/assessment/components/section/sectionSpec/tableSpec.js
  webapp/app/assessment/fra/sections/annualReforestation/sectionSpec.js
  webapp/app/assessment/fra/sections/areaAffectedByFire/sectionSpec.js
  webapp/app/assessment/fra/sections/areaOfPermanentForestEstate/sectionSpec.js
  webapp/app/assessment/fra/sections/biomassStock/sectionSpec.js
  webapp/app/assessment/fra/sections/carbonStock/sectionSpec.js
  webapp/app/assessment/fra/sections/designatedManagementObjective/sectionSpec.js
  webapp/app/assessment/fra/sections/disturbances/sectionSpec.js
  webapp/app/assessment/fra/sections/employment/sectionSpec.js
  webapp/app/assessment/fra/sections/extentOfForest/sectionSpec.js
  webapp/app/assessment/fra/sections/forestAreaChange/sectionSpec.js
  webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/sectionSpec.js
  webapp/app/assessment/fra/sections/forestCharacteristics/sectionSpec.js
  webapp/app/assessment/fra/sections/forestOwnership/sectionSpec.js
  webapp/app/assessment/fra/sections/forestPolicy/sectionSpec.js
  webapp/app/assessment/fra/sections/graduationOfStudents/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStock/sectionSpec.js
  webapp/app/assessment/fra/sections/growingStockComposition/sectionSpec.js
  webapp/app/assessment/fra/sections/holderOfManagementRights/sectionSpec.js
  webapp/app/assessment/fra/sections/otherLandWithTreeCover/sectionSpec.js
  webapp/app/assessment/fra/sections/specificForestCategories/sectionSpec.js
Labels: enhancement

#293 Dependencies upgrade
  package.json
  yarn.lock
Labels: dependencies

#301 Feature/issue 255
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  server/dataExport/dataExportRepository.js
  server/db/migration/migrations/sqls/20200129121417-extent-of-forest-view-up.sql
  server/db/migration/migrations/sqls/20200129121445-forest-characteristics-view-up.sql
  webapp/app/assessment/fra/sections/degradedForest/sectionSpec.js
  webapp/app/dataExport/components/columnSelect/columnSelect.js
  webapp/app/dataExport/components/columnSelect/index.js
  webapp/app/dataExport/components/countrySelect/countrySelect.js
  webapp/app/dataExport/components/resultsTable/index.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/components/resultsTable/resultsTable.less
  webapp/app/dataExport/components/variableSelect/variableSelect.js
  webapp/app/dataExport/dataExport.js
  webapp/app/dataExport/dataExport.less
  webapp/app/dataExport/useDataExportState.js
  webapp/components/hooks/useAsync.js
Labels: enhancement
