Repository openforis/fra-platform, pull requests merged in 2020-07, with the labels that each got.

#370 Pan european/fix export and navigation
  common/assessment/assessment.js
  common/i18n/resources/en.js
  package.json
  server/dataExport/dataExportRepository.js
  server/serverInit.js
  server/traditionalTable/api.js
  server/traditionalTable/mappings/panEuropean/index.js
  webapp/app/assessment/components/dataTable/actions/read.js
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSection.js
  webapp/app/assessment/components/section/components/title/title.js
  webapp/app/components/navigation/components/assessment/assessment.js
  webapp/app/components/navigation/components/assessment/header/header.js
  webapp/app/components/navigation/components/assessment/header/lock.js
  webapp/app/components/navigation/components/assessment/header/status.js
  webapp/app/components/navigation/components/assessment/header/title.js
  webapp/app/components/navigation/components/assessment/section/navigationLink.js
  webapp/app/components/navigation/components/assessment/section/section.js
  webapp/app/components/navigation/components/assessment/section/section.less
  webapp/app/components/navigation/navigation.js
  webapp/app/dataExport/components/columnSelect/columnSelect.js
  webapp/app/dataExport/components/countrySelect/countrySelect.js
  webapp/app/dataExport/components/resultsTable/resultsTable.js
  webapp/app/dataExport/useDataExportState.js
  webapp/app/dataExport/utils/format.js
  webapp/app/dataExport/utils/panEuropean.js
  webapp/app/dataExport/utils/panEuropeanMappings.js
  yarn.lock
Labels: bug, enhancement

#378 Added area translation files
  common/i18n/resources/en.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/area.js
  server/db/migration/migrations/20200703121304-country-names-update.js
  server/db/migration/migrations/sqls/20200703121304-country-names-update-down.sql
  server/db/migration/migrations/sqls/20200703121304-country-names-update-up.sql
Labels: enhancement

#371 Feature/issue 367
  common/i18n/resources/en.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/area.js
  server/db/migration/migrations/20200703121304-country-names-update.js
  server/db/migration/migrations/sqls/20200604164503-statistical-factsheets-view-up.sql
  server/db/migration/migrations/sqls/20200703121304-country-names-update-down.sql
  server/db/migration/migrations/sqls/20200703121304-country-names-update-up.sql
  server/statisticalFactsheets/api.js
  server/statisticalFactsheets/statisticalFactsheetsRepository.js
  webapp/app/appView.js
  webapp/app/assessment/fra/print/fraPrintView.js
  webapp/app/statisticalFactsheets/common/levels.js
  webapp/app/statisticalFactsheets/components/levelSelection/getLabel.js
  webapp/app/statisticalFactsheets/components/levelSelection/index.js
  webapp/app/statisticalFactsheets/components/levelSelection/levelSelection.js
  webapp/app/statisticalFactsheets/components/levelSelection/levelSelection.less
  webapp/app/statisticalFactsheets/components/levelSelection/list.js
  webapp/app/statisticalFactsheets/components/levelSelection/listItem.js
  webapp/app/statisticalFactsheets/statisticalFactsheets.js
  webapp/main/basePaths.js
Labels: enhancement

#389 Made CountrySelection eslint compliant
  common/country/area.js
  common/country/country.js
  common/country/index.js
  webapp/app/appView.less
  webapp/app/components/countrySelection/components/countryList.js
  webapp/app/components/countrySelection/components/countryListRoleSection.js
  webapp/app/components/countrySelection/components/countryListRow.js
  webapp/app/components/countrySelection/components/countrySelection.js
  webapp/app/components/countrySelection/components/countrySelection.less
  webapp/app/landing/landingView.js
  webapp/main/styles/config.less
Labels: enhancement, refactor

#393 Disable panEuropean navigation
  webapp/app/components/navigation/navigation.js
Labels: enhancement

#392 Added safeProp in utils/propUtils
  webapp/app/statisticalFactsheets/ForestOwnership/ForestOwnership.js
  webapp/app/statisticalFactsheets/PrimaryForest/PrimaryForest.js
  webapp/app/statisticalFactsheets/utils/propUtils.js
Labels: bug

#395 Feature/header fixed
  webapp/app/appView.js
  webapp/app/appView.less
  webapp/app/components/countrySelection/components/countryList.less
  webapp/app/components/countrySelection/components/countrySelection.js
  webapp/app/components/countrySelection/components/countrySelection.less
  webapp/app/components/countrySelection/components/toggleNavigationControl.js
  webapp/app/components/header/components/AppLinks.js
  webapp/app/components/header/components/toggleNavigationControl.js
  webapp/app/components/header/header.js
  webapp/app/components/header/header.less
  webapp/app/components/navigation/navigation.less
Labels: enhancement, refactor

#394 Home: Overview update #381
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  webapp/app/landing/landingState.js
  webapp/app/landing/landingView.js
  webapp/app/landing/messageBoard/messageBoardState.js
  webapp/app/landing/reducer.js
  webapp/app/landing/useLandingViewSections.js
  webapp/app/landing/views/messageBoard/index.js
  webapp/app/landing/views/messageBoard/messageBoard.js
  webapp/app/landing/views/messageBoard/messageBoardView.js
  webapp/app/landing/views/messageBoard/users.js
  webapp/app/landing/views/overviewView.js
  webapp/app/landing/views/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.js
  webapp/app/landing/views/statisticalFactsheets/CarbonGrowingStock/carbonGrowingStock.less
  webapp/app/landing/views/statisticalFactsheets/CarbonGrowingStock/index.js
  webapp/app/landing/views/statisticalFactsheets/ForestArea/ForestArea.js
  webapp/app/landing/views/statisticalFactsheets/ForestArea/forestArea.less
  webapp/app/landing/views/statisticalFactsheets/ForestArea/index.js
  webapp/app/landing/views/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.js
  webapp/app/landing/views/statisticalFactsheets/ForestAreaPercent/forestAreaPercent.less
  webapp/app/landing/views/statisticalFactsheets/ForestAreaPercent/index.js
  webapp/app/landing/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js
  webapp/app/landing/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/forestAreaWithinProtectedAreas.less
  webapp/app/landing/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/index.js
  webapp/app/landing/views/statisticalFactsheets/ForestOwnership/ForestOwnership.js
  webapp/app/landing/views/statisticalFactsheets/ForestOwnership/forestOwnership.less
  webapp/app/landing/views/statisticalFactsheets/ForestOwnership/index.js
  webapp/app/landing/views/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.js
  webapp/app/landing/views/statisticalFactsheets/NaturallyRegeneratingForest/index.js
  webapp/app/landing/views/statisticalFactsheets/NaturallyRegeneratingForest/naturallyRegeneratingForest.less
  webapp/app/landing/views/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.js
  webapp/app/landing/views/statisticalFactsheets/PrimaryDesignatedManagementObjective/index.js
  webapp/app/landing/views/statisticalFactsheets/PrimaryDesignatedManagementObjective/primaryDesignatedManagementObjective.less
  webapp/app/landing/views/statisticalFactsheets/PrimaryForest/PrimaryForest.js
  webapp/app/landing/views/statisticalFactsheets/PrimaryForest/index.js
  webapp/app/landing/views/statisticalFactsheets/PrimaryForest/primaryForest.less
  webapp/app/landing/views/statisticalFactsheets/common/levels.js
  webapp/app/landing/views/statisticalFactsheets/components/chart/Chart.js
  webapp/app/landing/views/statisticalFactsheets/components/chart/index.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/getLabel.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/index.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/levelSelection.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/levelSelection.less
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/list.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/listItem.js
  webapp/app/landing/views/statisticalFactsheets/components/table/index.js
  webapp/app/landing/views/statisticalFactsheets/components/table/table.js
  webapp/app/landing/views/statisticalFactsheets/hooks/useStatisticalFactsheetsState.js
  webapp/app/landing/views/statisticalFactsheets/index.js
  webapp/app/landing/views/statisticalFactsheets/statisticalFactsheets.js
  webapp/app/landing/views/statisticalFactsheets/statisticalFactsheets.less
  webapp/app/landing/views/statisticalFactsheets/utils/apiUtils.js
  webapp/app/landing/views/statisticalFactsheets/utils/chartUtils.js
  webapp/app/landing/views/statisticalFactsheets/utils/propUtils.js
  webapp/main/basePaths.js
Labels: enhancement

#400 Feature/navigation
  common/i18n/resources/en.js
  webapp/app/components/navigation/components/assessment/assessment.js
  webapp/app/components/navigation/components/assessment/header/header.js
  webapp/app/components/navigation/components/assessment/header/title.js
  webapp/app/components/navigation/components/assessment/section/navigationLink.js
  webapp/app/components/navigation/components/assessment/section/section.js
  webapp/app/components/navigation/navigation.js
  webapp/components/hooks/useIsDataExportView.js
  webapp/components/hooks/useNavigationVisible.js
Labels: enhancement

#401 Statistical Factsheets: Remove levelISOs api and levelSelection
  server/statisticalFactsheets/api.js
  server/statisticalFactsheets/statisticalFactsheetsRepository.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/getLabel.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/index.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/levelSelection.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/levelSelection.less
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/list.js
  webapp/app/landing/views/statisticalFactsheets/components/levelSelection/listItem.js
Labels: enhancement

#402 Statistical Factsheets: Remove throttling, refactor directories
  webapp/app/appView.js
  webapp/app/appViewExport.js
  webapp/app/landing/reducer.js
  webapp/app/landing/views/messageBoard/actions.js
  webapp/app/landing/views/messageBoard/messageBoard.js
  webapp/app/landing/views/messageBoard/messageBoardPanel.js
  webapp/app/landing/views/messageBoard/messageBoardState.js
  webapp/app/landing/views/messageBoard/messageBoardView.js
  webapp/app/landing/views/messageBoard/reducer.js
  webapp/app/landing/views/messageBoard/users.js
  webapp/app/landing/views/statisticalFactsheets/hooks/useStatisticalFactsheetsState.js
Labels: refactor

#403 App Header: removed user profile picture
  webapp/app/admin/adminView.js
  webapp/app/components/header/components/userInfo.js
  webapp/app/components/header/header.less
Labels: enhancement, refactor

#404 Statistical Factsheets: Remove routes and hide tabs if region
  webapp/app/landing/landingView.js
  webapp/main/basePaths.js
  webapp/main/routes.js
Labels: enhancement, refactor

#407 statisticalFactsheets/table: display empty rows
  common/i18n/resources/en.js
  webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.js
Labels: bug

#410 Added link home
  webapp/app/appView.less
  webapp/app/components/countrySelection/components/countryList.less
  webapp/app/components/countrySelection/components/countrySelection.js
  webapp/app/components/countrySelection/components/countrySelection.less
  webapp/app/components/countrySelection/components/toggleNavigationControl.js
  webapp/app/components/header/components/linkHome.js
  webapp/app/components/header/components/linkHome.less
  webapp/app/components/header/components/userInfo.js
  webapp/app/components/header/header.js
  webapp/app/components/header/header.less
  webapp/app/components/navigation/components/linkLanding.js
  webapp/app/components/navigation/navigation.js
  webapp/app/components/navigation/navigation.less
  webapp/app/components/navigation/navigationMixins.less
  webapp/app/countryLanding/views/statisticalFactsheets/components/chart/Chart.js
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.less
  webapp/app/countryLanding/views/statisticalFactsheets/utils/chartUtils.js
  webapp/components/hooks/index.js
  webapp/components/hooks/useIsHome.js
  webapp/components/hooks/useNavigationVisible.js
  webapp/main/styles/config.less
Labels: enhancement

#409 dataExport: remove routes, show in assessmentSectionView if not country
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSectionView.js
  webapp/app/dataExport/dataExport.js
  webapp/app/routes.js
  webapp/main/basePaths.js
  webapp/main/routes.js
Labels: enhancement

#413 Home: added area selector
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  web-resources/img/iconCountries.svg
  web-resources/img/iconGlobal.svg
  web-resources/img/iconRegions.svg
  webapp/app/landing/Introduction/AreaSelector/AreaSelector.js
  webapp/app/landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.js
  webapp/app/landing/Introduction/AreaSelector/DropdownAreas/index.js
  webapp/app/landing/Introduction/AreaSelector/areaSelector.less
  webapp/app/landing/Introduction/AreaSelector/index.js
  webapp/app/landing/Introduction/Introduction.js
  webapp/app/landing/Introduction/introduction.less
Labels: enhancement

#412 DataExport - Regions #390
  common/country/area.js
  common/country/country.js
  server/country/countryRepository.js
  server/db/migration/migrations/20200707134703-country-region-iso.js
  server/db/migration/migrations/sqls/20200707134703-country-region-iso-down.sql
  server/db/migration/migrations/sqls/20200707134703-country-region-iso-up.sql
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSectionView.js
  webapp/app/dataExport/components/countrySelect/countrySelect.js
Labels: enhancement

#418 buttonTableExport: .csv filename, format to number if number
  webapp/components/buttonTableExport/buttonTableExport.js
  webapp/components/buttonTableExport/utils.js
Labels: enhancement

#419 Feature/login
  webapp/Login/Login.js
  webapp/Login/LoginForm/Error/Error.js
  webapp/Login/LoginForm/Error/error.less
  webapp/Login/LoginForm/Error/index.js
  webapp/Login/LoginForm/ForgotPassword/ForgotPassword.js
  webapp/Login/LoginForm/ForgotPassword/index.js
  webapp/Login/LoginForm/LocalLogin/LocalLogin.js
  webapp/Login/LoginForm/LocalLogin/index.js
  webapp/Login/LoginForm/LoginForm.js
  webapp/Login/LoginForm/index.js
  webapp/Login/actions.js
  webapp/Login/components/resetPasswordForm.js
  webapp/Login/index.js
  webapp/Login/login.less
  webapp/Login/reducer.js
  webapp/app/appView.js
  webapp/components/Header/Header.js
  webapp/components/Header/components/autoSaveStatusText.js
  webapp/components/Header/components/languageSelection.js
  webapp/components/Header/components/linkHome.js
  webapp/components/Header/components/linkHome.less
  webapp/components/Header/components/userInfo.js
  webapp/components/Header/header.less
  webapp/components/Header/index.js
  webapp/login/actions.js
  webapp/login/components/forgotPasswordFormModal.js
  webapp/login/components/localLoginForm.js
  webapp/login/components/loginForm.js
  webapp/login/components/resetPasswordForm.js
  webapp/login/components/style.less
  webapp/login/loginView.js
  webapp/login/reducer.js
  webapp/main/basePaths.js
  webapp/main/rootReducer.js
  webapp/main/routes.js
Labels: enhancement

#423 footer: Created footer, translations and removed navigation footer
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  webapp/app/appView.js
  webapp/app/components/navigation/components/footer/footer.js
  webapp/app/components/navigation/components/footer/footer.less
  webapp/app/components/navigation/navigation.js
  webapp/components/footer/components/sendFeedback.js
  webapp/components/footer/footer.js
  webapp/components/footer/footer.less
  webapp/components/footer/index.js
Labels: enhancement

#424 StatisticalFactsheets: fixed charts overflow
  webapp/app/countryLanding/views/statisticalFactsheets/components/chart/Chart.js
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.less
Labels: bug

#425 i18n/en: statisticalFactsheet: use referencees where possible
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
Labels: enhancement

#426 Geographical area selection sticky
  .prettierignore
  common/i18n/resources/ru.js
  webapp/Login/Login.js
  webapp/app/appView.js
  webapp/app/appView.less
  webapp/app/appViewExport.js
  webapp/app/assessment/components/review/style.less
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSection.js
  webapp/app/assessment/components/section/assessmentSectionView/assessmentSectionView.js
  webapp/app/components/navigation/navigation.js
  webapp/app/components/navigation/navigation.less
  webapp/app/countryLanding/countryLandingView.js
  webapp/app/countryLanding/views/statisticalFactsheets/components/chart/Chart.js
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.js
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.less
  webapp/app/dataExport/dataExport.js
  webapp/app/landing/Introduction/introduction.less
  webapp/app/landing/KeyFinidings/keyFindings.less
  webapp/app/landing/landing.js
  webapp/app/landing/landing.less
  webapp/components/Header/header.less
  webapp/components/countrySelection/components/countryList.js
  webapp/components/countrySelection/components/countryList.less
  webapp/components/countrySelection/components/countryListDownload.js
  webapp/components/countrySelection/components/countryListDownload.less
  webapp/components/countrySelection/components/countryListRoleSection.js
  webapp/components/countrySelection/components/countryListRow.js
  webapp/components/countrySelection/components/countrySelection.js
  webapp/components/countrySelection/components/countrySelection.less
  webapp/components/countrySelection/components/linkLanding.js
  webapp/components/countrySelection/components/linkLanding.less
  webapp/components/countrySelection/components/toggleNavigationControl.js
  webapp/components/countrySelection/index.js
  webapp/components/dynamicImport.js
  webapp/components/error/style.less
  webapp/components/footer/components/sendFeedback.js
  webapp/components/footer/footer.js
  webapp/components/footer/footer.less
  webapp/components/hooks/index.js
  webapp/components/hooks/useIsHome.js
  webapp/components/hooks/useIsPath.js
  webapp/components/hooks/useNavigationVisible.js
  webapp/components/loading.js
  webapp/components/multiSelect.less
  webapp/components/popoverControl.less
  webapp/components/tooltip/tooltip.less
  webapp/main/rootReducer.js
  webapp/main/routes.js
  webapp/main/styles/config.less
  webapp/main/styles/style.less
Labels: enhancement

#433 header: hide autosave if in country root
  webapp/components/Header/components/autoSaveStatusText.js
Labels: bug

#432 appView: fix navigation toggle
  webapp/app/appView.js
Labels: bug

#450 Fixed rendering of admin view
  webapp/app/appView.js
  webapp/app/components/navigation/navigation.js
  webapp/components/countrySelection/components/toggleNavigationControl.js
  webapp/components/hooks/index.js
  webapp/components/hooks/useCountryIso.js
  webapp/components/hooks/useIsPath.js
Labels: bug
