Repository openforis/fra-platform, pull requests merged in 2021-08, with the labels that each got.

#865 FRA section specs
  webapp/app/assessment/components/section/sectionSpec/colSpec.ts
  webapp/app/assessment/components/section/sectionSpec/index.ts
  webapp/app/assessment/components/section/sectionSpec/rowSpec.ts
  webapp/app/assessment/components/section/sectionSpec/sectionSpec.ts
  webapp/app/assessment/components/section/sectionSpec/tableSectionSpec.ts
  webapp/app/assessment/components/section/sectionSpec/tableSpec.ts
  webapp/sectionSpec/colSpec.ts
  webapp/sectionSpec/colSpecFactory.ts
  webapp/sectionSpec/fra/annualReforestation/sectionSpec.ts
  webapp/sectionSpec/fra/areaAffectedByFire/sectionSpec.ts
  webapp/sectionSpec/fra/areaOfPermanentForestEstate/sectionSpec.ts
  webapp/sectionSpec/fra/biomassStock/sectionSpec.ts
  webapp/sectionSpec/fra/carbonStock/sectionSpec.ts
  webapp/sectionSpec/fra/contactPersons/sectionSpec.ts
  webapp/sectionSpec/fra/contentCheck/sectionSpec.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/disturbances.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/extent.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/forestGrowingStockBiomassCarbon.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/forestOwnership.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/holderOfManagementRights.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/periodicChangeRate.ts
  webapp/sectionSpec/fra/contentCheck/tableSpec/primaryDesignatedManagementObjective.ts
  webapp/sectionSpec/fra/degradedForest/sectionSpec.ts
  webapp/sectionSpec/fra/designatedManagementObjective/sectionSpec.ts
  webapp/sectionSpec/fra/disturbances/sectionSpec.ts
  webapp/sectionSpec/fra/employment/sectionSpec.ts
  webapp/sectionSpec/fra/extentOfForest/sectionSpec.ts
  webapp/sectionSpec/fra/forestAreaChange/sectionSpec.ts
  webapp/sectionSpec/fra/forestAreaWithinProtectedAreas/sectionSpec.ts
  webapp/sectionSpec/fra/forestCharacteristics/sectionSpec.ts
  webapp/sectionSpec/fra/forestOwnership/sectionSpec.ts
  webapp/sectionSpec/fra/forestPolicy/sectionSpec.ts
  webapp/sectionSpec/fra/graduationOfStudents/sectionSpec.ts
  webapp/sectionSpec/fra/growingStock/growingStockValidatorState.ts
  webapp/sectionSpec/fra/growingStock/sectionSpec.ts
  webapp/sectionSpec/fra/growingStockComposition/sectionSpec.ts
  webapp/sectionSpec/fra/holderOfManagementRights/sectionSpec.ts
  webapp/sectionSpec/fra/index.ts
  webapp/sectionSpec/fra/nonWoodForestProductsRemovals/sectionSpec.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/actions.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/updateSectionTables.ts
  webapp/sectionSpec/fra/originalDataPoint/originalDataListView.tsx
  webapp/sectionSpec/fra/originalDataPoint/originalDataPoint.ts
  webapp/sectionSpec/fra/originalDataPoint/paste.ts
  webapp/sectionSpec/fra/otherLandWithTreeCover/sectionSpec.ts
  webapp/sectionSpec/fra/specificForestCategories/sectionSpec.ts
  webapp/sectionSpec/fra/sustainableDevelopment/sectionSpec.ts
  webapp/sectionSpec/fra/sustainableDevelopment/sustainableDevelopmentState.ts
  webapp/sectionSpec/index.ts
  webapp/sectionSpec/rowSpec.ts
  webapp/sectionSpec/rowSpecFactory.ts
  webapp/sectionSpec/sectionSpecFactory.ts
  webapp/sectionSpec/tableSpecFactory.ts
  webapp/sectionSpec/variables.ts
Labels: enhancement, refactor

#867 Refactor panEu section specs
  webapp/pages/AssessmentSection/AssessmentSection.tsx
  webapp/sectionSpec/panEuropean/index.ts
  webapp/sectionSpec/panEuropean/table_1_1a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_1b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_2a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_2b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_2c/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_3a1/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_3a2/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_3b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_4a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_1_4b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_2_4/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_2_5/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_3_1/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_3_2/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_3_3/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_3_4/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_1/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_2a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_2b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_3a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_3b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_4a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_4b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_4c/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_5/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_8/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_4_9/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_5_1/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_1/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_10a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_10b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_10c/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_10d/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_2/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_3/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_4a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_4b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_4c/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_5a/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_5b/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_6/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_7/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_8/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_9/sectionSpec.ts
Labels: enhancement, refactor

#871 calcTotalLandArea: add nullcheck
  core/odp/odps/calc.ts
Labels: bug

#870 userApi: fix issue with default avatar
  server/user/userApi.ts
Labels: bug

#815 #1: OdpDraft -> OdpVersion
  server/api/odp/createDraft.ts
  server/repository/OdpVersion/create.ts
  server/repository/OdpVersion/index.ts
  server/repository/OdpVersion/update.ts
  server/repository/index.ts
  server/repository/odp/index.ts
  server/repository/odp/updateDraftId.ts
  server/repository/odpClass/addClassData.ts
  server/repository/odpDraft/index.ts
  server/repository/odpDraft/odpDraftRepository.ts
  server/repository/odpDraft/updateOrInsertDraft.ts
  server/service/odp/index.ts
  server/service/odp/persistDraft.ts
  server/service/odp/saveDraft.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/actions.ts
Labels: refactor

#874 Hotfix/husky upgrade
  package.json
  yarn.lock
Labels: bug

#831 #2: ODP: Delete Draft
  server/api/odp/deleteDraft.ts
  server/repository/OdpVersion/create.ts
  server/repository/odp/deleteDraft.ts
  server/repository/odp/deleteOdp.ts
  server/repository/odp/getActualId.ts
  server/repository/odp/getAndCheckOdpCountryId.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/index.ts
  server/repository/odp/markAsActual.ts
  server/repository/odp/updateDraftId.ts
  server/repository/odpClass/addClassData.ts
  server/repository/odpClass/getOdpNationalClasses.ts
  server/repository/odpClass/wipeNationalClassIssues.ts
  server/service/odp/create.ts
  server/service/odp/deleteDraft.ts
Labels: bug

#834 #3: Odp: Delete
  server/api/odp/delete.ts
  server/api/odp/deleteDraft.ts
  server/repository/OdpVersion/deleteById.ts
  server/repository/OdpVersion/index.ts
  server/repository/OdpVersion/update.ts
  server/repository/odp/deleteOdp.ts
  server/repository/odp/getOdp.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/markAsActual.ts
  server/repository/odpClass/wipeClassData.ts
  server/service/odp/deleteDraft.ts
  server/service/odp/deleteOdp.ts
  server/service/odp/persistDraft.ts
Labels: refactor

#883 Feature/get odp version id 806
  common/validateOriginalDataPoint.ts
  server/api/country/getOverviewStatus.ts
  server/api/odp/deleteDraft.ts
  server/api/odp/get.ts
  server/api/odp/getMany.ts
  server/api/odp/getPrevious.ts
  server/api/odp/markAsActual.ts
  server/repository/OdpVersion/update.ts
  server/repository/audit/auditRepository.ts
  server/repository/odp/create.ts
  server/repository/odp/deleteOdp.ts
  server/repository/odp/getActualId.ts
  server/repository/odp/getAndCheckOdpCountryId.ts
  server/repository/odp/getDraftId.ts
  server/repository/odp/getOdp.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/index.ts
  server/repository/odp/listAndValidateOriginalDataPoints.ts
  server/repository/odp/listOriginalDataPoints.ts
  server/repository/odp/markAsActual.ts
  server/repository/odp/updateDraftId.ts
  server/repository/odpClass/addClassData.ts
  server/repository/odpClass/wipeClassData.ts
  server/service/assessment/ndp/ndpExporter.ts
  server/service/odp/create.ts
  server/service/odp/deleteDraft.ts
  server/service/odp/deleteOdp.ts
  server/service/odp/listAndValidateOriginalDataPoints.ts
  server/service/odp/persistDraft.ts
Labels: refactor
