Repository openforis/fra-platform, pull requests merged in 2021-11, with the labels that each got.

#988 Refactor fetchODPs
  server/api/originalDataPoint/get.ts
  server/repository/odp/getOdp.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/listOriginalDataPoints.ts
  server/repository/odpClass/getOdpNationalClasses.ts
  server/repository/originalDataPoint/getMany.ts
  webapp/components/Assessment/FraPrint/useFraPrintDataFetch.ts
  webapp/components/OriginalDataPoint/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx
  webapp/pages/AssessmentPrint/export.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/actions.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/index.ts
  webapp/sectionSpec/fra/originalDataPoint/originalDataPointState.ts
  webapp/sectionSpec/fra/originalDataPoint/reducers.ts
  webapp/store/autosave/hooks/index.ts
  webapp/store/page/originalDataPoint/actions/fetchODPs.ts
  webapp/store/page/originalDataPoint/actions/index.ts
  webapp/store/page/originalDataPoint/actions/setODPs.ts
  webapp/store/page/originalDataPoint/hooks/index.ts
  webapp/store/page/originalDataPoint/index.ts
  webapp/store/page/originalDataPoint/slice.ts
  webapp/store/page/originalDataPoint/state.ts
Labels: enhancement, refactor

#989 initial commit for previous odp api
  common/api/endpoint/ApiEndPoint.ts
  server/api/originalDataPoint/getPrevious.ts
  server/api/originalDataPoint/index.ts
  server/service/originalDataPoint/getPrevious.ts
  server/service/originalDataPoint/index.ts
Labels: enhancement, refactor

#991 remove old ODP client side code
  test/unit/originalDataPointTest.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/actions.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/index.ts
  webapp/sectionSpec/fra/originalDataPoint/actions/updateSectionTables.ts
  webapp/sectionSpec/fra/originalDataPoint/originalDataPoint.ts
Labels: enhancement, refactor

#992 remove old ODP server side code
  server/api/api.ts
  server/api/odp/createDraft.ts
  server/api/odp/delete.ts
  server/api/odp/deleteDraft.ts
  server/api/odp/get.ts
  server/api/odp/getMany.ts
  server/api/odp/getPrevious.ts
  server/api/odp/index.ts
  server/api/odp/markAsActual.ts
  server/repository/OdpVersion/create.ts
  server/repository/OdpVersion/deleteById.ts
  server/repository/OdpVersion/index.ts
  server/repository/OdpVersion/update.ts
  server/repository/index.ts
  server/repository/odp/create.ts
  server/repository/odp/deleteOdp.ts
  server/repository/odp/getActualId.ts
  server/repository/odp/getAndCheckOdpCountryId.ts
  server/repository/odp/getDraftId.ts
  server/repository/odp/getOdp.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/index.ts
  server/repository/odp/listOriginalDataPoints.ts
  server/repository/odp/markAsActual.ts
  server/repository/odp/readEofOdps.ts
  server/repository/odp/readFocOdps.ts
  server/repository/odp/updateDraftId.ts
  server/repository/odpClass/addClassData.ts
  server/repository/odpClass/getOdpNationalClasses.ts
  server/repository/odpClass/index.ts
  server/repository/odpClass/odpClassRepository.ts
  server/repository/odpClass/wipeClassData.ts
  server/repository/odpClass/wipeNationalClassIssues.ts
  server/service/assessment/ndp/ndpExporter.ts
  server/service/index.ts
  server/service/odp/create.ts
  server/service/odp/deleteDraft.ts
  server/service/odp/deleteOdp.ts
  server/service/odp/getOdp.ts
  server/service/odp/getOdpVersionId.ts
  server/service/odp/index.ts
  server/service/odp/listAndValidateOriginalDataPoints.ts
  server/service/odp/listOriginalDataPoints.ts
  server/service/odp/markAsActual.ts
  server/service/odp/persistDraft.ts
  server/service/odp/readEofOdps.ts
  server/service/odp/readFocOdps.ts
Labels: enhancement, refactor

#994 remove old ODP routes
  common/api/endpoint/ApiEndPoint.ts
Labels: enhancement, refactor

#986 dataExport: persist country
  webapp/components/Assessment/DataExport/ColumnSelect/ColumnSelect.tsx
  webapp/components/Assessment/DataExport/DataExport.tsx
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx
  webapp/components/Assessment/DataExport/ResultsTable/Title/Title.tsx
  webapp/components/Assessment/DataExport/ResultsTable/useFetchResults.ts
  webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx
  webapp/store/page/dataExport/dataExportSlice.ts
  webapp/store/page/dataExport/dataExportStateType.ts
  webapp/store/page/dataExport/hooks/index.ts
Labels: enhancement, refactor

#996 remove versioning related UI elements etc
  webapp/main/basePaths.ts
  webapp/pages/Admin/Admin.tsx
  webapp/pages/Admin/components/Menu.tsx
  webapp/pages/Admin/components/versioning/NewVersionButton.tsx
  webapp/pages/Admin/components/versioning/NewVersionForm.tsx
  webapp/pages/Admin/components/versioning/VersioningViewTable.tsx
  webapp/pages/Admin/components/versioning/versioningView.tsx
  webapp/pages/Admin/components/versioning/versioningViewStyle.less
  webapp/pages/Admin/components/versioning/versioningViewUtils.ts
  webapp/pages/Admin/export.ts
  webapp/store/admin/actions.ts
  webapp/store/admin/index.ts
  webapp/store/admin/reducer.ts
  webapp/store/admin/state.ts
Labels: enhancement, refactor

#997 Remove rest of Versioning feature (backend)
  server/api/api.ts
  server/api/country/getAll.ts
  server/api/country/getConfig.ts
  server/api/dataExport/get.ts
  server/api/dataTable/read.ts
  server/api/descriptions/get.ts
  server/api/growingStock/get.ts
  server/api/statisticalFactsheets/get.ts
  server/api/versioning/create.ts
  server/api/versioning/delete.ts
  server/api/versioning/getAll.ts
  server/api/versioning/getLatest.ts
  server/api/versioning/index.ts
  server/db/migration/migrations/20211103073217-drop-fra-version.js
  server/db/migration/migrations/sqls/20211103073217-drop-fra-version-down.sql
  server/db/migration/migrations/sqls/20211103073217-drop-fra-version-up.sql
  server/eof/api.ts
  server/index.ts
  server/panEuropean/panEuropeanApi.ts
  server/repository/versioning/versioningRepository.ts
  server/service/versioning/service.ts
  server/sustainableDevelopment/sustainableDevelopmentApi.ts
  server/system/schedulers/versioningScheduler.ts
Labels: enhancement, refactor

#1001 rename bignumberUtils to numbers, add some types
  common/aggregate.ts
  common/bignumberUtils.ts
  common/extentOfForestHelper.ts
  common/fraUtils.ts
  common/numberFormat.ts
  common/validateOriginalDataPoint.ts
  core/odp/odps/calc.ts
  core/utils/numbers.ts
  server/eof/estimationEngine.ts
  server/service/assessment/fraYears/section_1/forestCharacteristicsExporter.ts
  server/service/assessment/fraYears/section_2/growingStockCompositionExporter.ts
  server/service/assessment/fraYears/section_3/designatedManagementObjectiveExporter.ts
  server/service/assessment/fraYears/section_4/forestOwnershipExporter.ts
  server/service/assessment/fraYears/section_4/holderOfManagementRightsExporter.ts
  server/service/assessment/sdg/section_1/forestCharacteristicsExporter.ts
  server/service/growingStock/growingStockService.ts
  test/unit/bigNumberTest.ts
  webapp/app/assessment/assessmentStateValidator.ts
  webapp/components/Assessment/DataExport/utils/format.ts
  webapp/components/Assessment/DataTable/Chart/components/dataPoints.tsx
  webapp/components/Assessment/DataTable/Table/Row/RowData/CellOdp/CellOdp.tsx
  webapp/components/Chart/utils/getChartOptions.ts
  webapp/components/OriginalDataPoint/ExtentOfForest/ExtentOfForestRow.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristics.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsPlantation.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsRow.tsx
  webapp/components/thousandSeparatedIntegerInput.tsx
  webapp/pages/StatisticalFactsheets/components/table/table.tsx
  webapp/sectionSpec/colSpecFactory.ts
  webapp/sectionSpec/fra/designatedManagementObjective/designatedManagementObjectiveState.ts
  webapp/sectionSpec/fra/extentOfForest/extentOfForestState.ts
  webapp/sectionSpec/fra/extentOfForest/extentOfForestValidatorState.ts
  webapp/sectionSpec/fra/forestAreaChange/actions.ts
  webapp/sectionSpec/fra/forestAreaChange/forestAreaChangeState.ts
  webapp/sectionSpec/fra/forestCharacteristics/forestCharacteristicsState.ts
  webapp/sectionSpec/fra/forestCharacteristics/forestCharacteristicsValidatorState.ts
  webapp/sectionSpec/fra/forestOwnership/forestOwnershipState.ts
  webapp/sectionSpec/fra/forestOwnership/forestOwnershipValidatorState.ts
  webapp/sectionSpec/fra/growingStock/growingStockState.ts
  webapp/sectionSpec/fra/growingStock/growingStockValidatorState.ts
  webapp/sectionSpec/fra/growingStockComposition/growingStockCompositionState.ts
  webapp/sectionSpec/fra/holderOfManagementRights/holderOfManagementRightsState.ts
  webapp/sectionSpec/fra/otherLandWithTreeCover/otherLandWithTreeCoverValidatorState.ts
  webapp/sectionSpec/fra/specificForestCategories/specificForestCategoriesValidatorState.ts
  webapp/sectionSpec/fra/sustainableDevelopment/sustainableDevelopmentState.ts
  webapp/sectionSpec/unitSpec.ts
  webapp/utils/numberInput.ts
Labels: refactor

#1003 remove functionUtils, use Functions
  webapp/components/Assessment/SectionView/Descriptions/Description/useDescription.ts
  webapp/utils/functionUtils.ts
Labels: refactor

#1004 use inferred return type
  core/utils/numbers.ts
Labels: bug

#1005 initial commit for assessment service
  core/meta/assessment.ts
  server/db/index.ts
  server/db/migration/migrations/20211108111343-assessment-schema-update.js
  server/db/migration/migrations/sqls/20211108111343-assessment-schema-update-down.sql
  server/db/migration/migrations/sqls/20211108111343-assessment-schema-update-up.sql
  server/db/schemas.ts
  server/repository/assessment/createAssessmentSchema.ts
  server/repository/assessment/index.ts
  server/service/assessment/createAssessment.ts
  server/service/assessment/index.ts
Labels: enhancement

#1018 Area tabnles
  server/repository/assessment/createAssessmentSchema.ts
  test/integration/index.ts
Labels: enhancement, refactor

#1020 Initial fra meta migration
  core/meta/cycle.ts
  package.json
  server/db/db.ts
  server/repository/assessment/createAssessmentSchema.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/getCol.ts
  tools/dataMigration/getRow.ts
  tools/dataMigration/getSection.ts
  tools/dataMigration/getTable.ts
  tools/dataMigration/getTableSection.ts
  tools/dataMigration/index.ts
Labels: infrastructure

#1019 add settings, test, service, repository
  core/meta/settings.ts
  server/db/migration/migrations/20211118105551-create-settings-table.js
  server/db/migration/migrations/sqls/20211118105551-create-settings-table-down.sql
  server/db/migration/migrations/sqls/20211118105551-create-settings-table-up.sql
  server/repository/index.ts
  server/repository/settings/index.ts
  server/repository/settings/read.ts
  server/repository/settings/update.ts
  server/service/assessment/create.ts
  server/service/index.ts
  server/service/settings/index.ts
  server/service/settings/read.ts
  server/service/settings/update.ts
  test/integration/assessment/assessmentParams.ts
  test/integration/assessment/createAssessment.ts
  test/integration/assessment/removeAssessment.ts
  test/integration/index.ts
  test/integration/settings/defaultAssessment.ts
Labels: enhancement

#1022 userRole: add types, migration
  core/meta/user.ts
  core/meta/userAuth.ts
  server/db/migration/migrations/20211119092729-create-user-auth.js
  server/db/migration/migrations/sqls/20211119092729-create-user-auth-down.sql
  server/db/migration/migrations/sqls/20211119092729-create-user-auth-up.sql
Labels: enhancement, refactor

#1023 deprecate tables
  server/db/migration/migrations/20211122100931-move-all-to-legacy.js
  server/db/migration/migrations/sqls/20211122100931-move-all-to-legacy-down.sql
  server/db/migration/migrations/sqls/20211122100931-move-all-to-legacy-up.sql
Labels: refactor

#1030 FRA region migrations
  server/repository/assessment/getCreateSchemaDDL.ts
  tools/dataMigration/index.ts
Labels: enhancement

#1032 Migrate users
  tools/dataMigration/index.ts
  tools/dataMigration/migrateAreas.ts
  tools/dataMigration/migrateMetadata.ts
  tools/dataMigration/migrateUsers.ts
Labels: enhancement, infrastructure

#1036 Migrate users
  core/meta/user.ts
  core/meta/userAuth.ts
  core/meta/userRoles.ts
  server/controller/user/create.ts
  server/db/migration/migrations/20211127054557-move-users-to-legacy.js
  server/db/migration/migrations/sqls/20211127054557-move-users-to-legacy-down.sql
  server/db/migration/migrations/sqls/20211127054557-move-users-to-legacy-up.sql
  server/repository/userProvider/create.ts
  test/integration/user/userCreate.test.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateMetadata.ts
  tools/dataMigration/migrateUsers.ts
  tools/dataMigration/migrateUsersAuthProvider.ts
  tools/dataMigration/migrateUsersInvitation.ts
  tools/dataMigration/migrateUsersResetPassword.ts
  tools/dataMigration/migrateUsersRole.ts
Labels: enhancement, infrastructure

#1038 moved cycle table to publich schema / split users_role role/props columns
  core/meta/assessment.ts
  core/meta/cycle.ts
  core/meta/user.ts
  core/meta/userRoles.ts
  server/controller/assessment/remove.ts
  server/db/migration/migrations/20211129120510-update-users-role.js
  server/db/migration/migrations/sqls/20211129120510-update-users-role-down.sql
  server/db/migration/migrations/sqls/20211129120510-update-users-role-up.sql
  server/repository/assessment/createAssessment.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  server/repository/assessment/read.ts
  server/repository/assessment/removeAssessment.ts
  server/repository/user/read.ts
  test/integration/assessment/createAssessment.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateUsersRole.ts
Labels: refactor

#1037 multiplatform package.json and test:watch
  jest.config.js
  package.json
  tsconfig.test.json
  yarn.lock
Labels: infrastructure

#1031 Client, store, assessment, initApp
  client/store/RootState.ts
  client/store/assessment/actions/initApp.ts
  client/store/assessment/slice.ts
  client/store/assessment/stateType.ts
  client/store/axiosErrorMiddleware.ts
  client/store/index.ts
  client/store/rootReducer.ts
  client/store/store.ts
  core/country/country.ts
  core/country/index.ts
  core/country/region.ts
  core/meta/region.ts
  core/meta/regionCode.ts
  core/meta/regionGroup.ts
  server/api/init/init.ts
  server/repository/assessment/getCountries.ts
  server/repository/assessment/getRegionGroups.ts
Labels: enhancement, refactor
