Repository openforis/fra-platform, pull requests merged in 2021-10, with the labels that each got.

#935 Remove User Consultation Survey
  webapp/pages/PageRoutes/PageRoutes.tsx
Labels: enhancement

#940 Redirect to pan european when url is /FE/
  webapp/pages/PageRoutes/PageRoutes.tsx
Labels: enhancement

#937 Rtk/page data export
  webapp/components/Assessment/DataExport/ColumnSelect/ColumnSelect.tsx
  webapp/components/Assessment/DataExport/CountrySelect/CountrySelect.tsx
  webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx
  webapp/store/RootState.ts
  webapp/store/page/dataExport/actionTypes.ts
  webapp/store/page/dataExport/actions.ts
  webapp/store/page/dataExport/dataExportSlice.ts
  webapp/store/page/dataExport/dataExportStateType.ts
  webapp/store/page/dataExport/hooks/index.ts
  webapp/store/page/dataExport/index.ts
  webapp/store/page/dataExport/reducer.ts
  webapp/store/page/reducer.ts
Labels: refactor

#945 Create original_data_point table and populate with existing data
  server/db/migration/migrations/20211011092220-create-original-data-point-table.js
  server/db/migration/migrations/sqls/20211011092220-create-original-data-point-table-down.sql
  server/db/migration/migrations/sqls/20211011092220-create-original-data-point-table-up.sql
Labels: enhancement

#956 update read odps for table 1a/1b
  server/api/country/getOverviewStatus.ts
  server/eof/fraValueService.ts
  server/repository/originalDataPoint/getMany.ts
  server/repository/originalDataPoint/index.ts
  server/service/originalDataPoint/getMany.ts
  server/service/originalDataPoint/index.ts
Labels: enhancement

#957 Odp/create
  common/api/endpoint/ApiEndPoint.ts
  server/api/api.ts
  server/api/originalDataPoint/create.ts
  server/api/originalDataPoint/index.ts
  server/repository/originalDataPoint/create.ts
  server/repository/originalDataPoint/index.ts
  server/service/originalDataPoint/create.ts
  server/service/originalDataPoint/index.ts
Labels: refactor

#963 fix odp data_source_methods column value
  server/db/migration/migrations/20211020075326-update-original-data-point-data-source-methods.js
  server/db/migration/migrations/sqls/20211020075326-update-original-data-point-data-source-methods-down.sql
  server/db/migration/migrations/sqls/20211020075326-update-original-data-point-data-source-methods-up.sql
Labels: bug

#965 UI Integration / ODP get
  core/odp/odp.ts
  core/odp/odpNationalClass.ts
  core/odp/odps/addNationalClassPlaceHolder.ts
  core/odp/odps/canCopyPreviousValues.ts
  core/odp/odps/index.ts
  server/repository/odpClass/addClassData.ts
  webapp/app/appViewExport.ts
  webapp/components/OriginalDataPoint/ExtentOfForest/ExtentOfForest.tsx
  webapp/components/OriginalDataPoint/ExtentOfForest/ExtentOfForestRow.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristics.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsPlantation.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
  webapp/components/OriginalDataPoint/ForestCharacteristics/ForestCharacteristicsRow.tsx
  webapp/components/OriginalDataPoint/NationalClasses/NationalClass/NationalClass.tsx
  webapp/components/OriginalDataPoint/OriginalData/OriginalData.tsx
  webapp/components/OriginalDataPoint/hooks/useNationalClassValidation.ts
  webapp/pages/OriginalDataPoint/OriginalDataPoint.tsx
  webapp/store/RootState.ts
  webapp/store/page/originalDataPoint/actions/fetchODP.ts
  webapp/store/page/originalDataPoint/actions/index.ts
  webapp/store/page/originalDataPoint/hooks/index.ts
  webapp/store/page/originalDataPoint/index.ts
  webapp/store/page/originalDataPoint/slice.ts
  webapp/store/page/originalDataPoint/state.ts
  webapp/store/page/reducer.ts
  webapp/store/rootReducer.ts
Labels: enhancement

#967 ODP Patch Years/Data sources
  core/odp/odps/index.ts
  core/odp/odps/removeNationalClassPlaceHolder.ts
  core/utils/functions.ts
  package.json
  server/api/originalDataPoint/update.ts
  server/repository/originalDataPoint/update.ts
  server/service/originalDataPoint/remove.ts
  server/service/originalDataPoint/update.ts
  webapp/components/OriginalDataPoint/DataSources/DataSources.tsx
  webapp/components/OriginalDataPoint/YearSelection/YearSelection.tsx
  webapp/pages/OriginalDataPoint/OriginalDataPoint.tsx
  webapp/store/page/originalDataPoint/actions/fetchODP.ts
  webapp/store/page/originalDataPoint/actions/setODP.ts
  webapp/store/page/originalDataPoint/actions/updateODP.ts
  webapp/store/page/originalDataPoint/slice.ts
  yarn.lock
Labels: enhancement

#968 Odp/UI/delete
  webapp/components/OriginalDataPoint/ButtonBar/ButtonBar.tsx
  webapp/store/page/originalDataPoint/actions/deleteODP.ts
  webapp/store/page/originalDataPoint/actions/index.ts
  webapp/store/page/originalDataPoint/slice.ts
Labels: refactor
