Repository openforis/fra-platform, pull requests merged in 2021-12, with the labels that each got.

#1039 refactor core/meta
  client/store/assessment/stateType.ts
  core/country/areas.ts
  core/country/country.ts
  core/country/index.ts
  core/country/region.ts
  core/meta/area/global.ts
  core/meta/area/index.ts
  core/meta/area/region.ts
  core/meta/area/regionCode.ts
  core/meta/area/regionGroup.ts
  core/meta/assessment/activityLog.ts
  core/meta/assessment/assessment.ts
  core/meta/assessment/col.ts
  core/meta/assessment/cycle.ts
  core/meta/assessment/description.ts
  core/meta/assessment/index.ts
  core/meta/assessment/node.ts
  core/meta/assessment/row.ts
  core/meta/assessment/section.ts
  core/meta/assessment/settings.ts
  core/meta/assessment/table.ts
  core/meta/assessment/tableSection.ts
  core/meta/assessment/unit.ts
  core/meta/user/index.ts
  core/meta/user/user.ts
  core/meta/user/userAuth.ts
  core/meta/user/userRoles.ts
  server/controller/assessment/create.ts
  server/controller/assessment/getRegionGroups.ts
  server/controller/settings/read.ts
  server/controller/settings/update.ts
  server/controller/user/create.ts
  server/repository/activityLog/insertActivityLog.ts
  server/repository/assessment/getRegionGroups.ts
  server/repository/settings/read.ts
  server/repository/settings/update.ts
  server/repository/userProvider/create.ts
  test/integration/user/userCreate.test.ts
  tools/dataMigration/getCol.ts
  tools/dataMigration/getRow.ts
  tools/dataMigration/getSection.ts
  tools/dataMigration/getTable.ts
  tools/dataMigration/getTableSection.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateMetadata.ts
  tools/dataMigration/migrateUsersRole.ts
Labels: refactor

#1043 initial commit for render white page
  client/Main.tsx
  jsconfig.json
  webpack.config.babel.js
  webpack.config.babel.test.js
Labels: refactor

#1044 add pageroutes, initialize assessment
  client/Main.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/pages/PageRoutes/index.ts
  client/pages/PageRoutes/useTheme.ts
  client/store/assessment/actions/initApp.ts
  client/store/assessment/index.ts
  client/store/assessment/slice.ts
  tsconfig.json
  webapp/main.tsx
  webapp/pages/PageRoutes/PageRoutes.tsx
  webapp/pages/PageRoutes/useTheme.ts
Labels: refactor

#1045 -a is not a valid parameter for shelljs, now -Rf is used instead
  package.json
Labels: bug

#1046 cycle schema / node table
  core/meta/assessment/index.ts
  core/meta/assessment/node.ts
  server/db/schemas.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  tools/dataMigration/index.ts
Labels: enhancement, infrastructure

#1047 getCountry => getCountryISOs
  server/api/init/init.ts
  server/controller/assessment/getCountries.ts
  server/controller/assessment/getCountryISOs.ts
  server/controller/assessment/getRegions.ts
  server/controller/assessment/index.ts
  server/repository/assessment/getCountryISOs.ts
  server/repository/assessment/getRegionGroups.ts
  server/repository/assessment/getRegions.ts
  server/repository/assessment/index.ts
Labels: refactor

#1048 update useTheme()
  client/hooks/index.ts
  client/hooks/useIsPath.ts
  client/pages/PageRoutes/basePaths.ts
  client/pages/PageRoutes/useTheme.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  core/meta/assessment/assessment.ts
  core/meta/assessment/assessmentName.ts
  core/meta/assessment/index.ts
  test/integration/assessment/assessmentParams.ts
Labels: refactor

#1054 render video
  client/Main.tsx
  client/components/Partners/Partners.tsx
  client/components/Partners/index.ts
  client/components/Partners/partners.scss
  client/components/index.ts
  client/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/index.ts
  client/pages/Landing/Introduction/AreaSelector/SelectMobile/SelectMobile.tsx
  client/pages/Landing/Introduction/AreaSelector/SelectMobile/index.ts
  client/pages/Landing/Introduction/AreaSelector/areaSelector.scss
  client/pages/Landing/Introduction/AreaSelector/index.ts
  client/pages/Landing/Introduction/Introduction.tsx
  client/pages/Landing/Introduction/index.ts
  client/pages/Landing/Introduction/introduction.scss
  client/pages/Landing/KeyFindings/KeyFindings.tsx
  client/pages/Landing/KeyFindings/index.ts
  client/pages/Landing/KeyFindings/keyFindings.scss
  client/pages/Landing/Landing.tsx
  client/pages/Landing/index.ts
  client/pages/Landing/landing.scss
  client/pages/PageRoutes/PageRoutes.tsx
  client/pages/PageRoutes/basePaths.ts
  client/style/_partials.scss
  client/style/_partials/_breakpoints.scss
  client/style/_partials/_button.scss
  client/style/_partials/_config.scss
  client/style/_partials/_navigation.scss
  client/style/_partials/_spacing.scss
  client/style/_partials/_status.scss
  client/style/_partials/_table.scss
  client/styles/buttons.scss
  client/styles/checkbox.scss
  client/styles/config.scss
  client/styles/cssVars.scss
  client/styles/form.scss
  client/styles/fraTable.scss
  client/styles/fraValidation.scss
  client/styles/icon.scss
  client/styles/inputMixins.scss
  client/styles/rtl.scss
  client/styles/statusMixins.scss
  client/styles/style.scss
Labels: refactor

#1055 initial commit for userstate
  client/store/RootState.ts
  client/store/user/hooks/index.ts
  client/store/user/index.ts
  client/store/user/slice.ts
  client/store/user/stateType.ts
Labels: refactor

#1056 add footer, loading components
  client/components/Footer/Footer.tsx
  client/components/Footer/components/SendFeedback.tsx
  client/components/Footer/footer.scss
  client/components/Footer/index.ts
  client/components/Loading/Loading.tsx
  client/components/Loading/index.ts
  client/pages/PageRoutes/PageRoutes.tsx
Labels: refactor

#1057 initial commit for header
  client/components/AssessmentSwitch/AssessmentSwitch.ts
  client/components/AssessmentSwitch/index.ts
  client/components/Footer/Footer.tsx
  client/components/Header/FraHeader/FraHeader.tsx
  client/components/Header/FraHeader/index.ts
  client/components/Header/Header.tsx
  client/components/Header/LanguageSelector/LanguageSelector.tsx
  client/components/Header/LanguageSelector/LanguageSelectorMobile.tsx
  client/components/Header/LanguageSelector/index.tsx
  client/components/Header/LanguageSelector/languageSelectorMobile.scss
  client/components/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  client/components/Header/PanEuropeanHeader/index.ts
  client/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  client/components/Header/UserLinks/LinksFRA/index.ts
  client/components/Header/UserLinks/UserLinks.tsx
  client/components/Header/UserLinks/index.ts
  client/components/Header/header.scss
  client/components/Header/index.ts
  client/components/Icon/Icon.tsx
  client/components/Icon/cacheBust.ts
  client/components/Icon/index.ts
  client/components/LinkHome/LinkHome.tsx
  client/components/LinkHome/index.ts
  client/components/LinkHome/linkHome.scss
  client/components/PopoverControl/PopoverControl.tsx
  client/components/PopoverControl/index.tsx
  client/components/PopoverControl/popoverControl.scss
  client/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  client/pages/Landing/Introduction/AreaSelector/SelectMobile/SelectMobile.tsx
  client/pages/Landing/Introduction/AreaSelector/areaSelector.scss
  client/pages/PageRoutes/PageRoutes.tsx
Labels: refactor

#1058 Feature/statistical db
  common/i18n/resources/ar.js
  common/i18n/resources/ar/area.js
  common/i18n/resources/en.js
  common/i18n/resources/en/area.js
  common/i18n/resources/es.js
  common/i18n/resources/es/area.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/area.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/area.js
  common/i18n/resources/zh.js
  common/i18n/resources/zh/area.js
  webapp/components/Partners/Partners.tsx
  webapp/pages/StatisticalFactsheets/components/table/table.tsx
  webapp/store/user/userSlice.ts
Labels: enhancement

#1062 initial commit for linksfra
  client/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  client/components/Header/UserLinks/UserLinks.tsx
  client/hooks/index.ts
  client/hooks/useIsPath.ts
  client/pages/PageRoutes/basePaths.ts
  core/country/country.ts
  core/country/index.ts
  core/meta/area/countryIso.ts
  core/meta/area/index.ts
  core/meta/user/index.ts
  core/meta/user/users.ts
Labels: refactor

#1067 Meta/area selector
  client/basePaths.ts
  client/components/CountrySelect/CountryList/countryList.scss
  client/components/CountrySelect/countrySelect.scss
  client/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  client/hooks/index.ts
  client/hooks/useCountryIso.ts
  client/hooks/useIsPath.ts
  client/hooks/useNavigationVisible.ts
  client/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  client/pages/Landing/Introduction/AreaSelector/SelectMobile/SelectMobile.tsx
  client/pages/Landing/Introduction/Introduction.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  client/store/assessment/stateType.ts
  client/utils/breakpoints.ts
  client/utils/index.ts
  common/country/country.ts
  core/meta/area/country.ts
  core/meta/area/index.ts
Labels: refactor

#1071 renamed userroles into userrole, removed userinvitation interface
  meta/user/index.ts
  meta/user/user.ts
  meta/user/userRole.ts
  meta/user/users.ts
Labels: refactor

#1068 DataExport: Multi-variable support with units
  webapp/components/Assessment/DataExport/DataExport.scss
  webapp/components/Assessment/DataExport/DataExport.tsx
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx
  webapp/components/Assessment/DataExport/ResultsTable/Title/Title.tsx
  webapp/components/Assessment/DataExport/ResultsTable/useFetchResults.ts
  webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx
  webapp/store/page/dataExport/dataExportStateType.ts
  webapp/store/page/dataExport/hooks/index.ts
Labels: enhancement

#1070 support changing language
  client/components/Header/LanguageSelector/LanguageSelector.tsx
  client/components/Header/LanguageSelector/LanguageSelectorMobile.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  core/auth/user.ts
  i18n/i18nFactory.ts
  meta/lang.ts
  webapp/components/Header/LanguageSelector/LanguageSelector.tsx
  webapp/components/Header/LanguageSelector/LanguageSelectorMobile.tsx
  webapp/store/app/actions/initApp.ts
  webapp/store/app/actions/switchLanguage.ts
Labels: refactor

#1073 add mailservice
  server/controller/user/invite.ts
  server/service/index.ts
  server/service/mail/index.ts
  server/service/mail/mail.ts
  server/service/mail/userInvite.ts
  test/integration/user/userInvite.test.ts
Labels: enhancement

#1074 save language
  client/components/Header/LanguageSelector/LanguageSelector.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/utils/index.ts
  client/utils/url.ts
Labels: refactor

#1076 Hotfix/dataexport
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx
Labels: bug

#1079 initial commit for login page
  client/pages/Login/Login.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/LoginForm/index.ts
  client/pages/Login/login.scss
Labels: enhancement, refactor

#1081 reset password
  client/pages/Login/Login.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/ResetPassword/ResetPassword.tsx
  client/pages/Login/ResetPassword/index.ts
  client/pages/Login/login.scss
  i18n/resources/en/login.js
Labels: enhancement, refactor

#1078 Login/master: Base branch for login UI
  client/pages/Login/Login.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/LoginForm/index.ts
  client/pages/Login/ResetPassword/ResetPassword.tsx
  client/pages/Login/ResetPassword/index.ts
  client/pages/Login/index.ts
  client/pages/Login/login.scss
  client/pages/PageRoutes/PageRoutes.tsx
  i18n/resources/en/login.js
Labels: refactor

#1052 User invitation
  README.md
  core/meta/user/userRole.ts
  core/meta/user/users.ts
  meta/assessment/activityLog.ts
  meta/assessment/assessmentName.ts
  meta/assessment/cycle.ts
  meta/user/users.ts
  server/controller/assessment/createCycle.ts
  server/controller/assessment/index.ts
  server/controller/user/acceptInvitation.ts
  server/controller/user/index.ts
  server/controller/user/invite.ts
  server/db/migration/migrations/20211130145149-update-users-role.js
  server/db/migration/migrations/20211211092810-merge-role-and-invitation.js
  server/db/migration/migrations/sqls/20211130145149-update-users-role-down.sql
  server/db/migration/migrations/sqls/20211130145149-update-users-role-up.sql
  server/db/migration/migrations/sqls/20211211092810-merge-role-and-invitation-down.sql
  server/db/migration/migrations/sqls/20211211092810-merge-role-and-invitation-up.sql
  server/repository/assessment/createCycle.ts
  server/repository/assessment/index.ts
  server/repository/assessment/read.ts
  server/repository/index.ts
  server/repository/user/read.ts
  server/repository/user/update.ts
  server/repository/userRole/acceptInvitation.ts
  server/repository/userRole/create.ts
  server/repository/userRole/index.ts
  server/service/index.ts
  server/service/mail/index.ts
  server/service/mail/mail.ts
  server/service/mail/userInvite.ts
  test/integration/assessment/createAssessment.ts
  test/integration/assessment/removeAssessment.ts
  test/integration/index.ts
  test/integration/mock/assessment.ts
  test/integration/mock/user.ts
  test/integration/settings/defaultAssessment.ts
  test/integration/user/userInvite.test.ts
Labels: refactor

#1082 initial commit for google login
  .env.template
  client/pages/Login/LoginForm/LoginForm.tsx
  package.json
  server/api/api.ts
  server/api/auth/config.ts
  server/api/auth/index.ts
  server/api/auth/login.ts
  server/repository/user/read.ts
  server/serverInit.ts
  yarn.lock
Labels: refactor

#1084 fixed windows wrong country selection width, horizontal scrollbar is now global
  webapp/components/CountrySelect/countrySelect.scss
  webapp/main/styles/fraTable.less
  webapp/pages/Assessment/assessment.scss
Labels: bug

#1085 local login, logout
  common/api/endpoint/ApiEndPoint.ts
  server/api/auth/config.ts
  server/api/auth/googleStrategyVerifyCallback.ts
  server/api/auth/index.ts
  server/api/auth/localStrategyVerifyCallback.ts
  server/api/auth/login.ts
  server/api/auth/logout.ts
  server/repository/userProvider/index.ts
  server/repository/userProvider/read.ts
Labels: refactor

#1086 Meta/user invitation UI
  client/basePaths.ts
  client/pages/Login/Invitation/Invitation.tsx
  client/pages/Login/Invitation/index.ts
  client/pages/Login/Login.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/RootState.ts
  client/store/login/actions/acceptInvitation.ts
  client/store/login/actions/fetchUserByInvitation.ts
  client/store/login/index.ts
  client/store/login/slice.ts
  client/store/login/stateType.ts
  client/store/rootReducer.ts
  common/api/endpoint/ApiEndPoint.ts
  server/api/api.ts
  server/api/user/acceptInvitation.ts
  server/api/user/getByInvitation.ts
  server/api/user/index.ts
  server/controller/user/index.ts
  server/controller/user/readByInvitation.ts
  server/repository/userRole/index.ts
  server/repository/userRole/read.ts
Labels: refactor
