Repository openforis/fra-platform, pull requests merged in 2021-07, with the labels that each got.

#837 UserConsultationSurvey: Update link from edit to view
  webapp/components/UserConsultationSurvey/UserConsultationSurvey.tsx
Labels: enhancement

#832 git: update pre-commit hook
  .husky/pre-commit
  package.json
Labels: bug, enhancement

#833 PageRoutes: add redirect for /:countryIso
  webapp/main/basePaths.ts
  webapp/pages/PageRoutes/PageRoutes.tsx
Labels: enhancement

#835 app/actions: fix url param
  webapp/store/app/actions/index.ts
Labels: bug

#845 Webpack + minor dependencies upgrade
  .eslintrc.json
  .husky/pre-commit
  common/assessmentSectionItems.ts
  common/countryRole.ts
  package.json
  server/assessment/assessmentEditAccessControl.ts
  server/index.ts
  webapp/components/AssessmentComponent/AssessmentComponent.ts
  webapp/main/styles/style.less
  webpack.config.babel.js
  yarn.lock
Labels: dependencies

#849 Fix dashboard legend labels
  webapp/app/countryLanding/views/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/ForestArea/ForestArea.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/ForestOwnership/ForestOwnership.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/PrimaryForest/PrimaryForest.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/StatisticalFactsheets.scss
  webapp/app/countryLanding/views/statisticalFactsheets/StatisticalFactsheets.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.tsx
  webapp/app/countryLanding/views/statisticalFactsheets/index.ts
  webapp/app/countryLanding/views/statisticalFactsheets/utils/chartUtils.ts
Labels: bug

#855 CountrySelect mobile
  package.json
  webapp/app/components/navigation/navigation.scss
  webapp/app/components/navigation/navigation.tsx
  webapp/app/countryLanding/views/linksView.tsx
  webapp/app/countryLanding/views/messageBoard/messageBoard.tsx
  webapp/app/countryLanding/views/messageBoard/users.tsx
  webapp/components/CountrySelect/CountrySelect.tsx
  webapp/components/Header/FraHeader/FraHeader.tsx
  webapp/components/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  webapp/components/Header/components/linkHome.less
  webapp/components/LinkHome/LinkHome.tsx
  webapp/components/LinkHome/index.ts
  webapp/components/LinkHome/linkHome.scss
  webapp/components/hooks/index.ts
  webapp/components/hooks/useCountryIso.ts
  webapp/components/hooks/useResponsive.ts
  webapp/pages/Admin/Admin.tsx
  webapp/pages/Admin/components/Menu.tsx
  webapp/pages/Assessment/Assessment.tsx
  webapp/pages/Assessment/AssessmentHome/AssessmentHome.tsx
  webapp/pages/Assessment/AssessmentHome/FraHome/FraHome.tsx
  webapp/pages/Assessment/AssessmentHome/FraHome/fraHome.scss
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/panEuropeanHome.scss
  webapp/pages/Assessment/DataDownload/dataDownload.scss
  webapp/pages/Assessment/DataDownload/index.tsx
  webapp/pages/Assessment/assessment.less
  webapp/pages/Assessment/assessment.scss
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  webapp/style/_partials.scss
  webapp/style/_partials/_button.scss
  webapp/utils/breakpoints.ts
Labels: enhancement

#856 Dashboard mobile
  webapp/app/dataExport/useDataExportState.ts
  webapp/components/CountrySelect/LinkLanding/LinkLanding.tsx
  webapp/components/CountrySelect/countrySelect.scss
  webapp/components/hooks/index.ts
  webapp/components/hooks/useCountryLandingSections.ts
  webapp/main/styles/style.less
  webapp/pages/Assessment/Assessment.tsx
  webapp/pages/Assessment/assessment.scss
  webapp/pages/AssessmentDataDownload/dataDownload.scss
  webapp/pages/AssessmentDataDownload/index.tsx
  webapp/pages/AssessmentDataDownload/resources.ts
  webapp/pages/AssessmentHome/AssessmentHome.tsx
  webapp/pages/AssessmentHome/FraHome/FraHome.tsx
  webapp/pages/AssessmentHome/FraHome/components/CountrySelector.tsx
  webapp/pages/AssessmentHome/FraHome/components/SelectedCountries.tsx
  webapp/pages/AssessmentHome/FraHome/fraHome.scss
  webapp/pages/AssessmentHome/FraHome/index.ts
  webapp/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
  webapp/pages/AssessmentHome/PanEuropeanHome/index.ts
  webapp/pages/AssessmentHome/PanEuropeanHome/panEuropeanHome.scss
  webapp/pages/AssessmentHome/index.ts
  webapp/pages/StatisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.tsx
  webapp/pages/StatisticalFactsheets/CarbonGrowingStock/index.ts
  webapp/pages/StatisticalFactsheets/ForestArea/ForestArea.tsx
  webapp/pages/StatisticalFactsheets/ForestArea/index.ts
  webapp/pages/StatisticalFactsheets/ForestAreaPercent/ForestAreaPercent.tsx
  webapp/pages/StatisticalFactsheets/ForestAreaPercent/index.ts
  webapp/pages/StatisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  webapp/pages/StatisticalFactsheets/ForestAreaWithinProtectedAreas/index.ts
  webapp/pages/StatisticalFactsheets/ForestOwnership/ForestOwnership.tsx
  webapp/pages/StatisticalFactsheets/ForestOwnership/index.ts
  webapp/pages/StatisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  webapp/pages/StatisticalFactsheets/NaturallyRegeneratingForest/index.ts
  webapp/pages/StatisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  webapp/pages/StatisticalFactsheets/PrimaryDesignatedManagementObjective/index.ts
  webapp/pages/StatisticalFactsheets/PrimaryForest/PrimaryForest.tsx
  webapp/pages/StatisticalFactsheets/PrimaryForest/index.ts
  webapp/pages/StatisticalFactsheets/StatisticalFactsheets.scss
  webapp/pages/StatisticalFactsheets/StatisticalFactsheets.tsx
  webapp/pages/StatisticalFactsheets/common/levels.ts
  webapp/pages/StatisticalFactsheets/components/chart/Chart.tsx
  webapp/pages/StatisticalFactsheets/components/chart/index.ts
  webapp/pages/StatisticalFactsheets/components/table/index.ts
  webapp/pages/StatisticalFactsheets/components/table/table.tsx
  webapp/pages/StatisticalFactsheets/hooks/useStatisticalFactsheetsState.ts
  webapp/pages/StatisticalFactsheets/index.ts
  webapp/pages/StatisticalFactsheets/utils/apiUtils.ts
  webapp/pages/StatisticalFactsheets/utils/chartUtils.ts
  webapp/pages/StatisticalFactsheets/utils/numberUtils.ts
  webapp/pages/StatisticalFactsheets/utils/propUtils.ts
Labels: enhancement

#857 Fix country select modal desktop
  webapp/app/user/userManagement/edit/editUserForm/components/CountryRoles.tsx
  webapp/components/CountrySelectModal/CountrySelectModal.tsx
  webapp/components/CountrySelectModal/CountrySelectionModalBody.tsx
  webapp/components/CountrySelectModal/countrySelectModal.scss
  webapp/components/CountrySelectModal/index.ts
  webapp/components/CountrySelectionModal/index.ts
  webapp/components/modal.scss
  webapp/components/modal.tsx
  webapp/main/styles/style.less
  webapp/pages/AssessmentHome/FraHome/components/CountrySelector.tsx
  webapp/pages/AssessmentPrint/style.less
Labels: bug
