Repository openforis/fra-platform, pull requests merged in 2021-06, with the labels that each got.

#793 Refactor/countries endpoint 792
  server/api/country/getAll.ts
  server/api/country/getConfig.ts
  server/api/country/getRegionGroups.ts
  server/api/country/getRegions.ts
  server/api/country/updateConfig.ts
  server/api/userChat/create.ts
  server/assessment/sendAssessmentNotification.ts
  server/eof/fraValueService.ts
  server/panEuropean/panEuropeanApi.ts
  server/repository/country/countryRepository.ts
  server/repository/country/getAllCountries.ts
  server/repository/country/getAllCountriesList.ts
  server/repository/country/getAllowedCountries.ts
  server/repository/country/getCountry.ts
  server/repository/country/getCountryIsos.ts
  server/repository/country/getCountryProperties.ts
  server/repository/country/getDynamicCountryConfiguration.ts
  server/repository/country/getRegionCodes.ts
  server/repository/country/getRegionGroups.ts
  server/repository/country/getRegions.ts
  server/repository/country/handleCountryResult.ts
  server/repository/country/index.ts
  server/repository/country/saveDynamicConfigurationVariable.ts
  server/repository/index.ts
  server/repository/user/userRepository.ts
  server/service/assessment/annual/annualYearsExporter.ts
  server/service/assessment/exportService.ts
  server/service/assessment/exporter/countryConfigExporter.ts
  server/service/assessment/fraYears/fraYearsExporter.ts
  server/service/assessment/intervals/intervalYearsExporter.ts
  server/service/assessment/sdg/sdgExporter.ts
  server/service/country/countryService.ts
  server/service/country/getAllCountriesList.ts
  server/service/country/getAllowedCountries.ts
  server/service/country/getCountry.ts
  server/service/country/getCountryConfig.ts
  server/service/country/getCountryConfigFull.ts
  server/service/country/getCountryIsos.ts
  server/service/country/getRegionCodes.ts
  server/service/country/getRegionGroups.ts
  server/service/country/getRegions.ts
  server/service/country/index.ts
  server/service/index.ts
  server/service/statisticalFactsheets/service.ts
  server/user/sendInvitation.ts
Labels: refactor

#796 fix request as any issue
  server/api/country/getAll.ts
  server/api/middleware/auth.ts
  server/service/versioning/service.ts
  server/user/userApi.ts
Labels: bug

#795 Refactor/use api end points frontend
  common/api/endpoint/ApiEndPoint.ts
  server/api/auth/changePassword.ts
  server/api/auth/getInvitation.ts
  server/api/auth/login.ts
  server/api/auth/logout.ts
  server/api/auth/resetPassword.ts
  server/api/countryMessageBoard/get.ts
  webapp/app/assessment/components/dataTable/actions/generate.ts
  webapp/app/assessment/components/dataTable/actions/persist.ts
  webapp/app/assessment/components/dataTable/actions/read.ts
  webapp/app/assessment/components/review/actions.ts
  webapp/app/assessment/fra/sections/growingStock/actions.ts
  webapp/app/assessment/fra/sections/originalDataPoint/actions/actions.ts
  webapp/app/components/audit/actions.ts
  webapp/app/country/actions.ts
  webapp/app/countryLanding/actions.ts
  webapp/app/countryLanding/views/messageBoard/actions.ts
  webapp/app/user/chat/actions.ts
  webapp/app/user/userManagement/actions.ts
  webapp/pages/Admin/components/DataExportView/dataExportView.tsx
  webapp/pages/Login/actions.ts
  webapp/store/admin/actions.ts
  webapp/store/app/actions/index.ts
  webapp/store/app/reducer.ts
  webapp/store/user/actions.ts
Labels: bug, enhancement

#801 Upgrade dependencies
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: refactor

#803 chartWrapper: fix chart visibility on load
  webapp/app/assessment/components/dataTable/chart/chartContainer.tsx
  webapp/app/assessment/components/dataTable/chart/chartWrapper.tsx
  webapp/app/assessment/components/dataTable/chart/components/dataTrend.tsx
Labels: bug

#804 Major refactor: Introduce ODP in new structure (service,api,repository)
  server/api/country/getOverviewStatus.ts
  server/api/odp/createDraft.ts
  server/api/odp/delete.ts
  server/api/odp/deleteDraft.ts
  server/api/odp/get.ts
  server/api/odp/getMany.ts
  server/api/odp/getPrevious.ts
  server/api/odp/markAsActual.ts
  server/eof/api.ts
  server/eof/fraValueService.ts
  server/repository/index.ts
  server/repository/odp/createOdp.ts
  server/repository/odp/deleteDraft.ts
  server/repository/odp/deleteOdp.ts
  server/repository/odp/getAndCheckOdpCountryId.ts
  server/repository/odp/getOdp.ts
  server/repository/odp/getOdpVersionId.ts
  server/repository/odp/index.ts
  server/repository/odp/listAndValidateOriginalDataPoints.ts
  server/repository/odp/listOriginalDataPoints.ts
  server/repository/odp/markAsActual.ts
  server/repository/odp/odpRepository.ts
  server/repository/odp/odpRepositoryUtils.ts
  server/repository/odp/readEofOdps.ts
  server/repository/odp/readFocOdps.ts
  server/repository/odp/saveDraft.ts
  server/service/assessment/ndp/ndpExporter.ts
  server/service/index.ts
  server/service/odp/createOdp.ts
  server/service/odp/deleteDraft.ts
  server/service/odp/deleteOdp.ts
  server/service/odp/getOdp.ts
  server/service/odp/getOdpVersionId.ts
  server/service/odp/index.ts
  server/service/odp/listAndValidateOriginalDataPoints.ts
  server/service/odp/listOriginalDataPoints.ts
  server/service/odp/markAsActual.ts
  server/service/odp/readEofOdps.ts
  server/service/odp/readFocOdps.ts
  server/service/odp/saveDraft.ts
Labels: refactor

#807 SCSS setup
  package.json
  web-resources/index.html
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  webapp/pages/Landing/Introduction/AreaSelector/areaSelector.scss
  webapp/pages/Landing/Introduction/Introduction.tsx
  webapp/pages/Landing/Introduction/introduction.scss
  webapp/pages/Landing/KeyFinidings/KeyFindings.tsx
  webapp/pages/Landing/KeyFinidings/keyFindings.scss
  webapp/pages/Landing/Landing.tsx
  webapp/pages/Landing/landing.scss
  webapp/style/_partials.scss
  webapp/style/_partials/_breakpoints.scss
  webapp/style/_partials/_config.scss
  webpack.config.babel.js
  yarn.lock
Labels: enhancement, refactor

#809 Add header mobile layout
  .eslintrc.json
  core/lang.ts
  package.json
  webapp/app/components/navigation/components/assessment/header/status.tsx
  webapp/components/Header/FraHeader/FraHeader.tsx
  webapp/components/Header/Header.tsx
  webapp/components/Header/LanguageSelector/LanguageSelector.tsx
  webapp/components/Header/LanguageSelector/LanguageSelectorMobile.tsx
  webapp/components/Header/LanguageSelector/index.tsx
  webapp/components/Header/LanguageSelector/languageSelectorMobile.scss
  webapp/components/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  webapp/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  webapp/components/Header/components/languageSelection.tsx
  webapp/components/Header/header.less
  webapp/components/Header/header.scss
  webapp/components/PopoverControl/PopoverControl.tsx
  webapp/components/PopoverControl/index.tsx
  webapp/components/PopoverControl/popoverControl.scss
  webapp/components/popoverControl.tsx
  webapp/style/_partials.scss
  webapp/style/_partials/_spacing.scss
  yarn.lock
Labels: enhancement

#811 Footer mobile layout
  .eslintrc.json
  webapp/components/Footer/Footer.tsx
  webapp/components/Footer/components/sendFeedback.tsx
  webapp/components/Footer/footer.scss
  webapp/components/Footer/index.ts
  webapp/components/footer/footer.less
  webapp/components/footer/footer.tsx
  webapp/components/footer/index.ts
  webapp/pages/PageRoutes/PageRoutes.tsx
Labels: enhancement

#813 Home KeyFindings/Partners mobile layout
  webapp/components/Partners/Partners.tsx
  webapp/components/Partners/partners.less
  webapp/components/Partners/partners.scss
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  webapp/pages/Landing/Introduction/AreaSelector/areaSelector.scss
  webapp/pages/Landing/Introduction/Introduction.tsx
  webapp/pages/Landing/Introduction/introduction.scss
  webapp/pages/Landing/KeyFindings/KeyFindings.tsx
  webapp/pages/Landing/KeyFindings/index.ts
  webapp/pages/Landing/KeyFindings/keyFindings.scss
  webapp/pages/Landing/Landing.tsx
Labels: enhancement

#814 CountrySelect: PR #1
  webapp/app/user/userManagement/edit/countrySelectionModal.tsx
  webapp/app/user/userManagement/edit/editUserForm/editUserForm.less
  webapp/components/CountrySelect/AutoSaveStatus/AutoSaveStatus.tsx
  webapp/components/CountrySelect/AutoSaveStatus/autoSaveStatus.scss
  webapp/components/CountrySelect/AutoSaveStatus/index.ts
  webapp/components/CountrySelect/CountrySelect.tsx
  webapp/components/CountrySelect/LinkLanding/LinkLanding.tsx
  webapp/components/CountrySelect/LinkLanding/index.ts
  webapp/components/CountrySelect/LinkLanding/linkLanding.scss
  webapp/components/CountrySelect/components/CountryListFra/CountryListFra.tsx
  webapp/components/CountrySelect/components/CountryListFra/index.ts
  webapp/components/CountrySelect/components/CountryListPanEuropean/CountryListPanEuropean.tsx
  webapp/components/CountrySelect/components/CountryListPanEuropean/index.ts
  webapp/components/CountrySelect/components/countryList.less
  webapp/components/CountrySelect/components/countryList.tsx
  webapp/components/CountrySelect/components/countryListDownload.less
  webapp/components/CountrySelect/components/countryListDownload.tsx
  webapp/components/CountrySelect/components/countryListRoleSection.tsx
  webapp/components/CountrySelect/components/countryListRow.tsx
  webapp/components/CountrySelect/components/toggleNavigationControl.tsx
  webapp/components/CountrySelect/countrySelect.scss
  webapp/components/CountrySelect/index.ts
  webapp/components/CountrySelect/utils/checkMatch.ts
  webapp/components/CountrySelectionModal/CountrySelectionModal.tsx
  webapp/components/CountrySelectionModal/style.less
  webapp/components/PopoverControl/PopoverControl.tsx
  webapp/components/countrySelection/components/linkLanding.less
  webapp/components/countrySelection/index.ts
  webapp/main/styles/rtl.less
  webapp/main/styles/style.less
  webapp/pages/Assessment/assessment.less
  webapp/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  webapp/pages/Landing/Introduction/AreaSelector/areaSelector.scss
  webapp/pages/PageRoutes/PageRoutes.tsx
  webapp/style/_partials.scss
  webapp/style/_partials/_navigation.scss
  webapp/style/_partials/_status.scss
Labels: enhancement, refactor

#816 Fix production build
  common/countryRole.ts
  common/userUtils.ts
  server/api/auth/authConfig.ts
  server/dataTable/dataTableSqlCreator.ts
  server/dataTable/tableMappings.ts
  server/db/db.ts
  server/db/migration/execMigrations.js
  server/eof/estimationEngine.ts
  server/index.ts
  server/repository/assessment/assessmentRepository.ts
  server/repository/audit/auditRepository.ts
  server/repository/collaborators/collaboratorsRepository.ts
  server/repository/country/getAllCountriesList.ts
  server/repository/country/getCountry.ts
  server/repository/country/getCountryIsos.ts
  server/repository/country/getRegionCodes.ts
  server/repository/country/getRegionGroups.ts
  server/repository/country/getRegions.ts
  server/repository/country/handleCountryResult.ts
  server/repository/countryMessageBoard/countryMessageBoardRepository.ts
  server/repository/eof/fraRepository.ts
  server/repository/fileRepository/fileRepositoryRepository.ts
  server/repository/odp/getOdp.ts
  server/repository/review/reviewRepository.ts
  server/repository/statisticalFactsheets/statisticalFactsheetsRepository.ts
  server/repository/user/userRepository.ts
  server/repository/userChat/userChatRepository.ts
  server/repository/userResetPassword/userResetPasswordRepository.ts
  server/repository/versioning/versioningRepository.ts
  server/serverInit.ts
  server/service/email/sendMail.ts
  server/sessionInit.ts
  server/sustainableDevelopment/sustainableDevelopmentApi.ts
  tsconfig.json
  webapp/app/assessment/fra/sections/contactPersons/contactPersonsPrintView.tsx
  webapp/components/AssessmentComponent/AssessmentComponent.ts
  webapp/pages/Admin/components/UserManagementView/usersTableFilter.tsx
Labels: bug

#818 db/ssl: {rejectUnauthorized}
  server/db/db.ts
Labels: bug

#819 db: ssl/rejectUnauthorized: false
  server/db/db.ts
Labels: bug

#827 Fix issue with login
  server/api/auth/login.ts
  server/serverInit.ts
Labels: bug

#829 fix email invitation
  server/service/email/sendMail.ts
Labels: bug

#825 User consultation survey
  common/i18n/resources/ar.js
  common/i18n/resources/ar/uc.js
  common/i18n/resources/en.js
  common/i18n/resources/en/uc.js
  common/i18n/resources/es.js
  common/i18n/resources/es/uc.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/uc.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/uc.js
  common/i18n/resources/zh.js
  common/i18n/resources/zh/uc.js
  webapp/components/UserConsultationSurvey/UserConsultationSurvey.tsx
  webapp/components/UserConsultationSurvey/index.ts
  webapp/components/UserConsultationSurvey/userConsulationSurvey.scss
  webapp/pages/PageRoutes/PageRoutes.tsx
Labels: enhancement
