Repository openforis/fra-platform, pull requests merged in 2021-02, with the labels that each got.

#709 Update data download file 3_Forest_designation_and_management
  server/fileRepository/dataDownload/3_Forest_designation_and_management_en.ods
  server/fileRepository/dataDownload/3_Forest_designation_and_management_en.xlsx
Labels: enhancement

#720 migrations: add ru to mp country_region
  server/db/migration/migrations/20210209132834-add-value-country-region-mp-rus.js
  server/db/migration/migrations/sqls/20210209132834-add-value-country-region-mp-rus-down.sql
  server/db/migration/migrations/sqls/20210209132834-add-value-country-region-mp-rus-up.sql
Labels: bug

#721 migrations: add ben to itto country_region
  server/db/migration/migrations/20210210083639-add-value-country-region-itto-ben.js
  server/db/migration/migrations/sqls/20210210083639-add-value-country-region-itto-ben-down.sql
  server/db/migration/migrations/sqls/20210210083639-add-value-country-region-itto-ben-up.sql
Labels: bug

#722 Feature/paneuropean home
  common/i18n/resources/en.js
  common/i18n/resources/ru.js
  webapp/components/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  webapp/components/Header/PanEuropeanHeader/style.less
  webapp/components/hooks/useI18n.ts
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
  webapp/pages/Assessment/AssessmentHome/PanEuropeanHome/panEuropeanHome.less
  webapp/store/app/types.ts
Labels: enhancement

#723 Hotfix/fix production build ts
  README.md
  package.json
  server/assessment/assessmentRepository.ts
  server/assessment/sendAssessmentNotification.ts
  server/index.ts
  server/serverInit.ts
  tsconfig.server.json
  tsconfig.server.paths.json
  webpack.config.babel.js
  yarn-error.log
  yarn.lock
Labels: bug, infrastructure

#656 Custom regions/selector 653
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  server/statisticalFactsheets/service.ts
  webapp/app/countryLanding/views/statisticalFactsheets/hooks/useStatisticalFactsheetsState.ts
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.less
  webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.tsx
  webapp/app/dataExport/useDataExportState.ts
  webapp/app/user/userManagement/edit/countrySelectionModal.tsx
  webapp/components/CountrySelectionModal/CountrySelectionModal.tsx
  webapp/components/CountrySelectionModal/CountrySelectionModalBody.tsx
  webapp/components/CountrySelectionModal/index.ts
  webapp/components/CountrySelectionModal/style.less
  webapp/components/modal.less
  webapp/components/modal.tsx
  webapp/main/rootReducer.ts
  webapp/pages/Assessment/AssessmentHome/FraHome/FraHome.tsx
  webapp/pages/Assessment/AssessmentHome/FraHome/components/CountrySelector.tsx
  webapp/pages/Assessment/AssessmentHome/FraHome/components/SelectedCountries.tsx
  webapp/pages/Assessment/AssessmentHome/FraHome/fraHome.less
  webapp/store/app/hooks/index.ts
  webapp/store/ui/home/actions.ts
  webapp/store/ui/home/index.ts
  webapp/store/ui/home/reducer.ts
  webapp/store/ui/home/state.ts
  webapp/store/ui/index.ts
  webapp/store/ui/reducer.ts
  webapp/store/ui/state.ts
  webapp/store/ui/types.ts
Labels: enhancement

#724 i18n/{en,ru,es,fr}: added missing translations
  common/i18n/resources/en.js
  common/i18n/resources/es.js
  common/i18n/resources/fr.js
  common/i18n/resources/ru.js
  webapp/pages/Assessment/AssessmentHome/FraHome/components/CountrySelector.tsx
Labels: bug

#725 auditRepository: fix issue removing user when no countryIso
  server/audit/auditRepository.ts
Labels: bug

#726 dataPoints: fix label data
  webapp/app/assessment/components/dataTable/chart/components/dataPoints.tsx
Labels: bug

#727 verticallyGrowingTextField: refactor component, fix issue with printview
  webapp/app/assessment/components/review/reviewFooter.tsx
  webapp/components/verticallyGrowingTextField.tsx
Labels: bug

#732 yarn build:copy: copy definitions
  package.json
Labels: bug

#733 Version 2.3.8
  package.json
Labels: enhancement

#737 Hotfix/serve static 736
  package.json
  server/biomassStock/biomassStockApi.ts
  server/dataExport/api.ts
  server/definitions/api.ts
  server/fileRepository/fileRepository.ts
  server/landing/landingApi.ts
  server/static/avatar.png
  server/static/biomassStock/calculator_boreal_en.xlsx
  server/static/biomassStock/calculator_boreal_es.xlsx
  server/static/biomassStock/calculator_boreal_fr.xlsx
  server/static/biomassStock/calculator_boreal_ru.xlsx
  server/static/biomassStock/calculator_subtropical_en.xlsx
  server/static/biomassStock/calculator_subtropical_es.xlsx
  server/static/biomassStock/calculator_subtropical_fr.xlsx
  server/static/biomassStock/calculator_subtropical_ru.xlsx
  server/static/biomassStock/calculator_temperate_en.xlsx
  server/static/biomassStock/calculator_temperate_es.xlsx
  server/static/biomassStock/calculator_temperate_fr.xlsx
  server/static/biomassStock/calculator_temperate_ru.xlsx
  server/static/biomassStock/calculator_tropical_en.xlsx
  server/static/biomassStock/calculator_tropical_es.xlsx
  server/static/biomassStock/calculator_tropical_fr.xlsx
  server/static/biomassStock/calculator_tropical_ru.xlsx
  server/static/dataExport/README.txt
  server/static/definitions/en/faq.md
  server/static/definitions/en/tad.md
  server/static/definitions/es/faq.md
  server/static/definitions/es/tad.md
  server/static/definitions/fr/faq.md
  server/static/definitions/fr/tad.md
  server/static/definitions/ru/faq.md
  server/static/definitions/ru/tad.md
  server/static/fileRepository/dataDownload/1_Forest_extent_characteristics_and_changes_en.ods
  server/static/fileRepository/dataDownload/1_Forest_extent_characteristics_and_changes_en.xlsx
  server/static/fileRepository/dataDownload/2_Forest_growing_stock_biomass_and_carbon_en.ods
  server/static/fileRepository/dataDownload/2_Forest_growing_stock_biomass_and_carbon_en.xlsx
  server/static/fileRepository/dataDownload/3_Forest_designation_and_management_en.ods
  server/static/fileRepository/dataDownload/3_Forest_designation_and_management_en.xlsx
  server/static/fileRepository/dataDownload/4_Forest_ownership_and_management_rights_en.ods
  server/static/fileRepository/dataDownload/4_Forest_ownership_and_management_rights_en.xlsx
  server/static/fileRepository/dataDownload/6_Permanent_forest_estate_en.ods
  server/static/fileRepository/dataDownload/6_Permanent_forest_estate_en.xlsx
  server/static/fileRepository/panEuropeanQuestionnaire/panEuropeanQuestionnaire_en.xls
  server/static/fileRepository/panEuropeanQuestionnaire/panEuropeanQuestionnaire_ru.xls
  server/static/fileRepository/statisticalFactsheets/AF_en.ods
  server/static/fileRepository/statisticalFactsheets/AS_en.ods
  server/static/fileRepository/statisticalFactsheets/EU_en.ods
  server/static/fileRepository/statisticalFactsheets/NA_en.ods
  server/static/fileRepository/statisticalFactsheets/OC_en.ods
  server/static/fileRepository/statisticalFactsheets/SA_en.ods
  server/static/fileRepository/statisticalFactsheets/WO_en.ods
  server/static/fileRepository/userGuide/userGuide_en.pdf
  server/static/fileRepository/userGuide/userGuide_es.pdf
  server/static/fileRepository/userGuide/userGuide_fr.pdf
  server/static/fileRepository/userGuide/userGuide_ru.pdf
  server/static/landing/NSO_SDG_Contact_Persons_20171213.xlsx
  server/static/landing/NSO_SDG_Contact_Persons_20191230.xlsx
  server/user/userApi.ts
Labels: bug, refactor
