Repository openforis/fra-platform, pull requests merged in 2021-09, with the labels that each got.

#897 Data Export mobile
  webapp/components/Assessment/DataExport/ColumnSelect/ColumnSelect.tsx
  webapp/components/Assessment/DataExport/CountrySelect/CountrySelect.tsx
  webapp/components/Assessment/DataExport/DataExport.scss
  webapp/components/Assessment/DataExport/DataExport.tsx
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.scss
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx
  webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx
  webapp/style/_partials/_spacing.scss
Labels: enhancement

#894 Feature/redux toolkit
  package.json
  webapp/app/country/actions.ts
  webapp/app/countryLanding/views/contentCheck/contentCheck.tsx
  webapp/components/Assessment/DataTable/actions/generate.ts
  webapp/components/Assessment/DataTable/actions/update.ts
  webapp/components/Assessment/FraPrint/useFraPrintDataFetch.ts
  webapp/components/dynamicImport.tsx
  webapp/main.tsx
  webapp/main/axiosErrorMiddleware.ts
  webapp/main/store.ts
  webapp/pages/AssessmentSection/AssessmentSection.tsx
  webapp/pages/OriginalDataPoint/OriginalDataPoint.tsx
  webapp/sectionSpec/fra/originalDataPoint/actions/actions.ts
  webapp/store/RootState.ts
  webapp/store/axiosErrorMiddleware.ts
  webapp/store/index.ts
  webapp/store/reduxBatch.ts
  webapp/store/rootReducer.ts
  webapp/store/store.ts
  yarn.lock
Labels: enhancement, refactor

#900 Login - Reserved area
  common/i18n/resources/ar.js
  common/i18n/resources/ar/common.js
  common/i18n/resources/ar/login.js
  common/i18n/resources/en.js
  common/i18n/resources/en/common.js
  common/i18n/resources/en/login.js
  common/i18n/resources/es.js
  common/i18n/resources/es/common.js
  common/i18n/resources/es/login.js
  common/i18n/resources/fr.js
  common/i18n/resources/fr/common.js
  common/i18n/resources/fr/login.js
  common/i18n/resources/ru.js
  common/i18n/resources/ru/common.js
  common/i18n/resources/ru/login.js
  common/i18n/resources/zh.js
  common/i18n/resources/zh/common.js
  common/i18n/resources/zh/login.js
  webapp/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  webapp/components/Header/UserLinks/UserLinks.tsx
  webapp/pages/Login/Error/Error.tsx
  webapp/pages/Login/Error/error.scss
  webapp/pages/Login/Login.tsx
  webapp/pages/Login/LoginForm/LoginForm.tsx
  webapp/pages/Login/login.scss
  webpack.config.babel.js
Labels: enhancement

#907 Fix data export country select
  webapp/components/Assessment/DataExport/CountrySelect/CountrySelect.tsx
Labels: bug

#910 fix pan eu export
  .github/workflows/heroku-prod.js.yml
  core/utils/strings.ts
  package.json
  webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx
  yarn.lock
Labels: bug

#912 uc: update link
  webapp/components/UserConsultationSurvey/UserConsultationSurvey.tsx
Labels: enhancement

#913 v2.6.0
  package.json
Labels: enhancement

#914 Fix panEuropean 6.7 - 6.9
  common/i18n/resources/ar.js
  common/i18n/resources/en.js
  common/i18n/resources/ru.js
  common/i18n/resources/zh.js
  webapp/components/Assessment/DataExport/CountrySelect/CountrySelect.tsx
  webapp/sectionSpec/panEuropean/table_6_7/sectionSpec.ts
  webapp/sectionSpec/panEuropean/table_6_8/sectionSpec.ts
Labels: bug

#916 v2.6.1
  package.json
Labels: version

#917 panEuropean: fix table 6.9
  common/i18n/resources/ar.js
  common/i18n/resources/en.js
  common/i18n/resources/ru.js
  common/i18n/resources/zh.js
  webapp/sectionSpec/panEuropean/table_6_9/sectionSpec.ts
Labels: bug

#918 v2.6.2
  package.json
Labels: version

#925 Dashboard: Country select mobile
  webapp/components/CountrySelectModal/CountrySelectModal.tsx
  webapp/components/CountrySelectModal/CountrySelectModalBody/CountrySelectModalBody.tsx
  webapp/components/CountrySelectModal/CountrySelectModalBody/countrySelectModalBody.scss
  webapp/components/CountrySelectModal/countrySelectModal.scss
Labels: enhancement

#924 Rtk/app react i18n hook
  common/i18n/i18nFactory.ts
  package.json
  webapp/components/Chart/Chart.tsx
  webapp/hooks/useI18n.ts
  webapp/i18n.ts
  webapp/main.tsx
  webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  webapp/pages/PageRoutes/PageRoutes.tsx
  webapp/store/app/actions/actionTypes.ts
  webapp/store/app/actions/initApp.ts
  webapp/store/app/actions/switchLanguage.ts
  webapp/store/app/appSlice.ts
  webapp/store/app/hooks/index.ts
  webapp/store/app/reducer.ts
  webapp/store/app/types.ts
  webapp/store/page/dataExport/reducer.ts
  webapp/store/user/reducer.ts
  yarn.lock
Labels: enhancement, refactor
