Repository openforis/fra-platform, pull requests merged in 2022-09, with the labels that each got.

#1492 Fix user language selection
  src/client/components/Header/LanguageSelector/LanguageSelector.tsx
  src/client/store/assessment/actions/initApp.ts
Labels: bug

#1494 RFC: Initial commit for bulk download
  src/client/pages/AssessmentDataDownload/index.tsx
  src/meta/api/endpoint/ApiEndPoint.ts
  src/server/api/file/getBulkDownload.ts
  src/server/api/file/index.ts
  src/server/controller/cycleData/getBulkDownload.ts
  src/server/controller/cycleData/index.ts
  src/server/repository/assessmentCycle/data/bulkDownload.ts
  src/server/repository/assessmentCycle/data/index.ts
  web-resources/index.html
Labels: enhancement, refactor

#1503 Fix Google login
  src/client/hooks/useToaster.ts
  src/client/pages/Login/LoginForm/LoginForm.tsx
  src/server/api/auth/config.ts
Labels: bug

#1501 Migrate fra_audit -> assessment_{name}.activity_log
  src/meta/assessment/activityLog.ts
  src/meta/assessment/activityLogs.ts
  src/server/api/cycleData/table/postEstimation.ts
  src/server/controller/cycleData/persistNodeValue/index.ts
  src/server/controller/cycleData/persistNodeValues.ts
  src/server/db/migration/migrations/20220914111702-move-fra-audit-legacy.js
  src/server/db/migration/migrations/sqls/20220914111702-move-fra-audit-legacy-down.sql
  src/server/db/migration/migrations/sqls/20220914111702-move-fra-audit-legacy-up.sql
  src/server/repository/assessment/activityLog/getCycleDataActivities.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateActivityLog.ts
  tools/dataMigration/migrateUsers.ts
Labels: enhancement

#1507 Handle 2025 table columns metadata
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowNoticeMessage/RowNoticeMessage.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/client/pages/AssessmentSection/DataTable/Table/utils/getODPColSpan.ts
  src/client/pages/AssessmentSection/DataTable/Table/utils/parseTable.ts
  src/client/pages/AssessmentSection/DataTable/utils/index.ts
  src/meta/assessment/col.ts
  src/meta/assessment/cols.ts
  src/meta/assessment/index.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  src/server/repository/assessment/section/getManyMetadata.ts
  src/server/repository/assessmentCycle/node/updateValidation.ts
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/dataMigration/steps/metadataFix/metadataFix.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
  tools/dataMigration/migrateUsersRole.ts
Labels: infrastructure

#1514 fix calculated columns 2025
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/metadataFix/metadataFix.ts
Labels: infrastructure

#1515 Minor fixes to bulkdownload csv
  src/server/controller/cycleData/getBulkDownload.ts
  src/server/repository/assessmentCycle/data/bulkDownload.ts
Labels: enhancement

#1522 Master fix: table 1 other wooded land
  server/api/auth/logout.ts
  server/repository/originalDataPoint/getMany.ts
  yarn.lock
Labels: bug

#1525 Meta/minor fixes 2
  src/client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.scss
  src/client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx
  src/client/pages/Assessment/Assessment.tsx
  src/client/pages/AssessmentDataDownload/index.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  src/client/pages/Landing/Landing.tsx
  src/client/pages/OriginalDataPoint/components/Comments/CommentsEditor.tsx
  src/client/pages/PageRoutes/PageRoutes.tsx
Labels: bug, enhancement

#1530 Fix exhaustive-deps issue
  src/client/pages/DataExport/ResultsTable/useFetchResults.ts
Labels: bug

#1531 add data export data comparison script
  .eslintrc.js
  package.json
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/client/pages/AssessmentSection/DataTable/Table/utils/parseTable.ts
  src/server/controller/cycleData/getTableData.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNode.ts
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
  src/server/repository/assessmentCycle/data/getTableData.ts
  src/test/dataExportComparison/compareValue.ts
  src/test/dataExportComparison/countryIsos.ts
  src/test/dataExportComparison/fetchData.ts
  src/test/dataExportComparison/getMetadata.ts
  src/test/dataExportComparison/getMetadataLegacy.ts
  src/test/dataExportComparison/index.ts
  src/test/dataExportComparison/jest.config.js
  src/test/dataExportComparison/legacyMapping.ts
  src/test/dataExportComparison/types.ts
  src/test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
  src/test/dataMigration/steps/updateCalculatedNodes/getCertifiedAreaValues.ts
  src/test/dataMigration/steps/updateCalculatedNodes/getClimaticDomainValues.ts
  src/test/dataMigration/steps/updateCalculatedNodes/getTotalLandAreaValues.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/colSpecFactory.ts
  src/test/sectionSpec/descriptionsSpec.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/index.ts
  src/test/sectionSpec/rowSpec.ts
  src/test/sectionSpec/rowSpecFactory.ts
  src/test/sectionSpec/sectionSpec.ts
  src/test/sectionSpec/sectionSpecFactory.ts
  src/test/sectionSpec/tableSpec.ts
  src/test/sectionSpec/tableSpecFactory.ts
  src/test/sectionSpec/typeSpec.ts
  src/test/sectionSpec/unitSpec.ts
  src/test/sectionSpec/validation.ts
  src/test/sectionSpec/variables.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
Labels: infrastructure

#1536 Col Names fix: table intervals + forestPolicy
  src/client/pages/DataExport/ResultsTable/ResultsTable.tsx
  src/client/pages/DataExport/ResultsTable/useFetchResults.ts
  src/client/pages/DataExport/utils/checks.ts
  src/client/pages/DataExport/utils/format.ts
  src/client/pages/DataExport/utils/index.ts
  src/client/pages/DataExport/utils/labelKeys.ts
  src/test/dataExportComparison/compareValue.ts
  src/test/dataExportComparison/fetchData.ts
  src/test/dataExportComparison/legacyMapping.ts
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/postMetadataFix/postMetadataFix.ts
  src/test/sectionSpec/fraSpecs.ts
  src/utils/numbers.ts
Labels: infrastructure

#1545 Allow select empty for select fields
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Select/OptionNotSelected.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Select/Select.tsx
  src/client/utils/sanitizer/select.ts
Labels: enhancement

#1535 bulk download compare
  package.json
  src/client/store/pages/assessmentSection/actions/updateDescription.ts
  src/client/store/pages/assessmentSection/actions/updateNodeValues.ts
  src/client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts
  src/server/controller/cycleData/getBulkDownload.ts
  src/server/repository/assessmentCycle/data/query/tables.ts
  src/test/bulkDownloadComparison/compareFiles.ts
  src/test/bulkDownloadComparison/downloadFile.ts
  src/test/bulkDownloadComparison/getFileName.ts
  src/test/bulkDownloadComparison/index.ts
  src/test/bulkDownloadComparison/jest.config.js
  src/test/bulkDownloadComparison/readCSV.ts
  src/test/bulkDownloadComparison/types.ts
  src/test/dataExportComparison/compareValue.ts
  src/test/dataExportComparison/parseValue.ts
  yarn.lock
Labels: enhancement, infrastructure

#1547 Persist metadata, only on cycle change, reset
  src/client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  src/client/components/Navigation/NavigationDesktop/NavigationDesktop.tsx
  src/client/components/Navigation/NavigationMobile/NavigationMobile.tsx
  src/client/pages/Assessment/Assessment.tsx
  src/client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  src/client/pages/AssessmentSection/DataTable/DataTable.tsx
  src/client/store/pages/assessmentSection/hooks/useGetTableSections.ts
Labels: bug

#1553 Fix calculation 2b: totalIntroduced
  src/test/sectionSpec/fraSpecs.ts
Labels: bug

#1555 Use node ^16.13.0
  .github/workflows/heroku-dev.yml__
  .github/workflows/heroku-incubator.yml__
  .github/workflows/heroku-prod.js.yml__
  .github/workflows/test.js.yml
  package.json
Labels: infrastructure

#1550 Meta/print hide section
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/DataTable/DataTable.tsx
  src/client/store/pages/assessmentSection/hooks/index.ts
  src/meta/data/tableDatas.ts
Labels: enhancement

#1556 Refactor bulkdownload/Annual
  src/server/controller/cycleData/getBulkDownload/climaticDomain.ts
  src/server/controller/cycleData/getBulkDownload/entries/AnnualData.ts
  src/server/controller/cycleData/getBulkDownload/entries/FRAYears.ts
  src/server/controller/cycleData/getBulkDownload/entries/Intervals.ts
  src/server/controller/cycleData/getBulkDownload/genders.ts
  src/server/controller/cycleData/getBulkDownload/getClimaticValue.ts
  src/server/controller/cycleData/getBulkDownload/getContent.ts
  src/server/controller/cycleData/getBulkDownload/getData.ts
  src/server/controller/cycleData/getBulkDownload/getFRAYearsData.ts
  src/server/controller/cycleData/getBulkDownload/getYears.ts
  src/server/controller/cycleData/getBulkDownload/index.ts
  src/server/controller/cycleData/getBulkDownload/props.ts
  src/server/repository/assessmentCycle/data/bulkDownload.ts
  src/server/repository/assessmentCycle/data/index.ts
  src/server/repository/assessmentCycle/data/query/genderTables.ts
  src/server/repository/assessmentCycle/data/query/getAreaOfPermanentForestEstateQuery.ts
  src/server/repository/assessmentCycle/data/query/getClimaticDomainQuery.ts
  src/server/repository/assessmentCycle/data/query/getForestPolicyQuery.ts
  src/server/repository/assessmentCycle/data/query/getFraYearsDataQuery.ts
  src/server/repository/assessmentCycle/data/query/getRegionsQuery.ts
  src/server/repository/assessmentCycle/data/query/getYearsQuery.ts
  src/server/repository/assessmentCycle/data/query/tables.ts
  src/test/bulkDownloadComparison/compareFiles.ts
Labels: enhancement, refactor

#1565 ext_data.taxon migration
  src/server/db/migration/migrations/20220929110801-table-taxon.js
  src/server/db/migration/migrations/sqls/20220929110801-table-taxon-down.sql
  src/server/db/migration/migrations/sqls/20220929110801-table-taxon-up.sql
Labels: enhancement

#1564 meta migration: insert metadata in batch
  src/meta/assessment/tableSection.ts
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/metadataFix/metadataFix.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getTableSection.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
Labels: infrastructure

#1566 Taxon search api
  src/meta/api/endpoint/ApiEndPoint.ts
  src/meta/assessment/node.ts
  src/meta/extData/index.ts
  src/meta/extData/taxon.ts
  src/server/api/api.ts
  src/server/api/extData/index.ts
  src/server/api/extData/searchTaxa.ts
  src/server/controller/extData/index.ts
  src/server/repository/extData/index.ts
  src/server/repository/extData/search.ts
Labels: enhancement

#1568 Metadata 2025: remove subsections 1e / 7a/ 7a and table total in 3a
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/rowSpec.ts
  src/test/sectionSpec/sectionSpec.ts
  src/test/sectionSpec/tableSpec.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getRow.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/dataMigration/migrateMetadata/getTable.ts
  tools/dataMigration/migrateMetadata/getTableSection.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/utils.ts
Labels: infrastructure
