Repository openforis/fra-platform, pull requests merged in 2022-02, with the labels that each got.

#1129 Meta/UI country status
  client/basePaths.ts
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/components/Modal/Modal.scss
  client/components/Modal/Modal.tsx
  client/components/Modal/index.ts
  client/components/Navigation/NavAssessment/Header/Header.tsx
  client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.tsx
  client/components/Navigation/Navigation.tsx
  client/pages/Assessment/Assessment.tsx
  client/store/assessment/actions/getCountryStatus.ts
  client/store/assessment/actions/postCountryStatus.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/slice.ts
  client/store/assessment/stateType.ts
  i18n/resources/ar.js
  i18n/resources/en.js
  i18n/resources/es.js
  i18n/resources/fr.js
  i18n/resources/ru.js
  i18n/resources/zh.js
  meta/assessment/assessments.ts
  meta/assessment/countryStatus.ts
  meta/assessment/index.ts
  meta/user/users.ts
  server/api/assessment/getOdp.ts
  server/api/assessment/index.ts
  server/api/assessment/postCountryStatus.ts
  server/api/init/init.ts
  server/controller/assessment/index.ts
  server/controller/assessment/updateCountryStatus.ts
  server/repository/assessment/index.ts
  server/repository/assessment/updateCountryStatus.ts
  server/repository/user/index.ts
  server/repository/user/read.ts
  server/repository/user/readCountryUsersByRole.ts
  server/service/mail/assessmentNotifyUsers.ts
  server/service/mail/mail.ts
  server/utils/requests.ts
Labels: enhancement, refactor

#1133 add wwwhisper / add github action deploy incubator
  .github/workflows/heroku-incubator.yml
  package.json
  server/serverInit.ts
  yarn.lock
Labels: infrastructure

#1137 Dependencies upgrade / deploy fix
  common/countryRole.ts
  common/validateOriginalDataPoint.ts
  i18n/i18nFactory.ts
  package.json
  server/api/definitions/utils/getHtml.ts
  tsconfig.server.paths.json
  webpack.config.babel.js
  yarn.lock
Labels: infrastructure

#1139 Meta/default cycle
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  client/store/assessment/hooks/index.ts
  client/store/assessment/hooks/useCycle.ts
  client/store/assessment/index.ts
  meta/assessment/assessment.ts
  server/api/assessment/getCountryStatus.ts
  server/api/assessment/getSections.ts
  server/api/init/init.ts
  server/api/user/acceptInvitation.ts
  server/api/user/getByInvitation.ts
  tools/dataMigration/index.ts
Labels: enhancement, refactor

#1144 Growing Stock tables migration
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/getNodeInsertsTableWithODP.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: infrastructure

#1150 Add and generate Assessment meta cache
  .github/workflows/heroku-dev.yml
  .github/workflows/heroku-incubator.yml
  .github/workflows/heroku-prod.js.yml
  .github/workflows/test.js.yml
  meta/assessment/assessment.ts
  meta/assessment/assessmentMetaCache.ts
  meta/assessment/index.ts
  meta/assessment/row.ts
  package.json
  server/db/migration/migrations/20220210201113-add-assessment-meta-cache-column.js
  server/db/migration/migrations/sqls/20220210201113-add-assessment-meta-cache-column-down.sql
  server/db/migration/migrations/sqls/20220210201113-add-assessment-meta-cache-column-up.sql
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/binary.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/call.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/compound.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/context.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/group.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/identifier.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/index.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/literal.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/member.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/this.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/unary.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/index.ts
  tools/dataMigration/generateMetaCache/index.ts
  tools/dataMigration/getRow.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
  webapp/sectionSpec/rowSpec.ts
  yarn.lock
Labels: enhancement

#1152 fix build / add yarn build to test action
  .github/workflows/test.js.yml
  server/api/assessment/getOdp.ts
Labels: bug

#1156 Assessment/pages/Section
  client/components/Tooltip/Tooltip.scss
  client/components/Tooltip/Tooltip.tsx
  client/components/Tooltip/index.ts
  client/pages/Assessment/pages/Section/Section.scss
  client/pages/Assessment/pages/Section/Section.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/AnalysisDescriptions/AnalysisDescriptions.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/AnalysisDescriptions/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/CommentableDescription/CommentableDescription.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/CommentableDescription/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Description.scss
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Description.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Title/Title.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Title/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Toggle/Toggle.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/Description/Toggle/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/Description/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/Description/useDescription.ts
  client/pages/Assessment/pages/Section/components/Descriptions/Descriptions.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/GeneralComments/GeneralComments.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/GeneralComments/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/NationalDataDescriptions/NationalDataDescriptions.tsx
  client/pages/Assessment/pages/Section/components/Descriptions/NationalDataDescriptions/index.ts
  client/pages/Assessment/pages/Section/components/Descriptions/index.ts
  client/pages/Assessment/pages/Section/components/SectionHeader/ExtentOfForest/ExtentOfForest.tsx
  client/pages/Assessment/pages/Section/components/SectionHeader/ExtentOfForest/index.ts
  client/pages/Assessment/pages/Section/components/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx
  client/pages/Assessment/pages/Section/components/SectionHeader/ForestCharacteristics/index.ts
  client/pages/Assessment/pages/Section/components/SectionHeader/SectionHeader.ts
  client/pages/Assessment/pages/Section/components/SectionHeader/index.ts
  client/pages/Assessment/pages/Section/components/SectionHeader/props.ts
  client/pages/Assessment/pages/Section/components/Title/ExtentOfForest/ExtentOfForest.tsx
  client/pages/Assessment/pages/Section/components/Title/ExtentOfForest/index.ts
  client/pages/Assessment/pages/Section/components/Title/ForestCharacteristics/ForestCharacteristics.tsx
  client/pages/Assessment/pages/Section/components/Title/ForestCharacteristics/index.ts
  client/pages/Assessment/pages/Section/components/Title/Title.tsx
  client/pages/Assessment/pages/Section/components/Title/TitleExcelCalculator/ExcelCalculatorDownload.tsx
  client/pages/Assessment/pages/Section/components/Title/TitleExcelCalculator/TitleExcelCalculator.scss
  client/pages/Assessment/pages/Section/components/Title/TitleExcelCalculator/TitleExcelCalculator.tsx
  client/pages/Assessment/pages/Section/components/Title/TitleExcelCalculator/index.ts
  client/pages/Assessment/pages/Section/components/Title/index.ts
  client/pages/Assessment/pages/Section/components/Title/props.ts
  client/store/assessment/hooks/index.ts
  client/store/pages/assessmentSection/hooks/index.ts
  client/store/pages/assessmentSection/stateType.ts
Labels: refactor

#1158 fix assessment ddl
  server/controller/assessment/remove.ts
  server/repository/assessment/removeAssessmentSchema.ts
  server/repository/assessmentCycle/removeSchema.ts
Labels: bug

#1159 add datatable
  .eslintrc.json
  client/components/ButtonTableExport/ButtonTableExport.scss
  client/components/ButtonTableExport/ButtonTableExport.tsx
  client/components/ButtonTableExport/index.ts
  client/components/ButtonTableExport/utils.ts
  client/components/CountrySelect/CountryList/CountryList.tsx
  client/components/TextInput/TextInput.scss
  client/components/TextInput/TextInput.tsx
  client/components/TextInput/index.tsx
  client/components/ThousandSeparatedIntegerInput/ThousandSeparatedIntegerInput.scss
  client/components/ThousandSeparatedIntegerInput/ThousandSeparatedIntegerInput.tsx
  client/components/ThousandSeparatedIntegerInput/index.ts
  client/pages/Assessment/pages/Section/Section.tsx
  client/pages/Assessment/pages/Section/components/DataTable/DataTable.scss
  client/pages/Assessment/pages/Section/components/DataTable/DataTable.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/CellOdpHeader/CellOdpHeader.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/CellOdpHeader/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/Row.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Calculated/Calculated.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Calculated/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Cell.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Number/Number.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Number/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Placeholder/Placeholder.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Placeholder/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Select/Select.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Select/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Text/Text.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Text/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/props.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/sanitizer.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/useClassName.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/useOnChange.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/CellOdp/CellOdp.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/CellOdp/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/CellOdp/props.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/CellOdp/useOnChange.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/useClassName.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowNoticeMessage/RowNoticeMessage.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowNoticeMessage/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowValidation/RowValidation.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowValidation/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/props.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Table.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/index.ts
  client/pages/Assessment/pages/Section/components/DataTable/printUtils.ts
  client/store/pages/assessmentSection/actions/getTableSections.ts
  client/store/pages/assessmentSection/slice.ts
  client/store/pages/assessmentSection/stateType.ts
  server/repository/assessment/getSectionMetaData.ts
Labels: refactor

#1162 fix cycle data / getCountry Iso repository
  server/controller/assessment/getCountryISOs.ts
  server/repository/assessment/getCountryISOs.ts
  server/repository/cycleData/getTableData.ts
Labels: bug

#1161 initial commit for datatable cells
  client/pages/Assessment/pages/Section/Section.tsx
  client/pages/Assessment/pages/Section/components/DataTable/DataTable.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/Cell.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/Cell/useOnChange.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/Assessment/pages/Section/components/DataTable/Table/Row/props.ts
  client/pages/Assessment/pages/Section/components/DataTable/Table/Table.tsx
  client/pages/Assessment/pages/Section/components/DataTable/utils/index.ts
  client/store/pages/assessmentSection/actions/getTableData.ts
  client/store/pages/assessmentSection/slice.ts
  client/store/pages/assessmentSection/stateType.ts
  core/utils/objects/camelize.ts
  meta/data/index.ts
  meta/data/tableDatas.ts
  server/api/assessment/getTableData.ts
  server/api/assessment/index.ts
  server/controller/assessment/getTableData.ts
  server/controller/assessment/index.ts
  server/controller/cycleData/getTableData.ts
  server/controller/cycleData/index.ts
  server/controller/cycleData/persistNodeValue/evalExpression.ts
  server/repository/assessment/index.ts
  server/repository/assessment/readTableData.ts
  server/repository/cycleData/getTableData.ts
  server/repository/cycleData/index.ts
Labels: enhancement, refactor
