Repository openforis/fra-platform, pull requests merged in 2022-04, with the labels that each got.

#1219 datatable review indicator integration
  client/components/MessageCenter/Topic/Message/Message.scss
  client/components/MessageCenter/Topic/Message/Message.tsx
  client/components/MessageCenter/Topic/Message/index.ts
  client/components/MessageCenter/Topic/Topic.scss
  client/components/MessageCenter/Topic/Topic.tsx
  client/components/ReviewIndicator/ReviewIndicator.tsx
  client/store/ui/messageCenter/actions/addMessage.ts
  client/store/ui/messageCenter/actions/index.ts
  client/store/ui/messageCenter/actions/openTopic.ts
  client/store/ui/messageCenter/slice.ts
  common/api/endpoint/ApiEndPoint.ts
  core/utils/dates.ts
  meta/messageCenter/messageTopic.ts
  meta/user/userProfilePicture.ts
  server/api/user/getProfilePicture.ts
  server/api/user/index.ts
  server/controller/messageCenter/getTopic.ts
  server/controller/user/index.ts
  server/repository/messageTopic/getOneOrNone.ts
  server/repository/user/getProfilePicture.ts
  server/repository/user/index.ts
  server/static/avatar.png
Labels: refactor

#1232 migrate calculations table 1d
  .github/workflows/test.js.yml
  package.json
  server/controller/cycleData/persistNodeValue/expressionEvaluator/binary.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/context.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/member.ts
  server/repository/cycleData/getOriginalDataPointData.ts
  test/dataMigration/postDataMigration.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/binary.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/call.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/compound.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/context.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/identifier.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/index.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/literal.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/member.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/this.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/unary.ts
  tools/dataMigration/migrateMetadata/index.ts
  webapp/sectionSpec/rowSpec.ts
  yarn.lock
Labels: enhancement

#1235 add .npmrc / fix heroku deploy
  .npmrc
Labels: enhancement

#1234 migrate calculations of tables 2a/2b
  server/repository/assessment/read.ts
  test/dataMigration/postDataMigration.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: enhancement

#1221 BE Migrations for Table 1b: Use National Data Points
  client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  client/pages/Assessment/Assessment.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/pages/AssessmentSection/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx
  client/store/assessment/actions/getCountry.ts
  client/store/assessment/actions/postCountryStatus.ts
  client/store/assessment/actions/updateCountry.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/slice.ts
  client/store/assessment/stateType.ts
  client/store/pages/assessmentSection/hooks/index.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/area/country.ts
  meta/assessment/activityLog.ts
  meta/assessment/assessments.ts
  meta/assessment/countryStatus.ts
  meta/assessment/index.ts
  meta/user/authorizer.ts
  server/api/assessment/getCountry.ts
  server/api/assessment/index.ts
  server/api/assessment/postCountry.ts
  server/api/assessment/postCountryStatus.ts
  server/api/init/init.ts
  server/controller/assessment/getCountryISOs.ts
  server/controller/assessment/getCountryStatus.ts
  server/controller/assessment/getOne.ts
  server/controller/assessment/getRegionGroups.ts
  server/controller/assessment/index.ts
  server/controller/assessment/updateCountry.ts
  server/controller/assessment/updateCountryStatus.ts
  server/db/migration/migrations/20220406151611-move-to-legacy-dynamic-country-configuration.js
  server/db/migration/migrations/sqls/20220406151611-move-to-legacy-dynamic-country-configuration-down.sql
  server/db/migration/migrations/sqls/20220406151611-move-to-legacy-dynamic-country-configuration-up.sql
  server/repository/assessment/getCountry.ts
  server/repository/assessment/getCountryISOs.ts
  server/repository/assessment/getCountryStatus.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  server/repository/assessment/getRegionGroups.ts
  server/repository/assessment/index.ts
  server/repository/assessment/updateCountry.ts
  server/repository/assessment/updateCountryStatus.ts
  server/service/mail/assessmentNotifyUsers.ts
  server/utils/requests.ts
  test/dataMigration/postDataMigration.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateAreas.ts
  tools/dataMigration/migrateData/migrateCountryStatus.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
Labels: enhancement, refactor

#1236 migrate calculations section 3/4/5/7 + forestArea.totalLandArea
  server/controller/cycleData/persistNodeValue/expressionEvaluator/conditional.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/member.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/sequence.ts
  server/repository/cycleData/getTableData.ts
  test/dataMigration/postDataMigration.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/conditional.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/index.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/sequence.ts
Labels: enhancement

#1238 Fix Heroku deploy
  .github/workflows/heroku-dev.yml
  .github/workflows/heroku-incubator.yml
  .github/workflows/heroku-prod.js.yml
  package.json
Labels: infrastructure

#1239 remove countryStatus, use country.props
  client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.tsx
  client/pages/Assessment/Assessment.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/pages/AssessmentSection/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx
  client/store/assessment/actions/getCountryStatus.ts
  client/store/assessment/actions/postCountryStatus.ts
  client/store/assessment/actions/updateCountry.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  client/store/assessment/slice.ts
  client/store/assessment/stateType.ts
  client/store/pages/assessmentSection/hooks/index.ts
  client/store/user/hooks/index.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/area/country.ts
  meta/assessment/assessments.ts
  meta/user/authorizer.ts
  server/api/assessment/getCountryStatus.ts
  server/api/assessment/index.ts
  server/api/assessment/postCountry.ts
  server/api/assessment/postCountryStatus.ts
  server/controller/assessment/getCountryStatus.ts
  server/controller/assessment/index.ts
  server/controller/assessment/updateCountryStatus.ts
  server/middleware/auth.ts
  server/repository/assessment/getCountryStatus.ts
  server/repository/assessment/index.ts
  server/repository/assessment/updateCountry.ts
  server/repository/assessment/updateCountryStatus.ts
  server/service/mail/assessmentNotifyUsers.ts
Labels: refactor

#1243 dataexport page
  client/pages/Assessment/Assessment.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/DataExport/DataExport.scss
  client/pages/DataExport/DataExport.tsx
  client/pages/DataExport/index.ts
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
Labels: enhancement

#1249 Migrate calculations section 8
  server/controller/cycleData/persistNodeValue/expressionEvaluator/binary.ts
  test/dataMigration/postDataMigration.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/member.ts
Labels: enhancement

#1254 remove unused api
  common/api/endpoint/ApiEndPoint.ts
  server/api/definitions/index.ts
Labels: refactor

#1255 simple import sort
  .eslintrc.js
  .eslintrc.json
  client/Main.tsx
  client/basePaths.ts
  client/i18n.ts
  package.json
  yarn.lock
Labels: enhancement

#1259 cache table sections metadata
  client/components/AssessmentSwitch/AssessmentSwitch.tsx
  client/hooks/index.ts
  client/hooks/useOnUpdate.ts
  client/pages/Assessment/Assessment.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/assessment/hooks/useCycle.ts
  client/store/pages/assessmentSection/actions/getTableSections.ts
  client/store/pages/assessmentSection/actions/setTableSections.ts
  client/store/pages/assessmentSection/hooks/index.ts
  client/store/pages/assessmentSection/slice.ts
  client/store/pages/assessmentSection/stateType.ts
  webpack.config.babel.js
Labels: enhancement, refactor

#1260 Migrate row chart props
  meta/assessment/row.ts
  tools/dataMigration/migrateMetadata/getRow.ts
Labels: enhancement

#1269 chart
  client/hooks/index.ts
  client/hooks/useOnResize.ts
  client/hooks/usePrevious.ts
  client/pages/AssessmentSection/DataTable/Chart/chart.ts
  client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx
  client/pages/AssessmentSection/DataTable/Chart/chartWrapper.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/dataPath.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/dataPoints.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/dataTrend.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/legend.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/noDataPlaceholder.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/odpTicks.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/xAxis.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/yAxis.tsx
  client/pages/AssessmentSection/DataTable/Chart/index.ts
  client/pages/AssessmentSection/DataTable/Chart/style.scss
  client/pages/AssessmentSection/DataTable/Chart/useChartData.ts
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/store/pages/assessmentSection/hooks/index.ts
  client/utils/domUtils.ts
Labels: enhancement, refactor

#1270 add required props for dataexport
  meta/assessment/row.ts
  tools/dataMigration/migrateMetadata/getRow.ts
  webapp/sectionSpec/rowSpec.ts
Labels: enhancement, refactor

#1273 Fix odp forestArea variable name / Migrate data all cycles
  meta/assessment/cols.ts
  server/db/db.ts
  server/repository/assessment/assessment/getCreateSchemaDDL.ts
  server/repository/assessmentCycle/data/getOriginalDataPointData.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
Labels: bug, enhancement

#1276 Fix tooltip on odp
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
Labels: bug, enhancement

#1274 Meta/sorja/odp cell no edit
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  meta/assessment/node.ts
  meta/data/tableDatas.ts
  server/repository/assessmentCycle/data/getOriginalDataPointData.ts
Labels: bug

#1277 Metadata fixes
  client/components/CountrySelect/LinkLanding/LinkLanding.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Calculated/Calculated.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/props.ts
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  meta/assessment/col.ts
  meta/assessment/index.ts
  meta/assessment/label.ts
  meta/assessment/row.ts
  meta/assessment/table.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getRow.ts
  tools/dataMigration/migrateMetadata/getTable.ts
  webapp/sectionSpec/rowSpec.ts
Labels: bug, enhancement

#1281 ActivityLog: add cycle_uuid, replace schemaName with cycle, assessment
  server/controller/assessment/create.ts
  server/controller/assessment/createCycle.ts
  server/controller/assessment/createOriginalDataPoint.ts
  server/controller/assessment/removeOriginalDataPoint.ts
  server/controller/assessment/updateCountry.ts
  server/controller/assessment/updateOriginalDataPoint.ts
  server/controller/cycleData/persistNodeValue/createOrUpdateNode.ts
  server/controller/messageCenter/addMessage.ts
  server/controller/user/invite.ts
  server/repository/assessment/activityLog/insertActivityLog.ts
  server/repository/assessment/assessment/getCreateSchemaDDL.ts
  server/repository/public/userRole/create.ts
  test/integration/integration.test.ts
  test/integration/user/userInvite.ts
Labels: refactor

#1283 countrySelect: fix font family
  client/components/CountrySelect/countrySelect.scss
Labels: bug

#1284 datatable/Chart: Fix issues with chart:
  client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx
  client/pages/AssessmentSection/DataTable/Chart/components/xAxis.tsx
Labels: bug

#1285 add section dataExport property
  client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  meta/assessment/section.ts
  tools/dataMigration/migrateMetadata/getSection.ts
Labels: enhancement

#1288 Websocket review
  client/components/MessageCenter/Topic/Message/Message.tsx
  client/components/MessageCenter/Topic/Topic.scss
  client/components/MessageCenter/Topic/Topic.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/service/socket/index.ts
  client/service/socket/socketClient.ts
  client/store/axiosErrorMiddleware.ts
  client/store/ui/messageCenter/actions/index.ts
  client/store/ui/messageCenter/actions/postMessage.ts
  client/store/ui/messageCenter/slice.ts
  meta/socket/index.ts
  meta/socket/sockets.ts
  package.json
  server/api/assessment/getSections.ts
  server/api/auth/login.ts
  server/api/messageCenter/addMessage.ts
  server/controller/messageCenter/addMessage.ts
  server/index.ts
  server/repository/assessmentCycle/message/create.ts
  server/serverInit.ts
  server/service/socket/index.ts
  server/service/socket/socketService.ts
  test/dataMigration/jest.config.js
  test/integration/messageCenter/messageCenter.ts
  webpack.config.babel.js
  yarn.lock
Labels: enhancement

#1291 Nullcheck tableData
  client/store/pages/assessmentSection/hooks/index.ts
Labels: bug
