Repository openforis/fra-platform, pull requests merged in 2022-06, with the labels that each got.

#1354 Initial commit for Country Selection
  client/components/CountrySelectModal/CountrySelectModal.tsx
  client/components/CountrySelectModal/CountrySelectModalBody/CountrySelectModalBody.tsx
  client/components/CountrySelectModal/CountrySelectModalBody/countrySelectModalBody.scss
  client/components/CountrySelectModal/CountrySelectModalBody/index.ts
  client/components/CountrySelectModal/countrySelectModal.scss
  client/components/CountrySelectModal/index.ts
  client/pages/AssessmentHome/AssessmentHome.scss
  client/pages/AssessmentHome/FraHome/CountrySelector/CountrySelector.tsx
  client/pages/AssessmentHome/FraHome/CountrySelector/index.ts
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/SelectedCountries/SelectedCountries.tsx
  client/pages/AssessmentHome/FraHome/SelectedCountries/index.ts
  client/store/RootState.ts
  client/store/assessment/hooks/index.ts
  client/store/rootReducer.ts
  client/store/ui/home/hooks.ts
  client/store/ui/home/slice.ts
  client/store/ui/home/stateType.ts
  meta/area/areas.ts
Labels: enhancement, refactor

#1357 Cycle Switcher
  client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx
  client/components/Navigation/NavAssessment/Header/Title/Title.tsx
  client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
Labels: enhancement

#1361 CycleSwitcher/canSwitchCycle: check user cycles
  client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx
Labels: bug

#1362 upgrade react/react-dom/react-redux
  package.json
  yarn.lock
Labels: enhancement

#1365 schemaCycle.value_aggregate migration
  server/db/migration/migrations/20220608102551-move-views-to-legacy.js
  server/db/migration/migrations/sqls/20220608102551-move-views-to-legacy-down.sql
  server/db/migration/migrations/sqls/20220608102551-move-views-to-legacy-up.sql
  server/repository/assessment/assessment/getCreateSchemaDDL.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/migrateAggregates.ts
Labels: refactor

#1364 Migrate validations section 1
  server/controller/cycleData/persistNodeValue/expressionEvaluator/evaluators/array.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/evaluators/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorGreaterThenOrZero.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorNotGreaterThanForest.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorOtherLand.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorOtherLandWithTreeCoverTotal.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorPlantationForestIntroduced.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorPrimaryForest.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorTotalForest.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/dependencyEvaluator/evalDependencies/array.ts
  tools/dataMigration/generateMetaCache/dependencyEvaluator/evalDependencies/index.ts
  webapp/app/assessment/assessmentStateValidator.ts
  webapp/sectionSpec/fra/extentOfForest/extentOfForestValidatorState.ts
  webapp/sectionSpec/fra/forestCharacteristics/forestCharacteristicsValidatorState.ts
  webapp/sectionSpec/fra/otherLandWithTreeCover/otherLandWithTreeCoverValidatorState.ts
  webapp/sectionSpec/fra/specificForestCategories/specificForestCategoriesValidatorState.ts
Labels: enhancement

#1369 migrate validations section 2
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorEqualToTotalGrowingStock.ts
  tools/dataMigration/fraSpecs.ts
  webapp/sectionSpec/fra/growingStock/growingStockValidatorState.ts
Labels: enhancement

#1370 Meta/get aggregated data
  client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  client/pages/Dashboard/Dashboard.tsx
  client/pages/Dashboard/ForestArea/ForestArea.tsx
  client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  client/pages/Dashboard/hooks/useDashboardData.ts
  server/api/assessment/getTableData.ts
  server/controller/cycleData/getTableData.ts
  server/repository/assessmentCycle/data/getAggregatedTableData.ts
  server/repository/assessmentCycle/data/index.ts
Labels: enhancement, refactor

#1371 Add region dashboard
  client/pages/Dashboard/Dashboard.tsx
  client/pages/Dashboard/ForestArea/ForestArea.tsx
  client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  meta/assessment/table.ts
  server/repository/assessmentCycle/data/getAggregatedTableData.ts
Labels: enhancement, refactor

#1372 added requireInviteUser and requireViewUsers
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/InviteUserForm/InviteUserForm.scss
  client/components/InviteUserForm/InviteUserForm.tsx
  client/components/UserList/UserList.tsx
  client/pages/AssessmentHome/FraHome/Collaborators/Collaborators.tsx
  meta/user/authorizer.ts
  server/api/user/index.ts
  server/middleware/auth.ts
  server/service/mail/userInvite.ts
Labels: enhancement

#1374 Add global dashboard, use TableDatas to extract NodeValue
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/useOnChange.ts
  client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  client/pages/Dashboard/Dashboard.tsx
  client/pages/Dashboard/ForestArea/ForestArea.tsx
  client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  meta/data/tableDatas.ts
  server/repository/assessmentCycle/data/getAggregatedTableData.ts
Labels: bug, enhancement, refactor

#1376 validate all calculated and validation dependents nodes
  client/Main.tsx
  client/pages/AssessmentSection/DataTable/utils/index.ts
  meta/data/index.ts
  meta/data/nodeUpdates.ts
  meta/data/tableDatas.ts
  server/controller/cycleData/persistNodeValue/index.ts
  server/controller/cycleData/persistNodeValue/persistCalculationDependants/evaluateNode.ts
  server/controller/cycleData/persistNodeValue/persistCalculationDependants/persistCalculationDependants.ts
  server/controller/cycleData/persistNodeValue/validateNode/index.ts
  server/controller/cycleData/persistNodeValue/validateNode/validateNode.ts
  server/controller/cycleData/persistNodeValue/validateNodeUpdates/index.ts
  server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNode.ts
  server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  server/repository/assessment/row/getOne.ts
  test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
  test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
Labels: enhancement

#1378 nullcheck odp
  server/controller/cycleData/getTableData.ts
Labels: bug

#1379 Dashboard: Calculate country values for CarbonGrowingStock table
  client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  meta/assessment/table.ts
Labels: bug, enhancement, refactor

#1380 Use Numbers for calculations in Dashboard
  client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
Labels: bug, enhancement, refactor

#1382 Meta/validate all nodes
  server/controller/cycleData/persistNodeValue/evalExpression/evalExpression.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorOtherLandWithTreeCoverTotal.ts
  server/controller/cycleData/persistNodeValue/index.ts
  server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNode.ts
  server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  test/dataMigration/postDataMigration.ts
  test/dataMigration/steps/validateNodes/validateNodes.ts
Labels: enhancement

#1390 Minor fixes to dashboard
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  meta/assessment/table.ts
Labels: bug

#1393 DataDownload: Initial commit
  client/components/Navigation/NavigationDesktop/NavigationDesktop.tsx
  client/pages/Assessment/Assessment.tsx
  client/pages/AssessmentDataDownload/dataDownload.scss
  client/pages/AssessmentDataDownload/index.tsx
  client/pages/AssessmentDataDownload/resources.ts
  common/api/endpoint/ApiEndPoint.ts
  server/api/file/getDataDownloadFile.ts
  server/api/file/index.ts
Labels: enhancement, refactor

#1395 Handle NaN string value in table
  client/pages/Dashboard/components/Table/Table.tsx
Labels: bug

#1396 Add validatorForestAreaComparedTo2015
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts
  server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorForestAreaComparedTo2015.ts
  test/dataMigration/postDataMigration.ts
  test/dataMigration/steps/validateNodes/validateNodes.ts
  tools/dataMigration/fraSpecs.ts
  tools/dataMigration/generateMetaCache/index.ts
  webapp/sectionSpec/fra/extentOfForest/extentOfForestValidatorState.ts
Labels: enhancement

#1399 Fix rendering tables with no data
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/pages/AssessmentSection/DataTable/utils/index.ts
  client/store/pages/assessmentSection/hooks/index.ts
Labels: bug

#1400 Country Message Board
  client/pages/AssessmentHome/AssessmentHome.scss
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/CountryMessageBoard.scss
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/CountryMessageBoard.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoard.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoardUsers.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/index.ts
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
Labels: enhancement, refactor

#1403 Functionality for message board
  client/components/MessageCenter/Topic/Topic.tsx
  client/pages/AssessmentHome/AssessmentHome.tsx
  client/pages/AssessmentHome/FraHome/Collaborators/Collaborators.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/CountryMessageBoard.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoard.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoardUsers.tsx
  client/pages/AssessmentHome/FraHome/CountrySelector/CountrySelector.tsx
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/SelectedCountries/SelectedCountries.tsx
  client/store/ui/messageCenter/actions/openTopic.ts
  meta/messageCenter/topics.ts
Labels: enhancement

#1381 react router v6
  client/clientRoutes.ts
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/components/CountrySelect/CountrySelect.tsx
  client/components/CountrySelect/LinkLanding/LinkLanding.tsx
  client/components/Header/UserLinks/LinksFRA/LinksFRA.tsx
  client/components/LinkGeo/LinkGeo.tsx
  client/components/LinkHome/LinkHome.tsx
  client/components/Navigation/NavAssessment/Header/Header.tsx
  client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx
  client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  client/components/Navigation/NavigationDesktop/NavigationDesktop.tsx
  client/hooks/useCountryIso.ts
  client/hooks/useIsPath.ts
  client/pages/Assessment/Assessment.tsx
  client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  client/pages/AssessmentHome/FraHome/ButtonDownloadDashboard/ButtonDownloadDashboard.tsx
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/pages/AssessmentSection/SectionHeader/ExtentOfForest/ExtentOfForest.tsx
  client/pages/DataExport/ColumnSelect/ColumnSelect.tsx
  client/pages/DataExport/CountrySelect/CountrySelect.tsx
  client/pages/DataExport/DataExport.tsx
  client/pages/DataExport/ResultsTable/ResultsTable.tsx
  client/pages/DataExport/ResultsTable/Title/Title.tsx
  client/pages/DataExport/VariableSelect/VariableSelect.tsx
  client/pages/Landing/Introduction/AreaSelector/SelectMobile/SelectMobile.tsx
  client/pages/Login/Invitation/Invitation.tsx
  client/pages/Login/Login.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/ResetPassword/ResetPassword.tsx
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/OriginalDataPoint/components/ButtonBar/ButtonBar.tsx
  client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
  client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/login/actions/changePassword.ts
  client/store/login/actions/createResetPassword.ts
  client/store/login/actions/localLogin.ts
  client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
  package.json
  webapp/pages/Admin/Admin.tsx
  webapp/pages/AssessmentHome/FraHome/FraHome.tsx
  yarn.lock
Labels: enhancement
