Repository openforis/fra-platform, pull requests merged in 2022-05, with the labels that each got.

#1297 Initial commit for Estimation engine
  package.json
  server/service/estimates/estimationEngine.test.ts
  server/service/estimates/estimationEngine.ts
  server/service/estimates/index.ts
  test/deprecated_unit/assessmentRoleAllowanceTest.ts
  test/deprecated_unit/assessmentTest.ts
  test/deprecated_unit/bigNumberTest.ts
  test/deprecated_unit/estimationEngineTest.ts
  test/deprecated_unit/numberInputTest.ts
  test/deprecated_unit/odpPasteTest.ts
  test/deprecated_unit/originalDataPointTest.ts
  test/deprecated_unit/package.json
  test/deprecated_unit/relativeDateTest.ts
  test/deprecated_unit/tableMappingTest.ts
  test/deprecated_unit/tableTest.ts
  test/deprecated_unit/validateOriginalDataPointTest.ts
Labels: enhancement, refactor

#1302 fix odp national class editing
  client/store/pages/originalDataPoint/actions/pasteNationalClass.ts
  client/store/pages/originalDataPoint/actions/updateNationalClass.ts
Labels: bug

#1307 fix ODP calculated node values
  server/repository/assessment/assessment/getCreateSchemaDDL.ts
  server/repository/assessmentCycle/cycle/create.ts
  server/repository/assessmentCycle/data/getOriginalDataPointData.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/migrateOdps.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
Labels: bug

#1308 Estimation engine/UI
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/FieldsOption.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/index.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.scss
  client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/field.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/index.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/method.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
Labels: refactor

#1310 add columnNames to table.props / refactor postDataMigration
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/store/pages/assessmentSection/hooks/index.ts
  meta/assessment/cols.ts
  meta/assessment/table.ts
  test/dataMigration/postDataMigration.ts
  test/dataMigration/steps/deleteWrongCalculatedNodes.ts
  test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
  test/dataMigration/steps/updateCalculatedNodes/getCertifiedAreaValues.ts
  test/dataMigration/steps/updateCalculatedNodes/getTotalLandAreaValues.ts
  test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  test/dataMigration/types.ts
  tools/dataMigration/migrateData/_getNodeInserts.ts
  tools/dataMigration/migrateData/_getNodeInsertsDegradedForest.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/getTable.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: enhancement

#1313 migrate climatic domain table metadata and data
  server/controller/cycleData/getTableData.ts
  test/dataMigration/steps/deleteWrongCalculatedNodes.ts
  test/dataMigration/steps/updateCalculatedNodes/getClimaticDomainValues.ts
  test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateClimaticDomain.ts
Labels: enhancement

#1318 update table columnNames type with Record indexed by cycle uuid
  meta/assessment/index.ts
  meta/assessment/table.ts
  server/repository/assessment/table/getOne.ts
  test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
  tools/dataMigration/migrateData/_getNodeInserts.ts
  tools/dataMigration/migrateData/_getNodeInsertsDegradedForest.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/getTable.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateClimaticDomain.ts
Labels: enhancement

#1312 Estimation engine/api
  client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  client/pages/AssessmentSection/DataTable/utils/index.ts
  client/store/pages/assessmentSection/actions/postEstimate.ts
  client/store/pages/assessmentSection/slice.ts
  common/api/endpoint/ApiEndPoint.ts
  server/api/assessment/index.ts
  server/api/assessment/postEstimation.ts
  server/controller/cycleData/index.ts
  server/controller/cycleData/persistNodeValues.ts
  server/repository/assessmentCycle/data/clearTable.ts
  server/repository/assessmentCycle/data/index.ts
  server/service/estimates/estimationEngine.test.ts
  server/service/estimates/estimationEngine.ts
Labels: enhancement, refactor

#1325 Estimation engine/api clear table
  client/pages/AssessmentSection/DataTable/Chart/chart.ts
  client/pages/AssessmentSection/DataTable/Chart/components/xAxis.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  meta/assessment/activityLog.ts
  server/api/assessment/postEstimation.ts
  server/controller/cycleData/deleteNodeValues.ts
  server/controller/cycleData/index.ts
  server/repository/assessmentCycle/data/clearTable.ts
  server/repository/assessmentCycle/data/deleteNodeValues.ts
  server/repository/assessmentCycle/data/index.ts
Labels: enhancement, refactor

#1300 Meta/estimation engine
  client/pages/AssessmentSection/DataTable/Chart/chart.ts
  client/pages/AssessmentSection/DataTable/Chart/components/xAxis.tsx
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/FieldsOption.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/index.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.scss
  client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/field.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/index.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/method.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  client/pages/AssessmentSection/DataTable/utils/index.ts
  client/store/pages/assessmentSection/actions/postEstimate.ts
  client/store/pages/assessmentSection/slice.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/activityLog.ts
  package.json
  server/api/assessment/index.ts
  server/api/assessment/postEstimation.ts
  server/controller/cycleData/deleteNodeValues.ts
  server/controller/cycleData/index.ts
  server/controller/cycleData/persistNodeValues.ts
  server/repository/assessmentCycle/data/deleteNodeValues.ts
  server/repository/assessmentCycle/data/index.ts
  server/service/estimates/estimationEngine.test.ts
  server/service/estimates/estimationEngine.ts
  server/service/estimates/index.ts
  test/deprecated_unit/assessmentRoleAllowanceTest.ts
  test/deprecated_unit/assessmentTest.ts
  test/deprecated_unit/bigNumberTest.ts
  test/deprecated_unit/estimationEngineTest.ts
  test/deprecated_unit/numberInputTest.ts
  test/deprecated_unit/odpPasteTest.ts
  test/deprecated_unit/originalDataPointTest.ts
  test/deprecated_unit/package.json
  test/deprecated_unit/relativeDateTest.ts
  test/deprecated_unit/tableMappingTest.ts
  test/deprecated_unit/tableTest.ts
  test/deprecated_unit/validateOriginalDataPointTest.ts
  test/unit/estimationEngineTest.ts
Labels: enhancement, refactor

#1331 migrate data tables and odp review
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Calculated/Calculated.tsx
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx
  server/api/messageCenter/resolveTopic.ts
  server/db/migration/migrations/20220517080843-move-issue-tables-to-legacy.js
  server/db/migration/migrations/sqls/20220517080843-move-issue-tables-to-legacy-down.sql
  server/db/migration/migrations/sqls/20220517080843-move-issue-tables-to-legacy-up.sql
  server/repository/assessmentCycle/messageTopic/getOneOrNone.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateReview/getIssuesLegacy.ts
  tools/dataMigration/migrateReview/getOdpTopics.ts
  tools/dataMigration/migrateReview/getTableRows.ts
  tools/dataMigration/migrateReview/getTableTopics.ts
  tools/dataMigration/migrateReview/index.ts
  tools/dataMigration/migrateReview/messageTopicRow.ts
  tools/dataMigration/migrateReview/migrateReview.ts
Labels: enhancement

#1332 SectionPage: scroll to top when navigating to new page
  client/pages/Assessment/Assessment.tsx
  client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  client/pages/Assessment/SectionWrapper/index.ts
  client/pages/AssessmentSection/DataTable/Chart/chartWrapper.tsx
  client/pages/PageRoutes/useTheme.ts
  client/utils/dom.ts
Labels: enhancement

#1334 fix table data rows/cols style
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/useClassName.ts
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  meta/assessment/cols.ts
  tools/dataMigration/fraSpecs.ts
Labels: enhancement

#1339 Fix National Classes, GenerateValues, random crash
  client/pages/AssessmentSection/DataTable/Chart/components/dataPath.tsx
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx
  client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
Labels: bug

#1342 Fix odp table headers
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/pages/AssessmentSection/DataTable/Table/CellOdpHeader/CellOdpHeader.tsx
  client/pages/AssessmentSection/DataTable/Table/CellOdpHeader/index.ts
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/pages/AssessmentSection/DataTable/Table/parseTable.ts
  server/repository/assessment/assessment/getCreateSchemaDDL.ts
Labels: bug

#1343 Country Select with assessment information and CSV download
  client/basePaths.ts
  client/components/CountrySelect/CountryList/CountryList.tsx
  client/components/CountrySelect/CountryList/CountryListDownload/CountryListDownload.tsx
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/components/CountrySelect/CountryList/countryList.scss
  client/components/CountrySelect/CountryList/hooks/useUserCountryISOs.tsx
  client/components/CountrySelect/CountrySelect.tsx
  client/components/CountrySelect/utils/checkMatch.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  meta/area/areas.ts
  meta/area/country.ts
  meta/area/region.ts
  server/api/init/init.ts
  server/repository/assessmentCycle/country/getMany.ts
Labels: enhancement

#1346 add home tabbar navigation
  client/basePaths.ts
  client/components/MessageCenter/Topic/Message/Message.scss
  client/pages/AssessmentHome/AssessmentHome.scss
  client/pages/AssessmentHome/AssessmentHome.tsx
  client/pages/AssessmentHome/FraHome/ButtonDownloadStatisticalFactsheets/ButtonDownloadStatisticalFactsheets.scss
  client/pages/AssessmentHome/FraHome/ButtonDownloadStatisticalFactsheets/ButtonDownloadStatisticalFactsheets.tsx
  client/pages/AssessmentHome/FraHome/ButtonDownloadStatisticalFactsheets/index.ts
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/fraHome.scss
  client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
  meta/area/areas.ts
  meta/area/regionCode.ts
  meta/user/users.ts
Labels: enhancement

#1349 Initial commit for Dashboard
  client/components/Chart/Chart.tsx
  client/components/Chart/index.ts
  client/pages/AssessmentHome/FraHome/FraHome.tsx
  client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
  client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  client/pages/Dashboard/CarbonGrowingStock/index.ts
  client/pages/Dashboard/Dashboard.scss
  client/pages/Dashboard/Dashboard.tsx
  client/pages/Dashboard/ForestArea/ForestArea.tsx
  client/pages/Dashboard/ForestArea/index.ts
  client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
  client/pages/Dashboard/ForestAreaPercent/index.ts
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx
  client/pages/Dashboard/ForestAreaWithinProtectedAreas/index.ts
  client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
  client/pages/Dashboard/ForestOwnership/index.ts
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/index.ts
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/index.ts
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
  client/pages/Dashboard/PrimaryForest/index.ts
  client/pages/Dashboard/components/Table/Table.tsx
  client/pages/Dashboard/components/Table/index.ts
  client/pages/Dashboard/hooks/useDashboardData.ts
  client/pages/Dashboard/index.ts
  client/pages/Dashboard/utils/numberUtils.ts
  client/pages/Dashboard/utils/preferences.ts
  client/pages/Dashboard/utils/propUtils.ts
  i18n/resources/ar/statisticalFactsheets.js
  i18n/resources/en/statisticalFactsheets.js
  i18n/resources/es/statisticalFactsheets.js
  i18n/resources/fr/statisticalFactsheets.js
  i18n/resources/ru/statisticalFactsheets.js
  i18n/resources/zh/statisticalFactsheets.js
Labels: bug, enhancement
