Repository openforis/fra-platform, pull requests merged in 2022-12, with the labels that each got.

#1784 hook: useInitApp
  src/client/components/CountrySelect/CountrySelect.tsx
  src/client/pages/Assessment/Assessment.tsx
  src/client/pages/Landing/Landing.tsx
  src/client/pages/PageRoutes/PageRoutes.tsx
  src/client/pages/User/User.tsx
  src/client/store/assessment/hooks/index.ts
  src/client/store/assessment/hooks/useSyncAssessmentPage.ts
  src/client/store/assessment/index.ts
Labels: bug, enhancement

#1790 Fix naturally regenerating forest dashboard
  src/client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
Labels: bug

#1791 Rename token
  src/meta/auth/index.ts
  src/server/api/auth/login.ts
  src/server/api/auth/postLogout.ts
  src/server/api/auth/strategy/jwt.ts
  src/server/api/auth/utils/setAuthToken.ts
Labels: bug

#1779 Handle Country Selector
  src/client/components/CountrySelect/CountryList/CountryList.tsx
  src/client/hooks/index.ts
  src/client/hooks/useIsPath.ts
  src/client/pages/AssessmentHome/AssessmentHome.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.scss
  src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/index.ts
Labels: enhancement

#1792 ATLANTIS_ALLOWED: Filter countries and regions
  .env.template
  src/client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  src/server/repository/assessmentCycle/country/getMany.ts
  src/server/repository/assessmentCycle/region/getRegionGroups.ts
  src/server/utils/processEnv.ts
Labels: enhancement

#1796 fix roles
  src/client/components/CountrySelect/CountryList/CountryList.tsx
  src/client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  src/client/components/CountrySelect/CountryList/hooks/useUserCountryISOs.tsx
  src/client/components/CountrySelect/CountrySelect.tsx
  src/client/components/EditUserForm/EditUserForm.tsx
  src/client/components/InviteUserForm/InviteUserForm.tsx
  src/client/components/MessageCenter/Topic/Topic.tsx
  src/client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  src/client/components/UserList/CollaboratorListElement/CollaboratorListElement.tsx
  src/client/components/UserList/UserInvitationInfo/UserInvitationInfo.tsx
  src/client/components/UserList/UserListButtonExport/UserListButtonExport.tsx
  src/client/components/UserList/UserRoleField/UserRoleField.tsx
  src/client/pages/AssessmentHome/FraHome/Collaborators/Collaborators.tsx
  src/client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoardUsers.tsx
  src/client/pages/AssessmentHome/FraHome/FraHome.tsx
  src/client/pages/AssessmentHome/FraHome/Links/Links.tsx
  src/client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
  src/client/pages/AssessmentPrint/FraPrint/ContactPersons/ContactPersons.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  src/client/pages/User/User.tsx
  src/client/store/assessment/hooks/useCycle.ts
  src/client/store/ui/userManagement/actions/inviteUser.ts
  src/client/store/ui/userManagement/actions/updateUser.ts
  src/client/store/ui/userManagement/slice.ts
  src/client/store/user/hooks/index.ts
  src/meta/assessment/assessments.test.ts
  src/meta/assessment/assessments.ts
  src/meta/user/authorizer.ts
  src/meta/user/userRole.ts
  src/meta/user/users.test.ts
  src/meta/user/users.ts
  src/server/middleware/auth.ts
  src/server/repository/public/user/getOne.ts
  src/test/integration/user/userInvite.ts
Labels: bug, enhancement

#1780 Pan european/section keys
  tools/dataMigration/migrateMetadata/getSection.ts
Labels: bug

#1813 Meta/invitation gmail fix
  src/client/components/CountrySelect/CountrySelect.tsx
  src/client/components/InviteUserForm/InviteUserForm.tsx
  src/client/components/UserList/CollaboratorListElement/CollaboratorListElement.tsx
  src/client/store/ui/userManagement/actions/removeInvitation.ts
  src/server/controller/user/invite.ts
  src/server/repository/public/user/create.ts
  src/server/repository/public/user/getOne.ts
Labels: bug, enhancement

#1814 Feature/section controller
  src/meta/assessment/activityLog.ts
  src/server/controller/section/create.ts
  src/server/controller/section/index.ts
  src/server/controller/section/remove.ts
  src/server/controller/section/update.ts
  src/server/repository/assessment/section/create.ts
  src/server/repository/assessment/section/index.ts
  src/server/repository/assessment/section/remove.ts
  src/server/repository/assessment/section/update.ts
  src/test/integration/integration.test.ts
  src/test/integration/mock/section.ts
  src/test/integration/section/createSection.ts
  src/test/integration/section/updateSection.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: enhancement

#1816 Error message if trying to link already linked google account
  src/i18n/resources/en/login.js
  src/server/api/auth/strategy/google.ts
Labels: enhancement

#1834 Severe bug has been fixed
  src/server/repository/public/user/getOne.ts
Labels: bug

#1836 Meta/hotfix printview
  src/client/pages/AssessmentPrint/AssessmentPrint.tsx
Labels: bug

#1838 Fix userguide link
  src/client/components/Footer/Footer.tsx
  src/meta/api/endpoint/ApiEndPoint.ts
  src/server/api/file/getUserGuide.ts
  src/server/api/file/index.ts
Labels: bug

#1844 Add 'sectionName: extentOfForest' for ODP write'
  src/client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
  src/client/store/pages/originalDataPoint/actions/deleteOriginalDataPoint.ts
  src/client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts
Labels: bug

#1856 Feature/table controller
  src/meta/assessment/activityLog.ts
  src/server/controller/metadata/createTable.ts
  src/server/controller/metadata/index.ts
  src/server/controller/metadata/removeTable.ts
  src/server/controller/metadata/updateTable.ts
  src/server/repository/assessment/table/create.ts
  src/server/repository/assessment/table/getOne.ts
  src/server/repository/assessment/table/index.ts
  src/server/repository/assessment/table/remove.ts
  src/server/repository/assessment/table/update.ts
  src/test/integration/integration.test.ts
  src/test/integration/mock/table.ts
  src/test/integration/table/createTable.ts
  src/test/integration/table/removeTable.ts
  src/test/integration/table/updateTable.ts
Labels: enhancement

#1870 Original data point: Copy previous national classes
  src/client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  src/client/pages/OriginalDataPoint/components/NationalClasses/NationalClasses.tsx
  src/client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  src/client/store/pages/originalDataPoint/actions/copyPreviousNationalClasses.ts
  src/client/store/pages/originalDataPoint/actions/getOriginalDataPointReservedYears.ts
  src/client/store/pages/originalDataPoint/hooks/index.ts
  src/client/store/pages/originalDataPoint/index.ts
  src/client/store/pages/originalDataPoint/slice.ts
  src/client/store/pages/originalDataPoint/stateType.ts
  src/meta/assessment/originalDataPoint/odps/getPreviousODPYear.ts
  src/meta/assessment/originalDataPoint/odps/index.ts
  tools/dataMigration/migrateData/migrateOdps.ts
Labels: bug, enhancement, refactor

#1891 GenerateValues: Add method validity check
  src/client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx
  src/client/pages/AssessmentSection/DataTable/GenerateValues/method.ts
  src/client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValues.ts
Labels: bug, enhancement

#1892 Fix ODP Edit Data sources -> Methods used
  src/client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx
Labels: bug

#1882 Add tab bar with no links
  src/client/pages/AssessmentHome/PanEuropeanHome/Description/Description.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/Description/index.ts
  src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/hooks/useSections.tsx
Labels: enhancement

#1896 Fix Original Data Point creation: Display ODPs without National Classes in section 1a and 1b
  src/client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
  src/client/store/pages/originalDataPoint/actions/setOriginalDataPointUpdating.ts
  src/client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts
  src/client/store/pages/originalDataPoint/slice.ts
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
Labels: bug

#1905 PanEuropean: Header -> Enable Reserved Area / user link
  src/client/components/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  src/client/components/Header/UserLinks/UserLinks.tsx
Labels: enhancement

#1906 Fix ODP table (1a, 1b) rendering
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/client/pages/AssessmentSection/DataTable/Table/TableBody/TableBody.tsx
  src/client/pages/AssessmentSection/DataTable/Table/TableBody/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/TableHead/TableHead.tsx
  src/client/pages/AssessmentSection/DataTable/Table/TableHead/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/utils/parseTable.ts
Labels: bug

#1918 ODP Edit: Add field validations
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsNaturallyRegeneratingRow.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx
  src/client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx
  src/client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  src/client/pages/OriginalDataPoint/hooks/index.ts
  src/client/pages/OriginalDataPoint/hooks/useNationalClassValidation.ts
  src/meta/assessment/originalDataPoint/odps/index.ts
  src/meta/assessment/originalDataPoint/odps/validateODP.ts
Labels: enhancement

#1922 PanEuropean: Manage collaborators -> user list empty
  src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.tsx
Labels: bug

#1921 Metadata 2025 updates
  .src.legacy/core/assessment/fra.ts
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Descriptions/Descriptions.tsx
  src/i18n/resources/en.js
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/degradedForest.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateFRATablesData.ts
Labels: enhancement

#1929 Restore section 6 metadata for 2025
  .src.legacy/core/assessment/fra.ts
  src/i18n/resources/en/fra.js
  src/test/dataMigration/steps/migratePrimaryForestData.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: enhancement

#1928 Show version number and release date
  src/client/components/Footer/Footer.tsx
  src/client/components/Footer/footer.scss
  src/client/style/_partials/_config.scss
  src/i18n/resources/en.js
  webpack.config.babel.js
Labels: enhancement

#1935 Wrap middlewares in try catch
  src/server/middleware/auth.ts
  src/server/middleware/tryCatch.ts
Labels: bug, enhancement

#1932 Update labels for ODP Edit
  src/client/pages/AssessmentPrint/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/OriginalDataPoint/components/NationalClasses/NationalClasses.tsx
  src/client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
  src/i18n/resources/ar.js
  src/i18n/resources/en.js
  src/i18n/resources/es.js
  src/i18n/resources/fr.js
  src/i18n/resources/ru.js
  src/i18n/resources/zh.js
Labels: enhancement

#1937 Section 8: Add missing years for SDG Sub Indicator 5 for 2025
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1939 Update land area for 2025
  src/test/dataMigration/steps/updateCalculatedNodes/getTotalLandAreaValues.ts
  src/test/dataMigration/steps/updateCalculatedNodes/landArea.js
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1940 PanEuropean: 2025 metadata
  src/test/sectionSpec/PanEuropeanSpecs.ts
Labels: enhancement
