Repository openforis/fra-platform, pull requests merged in 2022-08, with the labels that each got.

#1426 Fix xAxis issue
  client/pages/Dashboard/ForestArea/ForestArea.tsx
  client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
Labels: bug

#1427 Commentable Description API
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/commentableDescription.ts
  server/api/assessment/getCommentableDescription.ts
  server/api/assessment/index.ts
  server/controller/cycleData/index.ts
  server/repository/assessmentCycle/descriptions/getOneOrNone.ts
  server/repository/assessmentCycle/descriptions/index.ts
Labels: enhancement, refactor

#1431 Fix Sections fetch on cycle change
  client/components/Navigation/Navigation.tsx
  client/pages/Assessment/Assessment.tsx
  package.json
  yarn.lock
Labels: bug

#1440 originalDataPoints: Comments
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/OriginalDataPoint/components/Comments/CommentsEditor.tsx
Labels: enhancement, refactor

#1444 Add conditional descriptions rendering
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/AssessmentSection/DataTable/Table/parseTable.ts
  client/pages/AssessmentSection/Descriptions/Descriptions.tsx
  client/pages/AssessmentSection/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx
  client/store/pages/assessmentSection/hooks/index.ts
  client/store/pages/assessmentSection/index.ts
  meta/assessment/description.ts
  tools/dataMigration/migrateMetadata/getSection.ts
Labels: enhancement

#1448 Meta/tablesections group fetch
  client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  client/pages/AssessmentPrint/FraPrint/FraPrint.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/store/pages/assessmentSection/actions/getTableSections.ts
  client/store/pages/assessmentSection/actions/setTableSections.ts
  client/store/pages/assessmentSection/slice.ts
  client/store/pages/assessmentSection/stateType.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/tableSection.ts
  server/api/assessment/getSectionMetadata.ts
  server/api/assessment/index.ts
  server/repository/assessment/assessment/getSectionMetaData.ts
Labels: enhancement

#1449 Meta/print odp view
  client/pages/AssessmentPrint/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx
  client/pages/AssessmentPrint/OriginalDataPointsPrint/index.ts
  client/pages/AssessmentPrint/OriginalDataPointsPrint/useOriginalDataPoints.ts
  client/pages/AssessmentSection/Title/ExtentOfForest/ExtentOfForest.tsx
  client/pages/AssessmentSection/Title/ForestCharacteristics/ForestCharacteristics.tsx
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClasses.tsx
  client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
  common/api/endpoint/ApiEndPoint.ts
  server/api/assessment/getOriginalDataPoints.ts
  server/api/assessment/index.ts
  server/controller/assessment/index.ts
  server/repository/assessmentCycle/originalDataPoint/getMany.ts
  server/repository/assessmentCycle/originalDataPoint/index.ts
Labels: enhancement, refactor

#1450 Meta/print contact persons
  client/components/Navigation/NavAssessment/Header/Header.tsx
  client/hooks/useIsPath.ts
  client/pages/AssessmentPrint/FraPrint/ContactPersons/ContactPersons.tsx
  client/pages/AssessmentPrint/FraPrint/FraPrint.tsx
  client/pages/AssessmentPrint/FraPrint/TableOfContent/TableOfContent.tsx
  i18n/resources/ar.js
  i18n/resources/ar/print.js
  i18n/resources/en.js
  i18n/resources/en/print.js
  i18n/resources/es.js
  i18n/resources/es/print.js
  i18n/resources/fr.js
  i18n/resources/fr/print.js
  i18n/resources/ru.js
  i18n/resources/ru/print.js
  i18n/resources/zh.js
  i18n/resources/zh/print.js
  server/api/user/index.ts
Labels: enhancement, refactor

#1455 Add routing for print/tables
  client/pages/PageRoutes/PageRoutes.tsx
Labels: bug

#1453 Dashboard/PrimaryForest: null check values
  client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
Labels: bug

#1459 Refactor/controllers
  server/api/assessment/createOriginalDataPoint.ts
  server/api/assessment/deleteOriginalDataPoint.ts
  server/api/assessment/getOdp.ts
  server/api/assessment/getOriginalDataPoints.ts
  server/api/assessment/getReservedYears.ts
  server/api/assessment/postCountry.ts
  server/api/assessment/updateOriginalDataPoint.ts
  server/api/init/init.ts
  server/controller/area/index.ts
  server/controller/area/updateCountry.ts
  server/controller/assessment/getRegionGroups.ts
  server/controller/assessment/index.ts
  server/controller/cycleData/createOriginalDataPoint.ts
  server/controller/cycleData/getOriginalDataPoint.ts
  server/controller/cycleData/getOriginalDataPointReservedYears.ts
  server/controller/cycleData/index.ts
  server/controller/cycleData/removeOriginalDataPoint.ts
  server/controller/cycleData/updateOriginalDataPoint.ts
  server/middleware/auth.ts
  server/repository/assessment/assessment/index.ts
  server/repository/assessmentCycle/country/getOne.ts
  server/repository/assessmentCycle/country/index.ts
  server/repository/assessmentCycle/country/update.ts
  server/repository/assessmentCycle/region/getRegionGroups.ts
  server/repository/assessmentCycle/region/index.ts
  test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  test/integration/assessment/originalDataPoint.ts
Labels: refactor

#1461 Api refactor setup
  server/api/assessment/createOriginalDataPoint.ts
  server/api/assessment/deleteOriginalDataPoint.ts
  server/api/assessment/getDescription.ts
  server/api/assessment/getOdp.ts
  server/api/assessment/getOriginalDataPointData.ts
  server/api/assessment/getOriginalDataPoints.ts
  server/api/assessment/getReservedYears.ts
  server/api/assessment/getReviewStatus.ts
  server/api/assessment/getReviewSummary.ts
  server/api/assessment/getSectionMetadata.ts
  server/api/assessment/getSections.ts
  server/api/assessment/getTableData.ts
  server/api/assessment/persistNodeValues.ts
  server/api/assessment/postCountry.ts
  server/api/assessment/postEstimation.ts
  server/api/assessment/updateOriginalDataPoint.ts
  server/api/assessment/upsertDescription.ts
  server/api/init/init.ts
  server/api/messageCenter/addMessage.ts
  server/api/messageCenter/getTopic.ts
  server/api/messageCenter/getUnreadMessages.ts
  server/api/messageCenter/markMessageDeleted.ts
  server/api/messageCenter/resolveTopic.ts
  server/api/user/getMany.ts
  server/api/user/invite.ts
  server/controller/assessment/getOne.ts
  server/controller/assessment/getSections.ts
  server/controller/cycleData/getOriginalDataPoint.ts
  server/controller/cycleData/persistNodeValue/persistNodeValue.test.ts__
  server/middleware/auth.ts
  server/repository/assessment/assessment/read.ts
  server/utils/request.ts
  test/dataMigration/postDataMigration.ts
  test/integration/assessment/originalDataPoint.ts
  test/integration/assessment/removeAssessment.ts
  test/integration/messageCenter/messageCenter.ts
  test/integration/settings/defaultAssessment.ts
  test/integration/user/userInvite.ts
Labels: enhancement, refactor

#1462 Refactor cycleData/table/nodes endpoint
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  client/store/pages/assessmentSection/actions/updateNodeValues.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/api/cycleData/nodes/index.ts
  meta/api/request/cycleData/table.ts
  meta/api/request/index.ts
  server/api/api.ts
  server/api/assessment/getOriginalDataPoints.ts
  server/api/assessment/getReservedYears.ts
  server/api/assessment/getReviewStatus.ts
  server/api/assessment/getSectionMetadata.ts
  server/api/assessment/index.ts
  server/api/cycleData/index.ts
  server/api/cycleData/table/persistNodeValues.ts
  server/api/user/getMany.ts
  server/middleware/auth.ts
Labels: refactor

#1463 Initial commit for refactor api
  client/pages/AssessmentHome/FraHome/ButtonDownloadDashboard/ButtonDownloadDashboard.tsx
  client/pages/Login/Invitation/Invitation.tsx
  client/store/assessment/actions/initApp.ts
  client/store/assessment/actions/updateCountry.ts
  client/store/login/actions/createResetPassword.ts
  client/store/login/actions/localLogin.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/api/request/auth/login.ts
  meta/api/request/index.ts
  meta/api/request/init/init.ts
  server/api/api.ts
  server/api/area/index.ts
  server/api/area/postCountry.ts
  server/api/assessment/index.ts
  server/api/auth/googleStrategyVerifyCallback.ts
  server/api/auth/index.ts
  server/api/auth/localStrategyVerifyCallback.ts
  server/api/auth/login.ts
  server/api/definitions/index.ts
  server/api/file/index.ts
  server/api/init/index.ts
  server/api/init/init.ts
Labels: bug

#1464 Refactor cycleData/table endpoint
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  client/pages/Dashboard/hooks/useDashboardData.ts
  client/pages/DataExport/ResultsTable/useFetchResults.ts
  client/store/pages/assessmentSection/actions/getTableData.ts
  client/store/pages/assessmentSection/actions/postEstimate.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/api/request/cycleData/table.ts
  meta/api/request/index.ts
  server/api/assessment/index.ts
  server/api/cycleData/index.ts
  server/api/cycleData/table/getTableData.ts
  server/api/cycleData/table/postEstimation.ts
  server/middleware/auth.ts
Labels: refactor

#1466 Refactor/api/message center
  client/components/AssessmentSwitch/AssessmentSwitch.tsx
  client/components/Header/Header.tsx
  client/components/Header/UserLinks/UserLinks.tsx
  client/components/Loading/Loading.tsx
  client/components/MessageCenter/Topic/Topic.tsx
  client/components/Navigation/NavAssessment/Header/Header.tsx
  client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  client/components/PopoverControl/PopoverControl.tsx
  client/components/ReviewIndicator/ReviewIndicator.tsx
  client/pages/AssessmentHome/AssessmentHome.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageButton/MessageButton.tsx
  client/pages/AssessmentPrint/AssessmentPrint.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/SectionHeader/SectionHeader.ts
  client/pages/AssessmentSection/Title/Title.tsx
  client/pages/DataExport/VariableSelect/VariableSelect.tsx
  client/pages/DataExport/utils/format.ts
  client/pages/DataExport/utils/labelKeys.ts
  client/pages/Landing/Introduction/AreaSelector/AreaSelector.tsx
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  client/pages/PageRoutes/useTheme.ts
  client/store/ui/messageCenter/actions/markMessageDeleted.ts
  client/store/ui/messageCenter/actions/openTopic.ts
  client/store/ui/messageCenter/actions/postMessage.ts
  client/store/ui/messageCenter/actions/resolveTopic.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/api/request/index.ts
  meta/assessment/assessmentName.ts
  meta/assessment/index.ts
  meta/socket/sockets.ts
  server/api/area/postCountry.ts
  server/api/messageCenter/addMessage.ts
  server/api/messageCenter/getTopic.ts
  server/api/messageCenter/getUnreadMessages.ts
  server/api/messageCenter/index.ts
  server/api/messageCenter/markMessageDeleted.ts
  server/api/messageCenter/resolveTopic.ts
  server/api/messageCenter/sendRequestReviewUpdateEvents.ts
  server/api/user/invite.ts
  server/service/mail/assessmentNotifyUsers.ts
  server/utils/requests.ts
  test/integration/mock/assessment.ts
Labels: refactor

#1468 refactor user endpoint
  client/components/MessageCenter/Topic/Message/Message.tsx
  client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoardUsers.tsx
  client/pages/Dashboard/hooks/useDashboardData.ts
  client/pages/Login/Invitation/Invitation.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/store/login/actions/acceptInvitation.ts
  client/store/login/actions/fetchUserByInvitation.ts
  client/store/userManagement/actions/getUserToEdit.ts
  client/store/userManagement/actions/getUsers.ts
  client/store/userManagement/actions/inviteUser.ts
  client/store/userManagement/actions/removeInvitation.ts
  client/store/userManagement/actions/sendInvitationEmail.ts
  client/store/userManagement/actions/updateUser.ts
  common/api/endpoint/ApiEndPoint.ts
  meta/user/users.ts
  server/api/user/acceptInvitation.ts
  server/api/user/getInvitation.ts
  server/api/user/index.ts
  server/api/user/invite.ts
  server/api/user/removeInvitation.ts
  server/api/user/sendInvitationEmail.ts
  server/api/user/updateUser.ts
Labels: refactor

#1471 Refactor/section section name
  client/basePaths.ts
  client/clientRoutes.ts
  client/components/MessageCenter/Topic/Topic.tsx
  client/components/ReviewIndicator/ReviewIndicator.tsx
  client/hooks/useCountryIso.ts
  client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  client/pages/AssessmentHome/FraHome/ButtonDownloadDashboard/ButtonDownloadDashboard.tsx
  client/pages/AssessmentPrint/OriginalDataPointsPrint/OriginalDataPointsPrint.tsx
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/pages/AssessmentSection/DataTable/Table/Table.tsx
  client/pages/AssessmentSection/Descriptions/AnalysisDescriptions/AnalysisDescriptions.tsx
  client/pages/AssessmentSection/Descriptions/CommentableDescription/CommentableDescription.tsx
  client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  client/pages/AssessmentSection/Descriptions/Descriptions.tsx
  client/pages/AssessmentSection/Descriptions/GeneralComments/GeneralComments.tsx
  client/pages/AssessmentSection/Descriptions/NationalDataDescriptions/NationalDataDescriptions.tsx
  client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx
  client/pages/Dashboard/components/Table/Table.tsx
  client/pages/DataExport/ColumnSelect/ColumnSelect.tsx
  client/pages/DataExport/CountrySelect/CountrySelect.tsx
  client/pages/DataExport/DataExport.tsx
  client/pages/DataExport/ResultsTable/ResultsTable.tsx
  client/pages/DataExport/ResultsTable/Title/Title.tsx
  client/pages/DataExport/ResultsTable/useFetchResults.ts
  client/pages/DataExport/VariableSelect/VariableSelect.tsx
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/OriginalDataPoint/components/ButtonBar/ButtonBar.tsx
  client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
  client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  client/store/assessment/hooks/index.ts
  client/store/pages/dataExport/actionTypes.ts
  client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
  client/store/ui/review/actions/getReviewStatus.ts
  meta/api/request/index.ts
  server/api/cycleData/review/getReviewStatus.ts
  server/api/cycleData/table/persistNodeValues.ts
  server/controller/cycleData/getReviewStatus.ts
  server/middleware/auth.ts
  server/repository/assessmentCycle/messageTopicUser/getReviewStatus.ts
Labels: refactor

#1476 refactor cycleData/originalDataPoint endpoint
  client/pages/AssessmentPrint/OriginalDataPointsPrint/useOriginalDataPoints.ts
  client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  client/store/pages/assessmentSection/actions/getOriginalDataPointData.ts
  client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
  client/store/pages/originalDataPoint/actions/deleteOriginalDataPoint.ts
  client/store/pages/originalDataPoint/actions/getOriginalDataPoint.ts
  client/store/pages/originalDataPoint/actions/updateOriginalDataPoint.ts
  meta/api/endpoint/ApiEndPoint.ts
  server/api/api.ts
  server/api/assessment/index.ts
  server/api/cycleData/index.ts
  server/api/cycleData/originalDataPoint/createOriginalDataPoint.ts
  server/api/cycleData/originalDataPoint/deleteOriginalDataPoint.ts
  server/api/cycleData/originalDataPoint/getOdp.ts
  server/api/cycleData/originalDataPoint/getOriginalDataPointData.ts
  server/api/cycleData/originalDataPoint/getOriginalDataPoints.ts
  server/api/cycleData/originalDataPoint/getReservedYears.ts
  server/api/cycleData/originalDataPoint/updateOriginalDataPoint.ts
  server/controller/cycleData/createOriginalDataPoint.ts
  server/controller/cycleData/getOriginalDataPoint.ts
  server/controller/cycleData/removeOriginalDataPoint.ts
  server/controller/cycleData/updateOriginalDataPoint.ts
  server/repository/assessmentCycle/originalDataPoint/create.ts
  server/repository/assessmentCycle/originalDataPoint/getOne.ts
  server/repository/assessmentCycle/originalDataPoint/remove.ts
  server/repository/assessmentCycle/originalDataPoint/update.ts
  test/integration/assessment/originalDataPoint.ts
Labels: refactor

#1477 RFC: remove references to common
  client/components/CountrySelect/CountryList/CountryList.tsx
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/components/CountrySelect/CountryList/hooks/useUserCountryISOs.tsx
  client/components/ThousandSeparatedDecimalInput/ThousandSeparatedDecimalInput.tsx
  client/pages/AssessmentSection/DataTable/GenerateValues/method.ts
  client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  common/aggregate.ts
  common/numberFormat.ts
  meta/user/userRoles.ts
  meta/user/users.ts
  server/api/auth/localStrategyVerifyCallback.ts
  server/api/auth/postChangePassword.ts
  server/api/auth/postResetPassword.ts
  server/utils/accessControl.ts
  server/utils/index.ts
  server/utils/validEmail.ts
  server/utils/validPassword.ts
Labels: refactor
