Repository openforis/fra-platform, pull requests merged in 2022-11, with the labels that each got.

#1667 Update 1a, 1b on odp change
  src/client/store/pages/assessmentSection/slice.ts
  src/server/controller/cycleData/updateOriginalDataPoint.ts
  src/test/integration/assessment/originalDataPoint.ts
Labels: enhancement

#1670 Meta/2025 meta 3 forest restoration
  .src.legacy/core/assessment/fra.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Select/Select.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Text/Text.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: enhancement

#1678 Metadata 2025: metadata migration section 3c
  .src.legacy/core/assessment/fra.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Number/Number.tsx
  src/i18n/resources/en/fra.js
  src/test/dataMigration/steps/migratePrimaryForestData.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: enhancement

#1679 eslint 8.22.0
  package.json
  src/meta/app.ts
  yarn.lock
Labels: dependencies

#1687 Calculate function and validate functions under Cycle.Uuid
  src/client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  src/meta/assessment/assessment.ts
  src/meta/assessment/col.ts
  src/meta/assessment/cycle.ts
  src/meta/assessment/index.ts
  src/meta/assessment/row.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/context.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/evaluators/member.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNode.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  src/server/repository/assessment/col/getMany.ts
  src/server/repository/assessment/row/getOne.ts
  src/server/repository/assessment/section/getManyMetadata.ts
  src/test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/dataMigration/steps/validateNodes/validateNodes.ts
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/rowSpec.ts
  tools/dataMigration/generateMetaCache/index.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getRow.ts
Labels: enhancement

#1698 fixed wrong import
  src/client/store/ui/userManagement/index.ts
Labels: bug

#1696 Fix double data on chart
  src/client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx
Labels: bug

#1697 Fix DataSource row names
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceRow.tsx
Labels: bug

#1703 Dashboard: Forest Ownership: Fix issue other_unknown
  src/client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx
Labels: bug

#1704 Dashboard: Primary Forest: fix issue primary_forest
  src/client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx
Labels: bug

#1676 Initial commit invalidate token
  src/server/api/auth/login.ts
  src/server/serverInit.ts
  src/server/utils/validateToken.ts
Labels: enhancement

#1707 Metadata 2025: Migrate section 2c/2d
  package.json
  src/i18n/resources/en/fra.js
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/dataMigration/steps/migrateBiomassAndCarbonStockData.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/generateMetaCache/index.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: infrastructure

#1709 Dashboard: Carbon stock: fix table per cycle
  src/client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx
  src/meta/assessment/table.ts
Labels: bug

#1714 Show ODP years in 2025
  src/client/store/pages/assessmentSection/hooks/index.ts
Labels: bug

#1712 Metadata 2025: Final adjustements
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
Labels: infrastructure

#1716 Pan european/migration setup
  package.json
  src/server/db/migration/migrations/20221116105034-pan-european-legacy.js
  src/server/db/migration/migrations/sqls/20221116105034-pan-european-legacy-down.sql
  src/server/db/migration/migrations/sqls/20221116105034-pan-european-legacy-up.sql
  src/test/sectionSpec/PanEuropeanSpecs.ts
  tools/dataMigration/panEuropean.ts
Labels: enhancement

#1718 Metadata 2025: Reset Atlantis data
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/cleanupCountryProps.ts
  src/test/dataMigration/steps/deleteAtlantisData/deleteAtlantisData.ts
Labels: infrastructure

#1685 Feature/ ODP nodes update: calculate and validate dependents nodes
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  src/client/store/pages/assessmentSection/hooks/index.ts
  src/client/store/pages/assessmentSection/slice.ts
  src/client/store/pages/assessmentSection/stateType.ts
  src/meta/assessment/table.ts
  src/server/api/cycleData/originalDataPoint/updateOriginalDataPoint.ts
  src/server/controller/cycleData/getTableData.ts
  src/server/controller/cycleData/persistNodeValue/calculateAndValidateDependentNodes.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
  src/server/controller/cycleData/persistNodeValue/index.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  src/server/controller/cycleData/updateOriginalDataPoint.ts
  src/server/controller/cycleData/updateOriginalDataPointDependentNodes.ts
  src/server/repository/assessment/assessment/createAssessment.ts
  src/server/repository/assessmentCycle/cycle/create.ts
  src/test/integration/assessment/createAssessment.ts
  src/test/integration/assessment/originalDataPoint.ts
Labels: enhancement

#1713 Assessment Controller for Update
  src/meta/assessment/activityLog.ts
  src/meta/assessment/assessment.ts
  src/meta/assessment/index.ts
  src/server/controller/assessment/index.ts
  src/server/controller/assessment/update.ts
  src/server/repository/adapter/assessment.ts
  src/server/repository/adapter/index.ts
  src/server/repository/assessment/assessment/index.ts
  src/server/repository/assessment/assessment/updateAssessment.ts
  src/test/integration/assessment/updateAssessmentDefaultCycle.ts
  src/test/integration/integration.test.ts
Labels: enhancement

#1677 Add express-validation middleware
  package.json
  src/meta/api/request/geo/layer.ts
  src/server/api/geo/getForestAgreementLayer.ts
  src/server/api/geo/getForestLayer.ts
  src/server/api/geo/index.ts
  src/server/controller/geo/assets/getForestAssetData.ts
  src/server/controller/geo/getForestAgreementLayer.ts
  src/server/controller/geo/getForestLayer.ts
  src/server/middleware/validation/geoSchemes.ts
  src/server/middleware/validation/index.ts
  yarn.lock
Labels: enhancement

#1720 Create assessment and cycles
  tools/dataMigration/panEuropean.ts
Labels: enhancement

#1729 fix asynchronous assessment sections fetch
  src/client/pages/Assessment/Assessment.tsx
Labels: bug

#1728 DataTable/Chart: No data placeholder text
  src/client/pages/AssessmentSection/DataTable/Chart/components/noDataPlaceholder.tsx
Labels: bug

#1731 migrate metadata
  src/test/sectionSpec/PanEuropeanSpecs.ts
  tools/dataMigration/panEuropean.ts
Labels: enhancement

#1749 Pan european/migrate data
  tools/dataMigration/migrateAreas.ts
  tools/dataMigration/panEuropean.ts
Labels: enhancement

#1754 Solves bug in migration
  tools/dataMigration/migrateAreas.ts
Labels: bug

#1753 totalLandArea 2025: use 2020 value
  src/test/dataMigration/steps/updateCalculatedNodes/getTotalLandAreaValues.ts
Labels: bug

#1739 Fix non-odp odp-year dependant calculations
  src/meta/assessment/assessmentMetaCaches.ts
  src/meta/assessment/index.ts
  src/server/controller/cycleData/originalDataPointVariables.ts
  src/server/controller/cycleData/persistNodeValue/calculateAndValidateDependentNodes.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateDependantNodes.ts
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
  src/server/controller/cycleData/persistNodeValue/utils/assessmentMetaCaches.ts
  src/server/controller/cycleData/persistNodeValue/utils/isODPCell.ts
  src/server/controller/cycleData/persistNodeValue/validateNodeUpdates/validateNodeUpdates.ts
  src/server/controller/cycleData/updateOriginalDataPointDependentNodes.ts
Labels: bug, enhancement

#1764 Fix panEuropean migrate areas
  tools/dataMigration/migrateAreas.ts
Labels: bug

#1768 Pan european/data migration
  tools/dataMigration/migrateData/_getNodeInserts.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateFRATablesData.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/panEuropean.ts
Labels: enhancement

#1759 Listen separately to Validations change (grouped)
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useListenNodeUpdate.ts
  src/client/pages/AssessmentSection/useListenValidationsUpdate.ts
  src/client/store/pages/assessmentSection/slice.ts
  src/meta/socket/sockets.ts
  src/server/controller/cycleData/persistNodeValue/calculateAndValidateDependentNodes.ts
  src/server/controller/cycleData/persistNodeValue/index.ts
  src/server/controller/cycleData/persistNodeValue/persistNodeValue.test.ts__
  src/server/controller/cycleData/persistNodeValue/persistNodeValue.ts
  src/server/controller/cycleData/updateOriginalDataPointDependentNodes.ts
Labels: bug, enhancement

#1775 Change assessment name to panEuropean
  tools/dataMigration/_DBNames.ts
  tools/dataMigration/migrateAreas.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/panEuropean.ts
Labels: bug

#1777 RFC: Add JWT authentication
  package.json
  src/client/store/axiosMiddleware.ts
  src/client/store/login/actions/localLogin.ts
  src/client/store/store.ts
  src/client/store/user/actions/index.ts
  src/server/api/api.ts
  src/server/api/area/postCountry.ts
  src/server/api/auth/config.ts
  src/server/api/auth/index.ts
  src/server/api/auth/login.ts
  src/server/api/auth/strategy/google.ts
  src/server/api/auth/strategy/jwt.ts
  src/server/api/auth/strategy/local.ts
  src/server/api/auth/utils/setAuthToken.ts
  src/server/api/cycleData/descriptions/upsertDescription.ts
  src/server/api/cycleData/originalDataPoint/createOriginalDataPoint.ts
  src/server/api/cycleData/originalDataPoint/deleteOriginalDataPoint.ts
  src/server/api/cycleData/originalDataPoint/updateOriginalDataPoint.ts
  src/server/api/cycleData/review/getReviewStatus.ts
  src/server/api/cycleData/review/getReviewSummary.ts
  src/server/api/cycleData/table/persistNodeValues.ts
  src/server/api/cycleData/table/postEstimation.ts
  src/server/api/file/createAssessmentFile.ts
  src/server/api/file/removeAssessmentFile.ts
  src/server/api/init/init.ts
  src/server/api/messageCenter/addMessage.ts
  src/server/api/messageCenter/getTopic.ts
  src/server/api/messageCenter/getUnreadMessages.ts
  src/server/api/messageCenter/markMessageDeleted.ts
  src/server/api/messageCenter/resolveTopic.ts
  src/server/api/user/invite.ts
  src/server/api/user/removeInvitation.ts
  src/server/api/user/updateUser.ts
  src/server/api/user/updateUserRoles.ts
  src/server/middleware/auth.ts
  src/server/serverInit.ts
  src/server/utils/requests.ts
  yarn.lock
Labels: enhancement
