Repository openforis/fra-platform, pull requests merged in 2022-01, with the labels that each got.

#1088 local login ui [merge last]
  client/pages/Login/Login.tsx
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/login.scss
  client/pages/Login/utils/LoginValidator.tsx
  client/store/assessment/slice.ts
  client/store/login/actions/localLogin.ts
  client/store/login/slice.ts
  client/store/rootReducer.ts
  client/store/user/slice.ts
  i18n/resources/en/login.js
  server/api/init/init.ts
Labels: enhancement, refactor

#1097 Hotfix/odp
  webapp/components/multiSelect.tsx
Labels: bug

#1094 initial commit for country list ui
  client/components/CountrySelect/CountryList/CountryList.tsx
  client/components/CountrySelect/CountryList/CountryListDownload/CountryListDownload.tsx
  client/components/CountrySelect/CountryList/CountryListDownload/countryListDownload.scss
  client/components/CountrySelect/CountryList/CountryListDownload/index.ts
  client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx
  client/components/CountrySelect/CountryList/CountryListRoleSection/index.ts
  client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx
  client/components/CountrySelect/CountryList/CountryListRow/index.ts
  client/components/CountrySelect/utils/checkMatch.ts
  client/store/user/hooks/index.ts
  client/store/user/index.ts
  client/utils/dates.ts
  client/utils/index.ts
  client/utils/urls.ts
  meta/area/areas.ts
  meta/area/index.ts
  meta/user/userRole.ts
Labels: refactor

#1096 API endpoint: /api/assessment/section/:assessmentName/:assessmentCycleName
  _legacy_server/api/assessment/createEmail.ts
  _legacy_server/api/assessment/export.ts
  common/api/endpoint/ApiEndPoint.ts
  server/api/api.ts
  server/api/assessment/getSections.ts
  server/api/assessment/index.ts
  server/controller/assessment/getSections.ts
  server/controller/assessment/index.ts
  server/repository/assessment/index.ts
  server/repository/assessment/readSections.ts
  webapp/pages/Admin/components/DataExportView/dataExportView.tsx
  webapp/store/country/actions/changeAssessmentStatus.ts
Labels: enhancement, refactor

#1101 add getSections action
  client/store/assessment/actions/getSections.ts
  client/store/assessment/actions/initApp.ts
  client/store/assessment/slice.ts
  client/store/assessment/stateType.ts
Labels: enhancement, refactor

#1104 Basic data tables migrations
  core/utils/numbers.ts
  server/db/migration/migrations/20220111145510-move-climatic-domain-to-legacy-schema.js
  server/db/migration/migrations/sqls/20220111145510-move-climatic-domain-to-legacy-schema-down.sql
  server/db/migration/migrations/sqls/20220111145510-move-climatic-domain-to-legacy-schema-up.sql
  tools/dataMigration/_DBNames.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/_getNodeInserts.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateBasicTablesData.ts
Labels: enhancement

#1109 migrate odp | Api Endpoint: /api/assessment/:name/originalDataPoint/:cycleName/:odpId
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/index.ts
  meta/assessment/originalDataPoint/index.ts
  meta/assessment/originalDataPoint/odpDataSource.ts
  meta/assessment/originalDataPoint/odpEditStatus.ts
  meta/assessment/originalDataPoint/odpNationalClass.ts
  meta/assessment/originalDataPoint/odpValidation.ts
  meta/assessment/originalDataPoint/odps/addNationalClassPlaceHolder.ts
  meta/assessment/originalDataPoint/odps/calc.ts
  meta/assessment/originalDataPoint/odps/canCopyPreviousValues.ts
  meta/assessment/originalDataPoint/odps/deleteNationalClass.ts
  meta/assessment/originalDataPoint/odps/index.ts
  meta/assessment/originalDataPoint/odps/removeNationalClassPlaceHolder.ts
  meta/assessment/originalDataPoint/odps/updateNationalClass.ts
  meta/assessment/originalDataPoint/originalDataPoint.ts
  server/api/assessment/getOdp.ts
  server/api/assessment/index.ts
  server/controller/assessment/getOdp.ts
  server/controller/assessment/index.ts
  server/db/migration/migrations/20220114120801-move-original-data-point-to-legacy-schema.js
  server/db/migration/migrations/sqls/20220114120801-move-original-data-point-to-legacy-schema-down.sql
  server/db/migration/migrations/sqls/20220114120801-move-original-data-point-to-legacy-schema-up.sql
  server/repository/assessment/getCreateSchemaDDL.ts
  server/repository/assessment/index.ts
  server/repository/assessment/readOdp.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/migrateOdps.ts
Labels: enhancement, refactor

#1102 Navigation
  client/basePaths.ts
  client/components/CountrySelect/CountrySelect.tsx
  client/components/CountrySelect/ToggleNavigationControl/ToggleNavigationControl.tsx
  client/components/Navigation/NavAssessment/Header/ButtonToggleAll/ButtonToggleAll.tsx
  client/components/Navigation/NavAssessment/Header/ButtonToggleAll/index.ts
  client/components/Navigation/NavAssessment/Header/Header.scss
  client/components/Navigation/NavAssessment/Header/Header.tsx
  client/components/Navigation/NavAssessment/Header/Status/Status.tsx
  client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.scss
  client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.tsx
  client/components/Navigation/NavAssessment/Header/Status/index.ts
  client/components/Navigation/NavAssessment/Header/Status/types.ts
  client/components/Navigation/NavAssessment/Header/Title/Title.tsx
  client/components/Navigation/NavAssessment/Header/Title/index.ts
  client/components/Navigation/NavAssessment/Header/index.ts
  client/components/Navigation/NavAssessment/NavAssessment.tsx
  client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  client/components/Navigation/NavAssessment/Section/ReviewStatusMarker/ReviewStatusMarker.scss
  client/components/Navigation/NavAssessment/Section/ReviewStatusMarker/ReviewStatusMarker.tsx
  client/components/Navigation/NavAssessment/Section/ReviewStatusMarker/index.ts
  client/components/Navigation/NavAssessment/Section/Section.scss
  client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  client/components/Navigation/NavAssessment/Section/SectionItemLink/index.ts
  client/components/Navigation/NavAssessment/Section/index.ts
  client/components/Navigation/NavAssessment/index.ts
  client/components/Navigation/Navigation.scss
  client/components/Navigation/Navigation.tsx
  client/components/Navigation/NavigationDesktop/NavigationDesktop.tsx
  client/components/Navigation/NavigationDesktop/index.ts
  client/components/Navigation/NavigationMobile/NavigationMobile.scss
  client/components/Navigation/NavigationMobile/NavigationMobile.tsx
  client/components/Navigation/NavigationMobile/index.ts
  client/components/Navigation/index.ts
  client/hooks/index.ts
  client/hooks/useIsDataExportView.ts
  client/hooks/useNavigationVisible.ts
  client/pages/Assessment/Assessment.tsx
  client/pages/Assessment/assessment.scss
  client/pages/Assessment/index.ts
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/RootState.ts
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  client/store/rootReducer.ts
  client/store/ui/navigation/hooks/index.ts
  client/store/ui/navigation/index.ts
  client/store/ui/navigation/slice.ts
  client/store/ui/navigation/stateType.ts
  meta/area/areas.ts
Labels: enhancement, refactor

#1112 Add row.props.variableName / col.props.colName
  meta/assessment/col.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateBasicTablesData.ts
  tools/dataMigration/migrateMetadata.ts
Labels: enhancement

#1110 render path for odp
  client/basePaths.ts
  client/components/MultiSelect/MultiSelect.scss
  client/components/MultiSelect/MultiSelect.tsx
  client/components/MultiSelect/index.ts
  client/components/PercentInput/PercentInput.scss
  client/components/PercentInput/PercentInput.tsx
  client/components/PercentInput/index.ts
  client/components/ThousandSeparatedDecimalInput/ThousandSeparatedDecimalInput.scss
  client/components/ThousandSeparatedDecimalInput/ThousandSeparatedDecimalInput.tsx
  client/components/ThousandSeparatedDecimalInput/index.ts
  client/components/VerticallyGrowingTextField/VerticallyGrowingTextField.scss
  client/components/VerticallyGrowingTextField/VerticallyGrowingTextField.tsx
  client/components/VerticallyGrowingTextField/index.ts
  client/pages/Assessment/Assessment.tsx
  client/pages/OriginalDataPoint/OriginalDataPoint.scss
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/OriginalDataPoint/components/ButtonBar/ButtonBar.tsx
  client/pages/OriginalDataPoint/components/ButtonBar/index.ts
  client/pages/OriginalDataPoint/components/Comments/Comments.tsx
  client/pages/OriginalDataPoint/components/Comments/CommentsEditor.tsx
  client/pages/OriginalDataPoint/components/Comments/index.ts
  client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx
  client/pages/OriginalDataPoint/components/DataSources/index.ts
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  client/pages/OriginalDataPoint/components/ExtentOfForest/index.ts
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantation.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/index.ts
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/index.ts
  client/pages/OriginalDataPoint/components/NationalClasses/NationalClasses.tsx
  client/pages/OriginalDataPoint/components/NationalClasses/index.ts
  client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx
  client/pages/OriginalDataPoint/components/OriginalData/index.ts
  client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  client/pages/OriginalDataPoint/components/YearSelection/index.ts
  client/pages/OriginalDataPoint/hooks/index.ts
  client/pages/OriginalDataPoint/hooks/useNationalClassNameComments.ts
  client/pages/OriginalDataPoint/hooks/useNationalClassValidation.ts
  client/pages/OriginalDataPoint/index.ts
  client/pages/PageRoutes/useTheme.ts
  client/store/RootState.ts
  client/store/data/originalDataPoint/actions/fetchOriginalDataPoint.ts
  client/store/data/originalDataPoint/hooks/index.ts
  client/store/data/originalDataPoint/index.ts
  client/store/data/originalDataPoint/slice.ts
  client/store/data/originalDataPoint/stateType.ts
  client/store/rootReducer.ts
  client/store/ui/navigation/slice.ts
  client/styles/fraTable.scss
  client/utils/numberInput.ts
  core/odp/odpEditStatus.ts
  meta/assessment/originalDataPoint/odps/addNationalClassPlaceHolder.ts
  meta/assessment/originalDataPoint/odps/calc.ts
  meta/assessment/originalDataPoint/odps/index.ts
  meta/assessment/originalDataPoint/odps/removeNationalClassPlaceHolder.ts
Labels: enhancement, refactor

#1114 fix user not logged issue
  client/components/CountrySelect/CountryList/CountryList.tsx
  client/hooks/useCountryIso.ts
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/user/hooks/index.ts
Labels: bug

#1116 add definitons api
  _legacy_server/api/definitions/get.ts
  common/api/endpoint/ApiEndPoint.ts
  server/api/api.ts
  server/api/definitions/get.ts
  server/api/definitions/index.ts
  server/api/definitions/utils/getHtml.ts
  server/static/definitions/ar/faq.md
  server/static/definitions/ar/tad.md
  server/static/definitions/en/faq.md
  server/static/definitions/en/tad.md
  server/static/definitions/es/faq.md
  server/static/definitions/es/tad.md
  server/static/definitions/fr/faq.md
  server/static/definitions/fr/tad.md
  server/static/definitions/ru/faq.md
  server/static/definitions/ru/tad.md
  server/static/definitions/zh/faq.md
  server/static/definitions/zh/tad.md
  server/utils/sanityChecks.ts
Labels: enhancement, refactor

#1117 ui definition link
  client/components/DefinitionLink/DefinitionLink.scss
  client/components/DefinitionLink/DefinitionLink.tsx
  client/components/DefinitionLink/index.ts
  client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
Labels: enhancement, refactor

#1124 add data lock
  client/components/CountrySelect/CountrySelect.tsx
  client/components/Navigation/NavAssessment/Header/Header.scss
  client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.scss
  client/components/Navigation/NavAssessment/Header/Title/Title.tsx
  client/components/Navigation/NavAssessment/Section/Section.scss
  client/components/Navigation/NavigationMobile/NavigationMobile.scss
  client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx
  client/store/RootState.ts
  client/store/rootReducer.ts
  client/store/ui/dataLock/hooks/index.ts
  client/store/ui/dataLock/index.ts
  client/store/ui/dataLock/slice.ts
  client/store/ui/dataLock/stateType.ts
Labels: enhancement, refactor

#1121 restored google login and other fixes
  client/pages/Login/LoginForm/LoginForm.tsx
  client/pages/Login/utils/LoginValidator.tsx
  server/api/auth/googleStrategyVerifyCallback.ts
  server/api/auth/localStrategyVerifyCallback.ts
  server/api/auth/login.ts
  server/service/mail/userInvite.ts
Labels: refactor

#1120 resetPassword and changePassword implementation
  server/api/auth/changePassword.ts
  server/api/auth/index.ts
  server/api/auth/resetPassword.ts
  server/controller/user/createResetPassword.ts
  server/controller/user/invite.ts
  server/service/mail/mail.ts
  server/service/mail/resetPassword.ts
  server/utils/requests.ts
Labels: refactor

#1125 BE: CountryStatus
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/countryStatus.ts
  meta/assessment/index.ts
  server/api/assessment/getCountryStatus.ts
  server/api/assessment/index.ts
  server/controller/assessment/getCountryStatus.ts
  server/controller/assessment/index.ts
  server/repository/assessment/getCountryStatus.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  server/repository/assessment/index.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/migrateCountryStatus.ts
Labels: enhancement, refactor

#1128 Migrate tables 1a and 1b
  meta/assessment/node.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/_getNodeInserts.ts
  tools/dataMigration/migrateData/getNodeInsertsTableWithODP.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/index.ts
  tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
Labels: enhancement
