Repository openforis/fra-platform, pull requests merged in 2022-03, with the labels that each got.

#1175 Fix data
  common/countryRole.ts
  common/fraUtils.ts
  common/validateOriginalDataPoint.ts
  server/repository/country/getAllowedCountries.ts
  server/repository/review/reviewRepository.ts
  webapp/sectionSpec/fra/extentOfForest/extentOfForestState.ts
  webapp/sectionSpec/fra/extentOfForest/sectionSpec.ts
  webapp/sectionSpec/fra/forestCharacteristics/sectionSpec.ts
Labels: bug

#1174 Meta/can edit
  client/pages/Assessment/pages/Section/Section.tsx
  client/pages/Assessment/pages/Section/components/DataTable/DataTable.tsx
  client/store/assessment/hooks/index.ts
  client/store/assessment/index.ts
  client/store/pages/assessmentSection/hooks/index.ts
  client/store/pages/assessmentSection/index.ts
  client/store/user/hooks/index.ts
  client/store/user/index.ts
  server/controller/assessment/getSection.ts
  server/controller/assessment/index.ts
  server/middleware/auth.ts
  server/repository/assessment/getSection.ts
  server/repository/assessment/index.ts
  server/repository/table/getOne.ts
  server/repository/table/index.ts
Labels: enhancement

#1181 restored datatable functionality
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/AssessmentSection/DataTable/DataTable.tsx
  client/store/pages/assessmentSection/actions/getTableData.ts
  client/store/pages/assessmentSection/slice.ts
  server/api/assessment/getTableData.ts
  server/controller/cycleData/getTableData.ts
  server/repository/section/getTableNames.ts
  server/repository/section/index.ts
Labels: bug

#1192 Meta/api refactor
  meta/data/tableDatas.ts
  server/api/assessment/getCountryStatus.ts
  server/api/assessment/getOdp.ts
  server/api/assessment/getSectionMetadata.ts
  server/api/assessment/getSections.ts
  server/api/assessment/index.ts
  server/api/assessment/postCountryStatus.ts
  server/api/auth/changePassword.ts
  server/api/auth/createResetPassword.ts
  server/api/auth/index.ts
  server/api/auth/login.ts
  server/api/auth/logout.ts
  server/api/auth/postChangePassword.ts
  server/api/auth/postLogout.ts
  server/api/auth/postResetPassword.ts
  server/api/definitions/get.ts
  server/api/definitions/index.ts
  server/api/init/index.ts
  server/api/init/init.ts
  server/api/user/acceptInvitation.ts
  server/api/user/index.ts
  server/middleware/auth.ts
Labels: refactor

#1196 multi minor fix
  client/pages/AssessmentSection/AssessmentSection.tsx
  client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  client/pages/PageRoutes/PageRoutes.tsx
  client/store/user/hooks/index.ts
  server/api/definitions/utils/getHtml.ts
Labels: refactor

#1203 Index by column
  client/pages/AssessmentSection/DataTable/utils/index.ts
  meta/data/tableDatas.ts
  server/repository/cycleData/getTableData.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
Labels: enhancement

#1206 include query params in check
  server/api/assessment/persistNodeValue.ts
  server/middleware/auth.ts
Labels: bug

#1201 restored google login correct behaviour
  client/pages/Login/Invitation/Invitation.tsx
  client/store/login/actions/localLogin.ts
  i18n/resources/en/login.js
  server/api/auth/config.ts
  server/api/auth/googleStrategyVerifyCallback.ts
  server/api/auth/localStrategyVerifyCallback.ts
  server/api/auth/login.ts
  server/api/auth/postChangePassword.ts
  server/api/auth/postResetPassword.ts
  server/controller/user/changePassword.ts
  server/controller/user/create.ts
  server/controller/user/index.ts
  server/controller/user/invite.ts
  server/controller/user/read.ts
  server/controller/user/readByInvitation.ts
  server/controller/userProvider/create.ts
  server/repository/user/getOne.ts
  server/repository/user/index.ts
  server/repository/user/read.ts
  server/repository/user/update.ts
  server/repository/userProvider/create.ts
  test/integration/assessment/createAssessment.ts
  test/integration/assessment/originalDataPoint.ts
  test/integration/user/userInvite.ts
  test/integration/user/userRemove.ts
  test/integration/user/userResetPassword.ts
  test/integration/user/userSetActive.ts
  test/integration/user/userSetInactive.ts
Labels: bug

#1207 originalDataPoint data API, View, etc
  common/api/endpoint/ApiEndPoint.ts
  server/api/assessment/getOriginalDataPointData.ts
  server/api/assessment/index.ts
  server/repository/assessment/getCreateSchemaDDL.ts
  server/repository/assessment/index.ts
  server/repository/assessmentCycle/create.ts
  server/repository/cycleData/getOriginalDataPointData.ts
  server/repository/cycleData/index.ts
  tools/dataMigration/index.ts
  tools/dataMigration/migrateData/migrateOdps.ts
Labels: enhancement, refactor

#1204 messagecenter be implementation
  common/api/endpoint/ApiEndPoint.ts
  meta/assessment/activityLog.ts
  meta/messageCenter/index.ts
  meta/messageCenter/message.ts
  meta/messageCenter/messageTopic.ts
  server/api/api.ts
  server/api/messageCenter/addMessage.ts
  server/api/messageCenter/getTopic.ts
  server/api/messageCenter/index.ts
  server/controller/messageCenter/addMessage.ts
  server/controller/messageCenter/getTopic.ts
  server/controller/messageCenter/index.ts
  server/db/migration/migrations/20220309093532-message-center.js
  server/db/migration/migrations/sqls/20220309093532-message-center-down.sql
  server/db/migration/migrations/sqls/20220309093532-message-center-up.sql
  server/repository/assessment/read.ts
  server/repository/message/create.ts
  server/repository/message/index.ts
  server/repository/messageTopic/create.ts
  server/repository/messageTopic/getOneOrNone.ts
  server/repository/messageTopic/index.ts
  test/integration/integration.test.ts
  test/integration/messageCenter/messageCenter.ts
Labels: enhancement, refactor

#1208 messagecenter topic ui
  client/components/MessageCenter/MessageCenter.scss
  client/components/MessageCenter/MessageCenter.tsx
  client/components/MessageCenter/Topic/Topic.scss
  client/components/MessageCenter/Topic/Topic.tsx
  client/components/MessageCenter/Topic/index.ts
  client/components/MessageCenter/index.ts
  client/components/Toaster/Toaster.scss
  client/pages/Assessment/Assessment.tsx
  client/store/RootState.ts
  client/store/rootReducer.ts
  client/store/ui/messageCenter/hooks/index.ts
  client/store/ui/messageCenter/index.ts
  client/store/ui/messageCenter/slice.ts
  client/store/ui/messageCenter/stateType.ts
Labels: enhancement

#1218 Geo/sepal auth fix
  server/api/api.ts
  server/api/geo/index.ts
  server/proxy/proxy.ts
  server/proxy/sepalProxy.ts
  server/serverInit.ts
Labels: bug

#1222 datatable review indicator
  client/components/ReviewIndicator/ReviewIndicator.scss
  client/components/ReviewIndicator/ReviewIndicator.tsx
  client/components/ReviewIndicator/index.ts
  client/pages/AssessmentSection/DataTable/DataTable.scss
  client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  client/store/ui/messageCenter/hooks/index.ts
  meta/messageCenter/index.ts
  meta/messageCenter/topics.ts
Labels: enhancement
