Repository openforis/fra-platform, pull requests merged in 2022-10, with the labels that each got.

#1570 Autocomplete component for Scientific name
  package.json
  src/client/components/Autocomplete/Autocomplete.scss
  src/client/components/Autocomplete/Autocomplete.tsx
  src/client/components/Autocomplete/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Calculated/Calculated.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Number/Number.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Placeholder/Placeholder.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Select/Select.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Taxon/Taxon.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Taxon/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Text/Text.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useClassName.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/props.ts
  src/meta/assessment/col.ts
  src/meta/extData/taxon.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateMetadata/index.ts
  yarn.lock
Labels: enhancement

#1575 Fix crash on null value
  src/client/hooks/useOnResize.ts
  src/client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx
Labels: bug

#1576 ODP 1b allow plantations subcategories when plantation is 0
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx
Labels: enhancement

#1579 Fix missing labels and missing null checks
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Placeholder/Placeholder.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantation.tsx
Labels: bug

#1578 Metadata 2025: Section 1a/1b
  src/client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Placeholder/Placeholder.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowNoticeMessage/RowNoticeMessage.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/client/pages/DataExport/ResultsTable/Title/Title.tsx
  src/i18n/resources/ar.js
  src/i18n/resources/ar/fra.js
  src/i18n/resources/en.js
  src/i18n/resources/en/fra.js
  src/i18n/resources/es.js
  src/i18n/resources/es/fra.js
  src/i18n/resources/fr.js
  src/i18n/resources/fr/fra.js
  src/i18n/resources/ru.js
  src/i18n/resources/ru/fra.js
  src/i18n/resources/zh.js
  src/i18n/resources/zh/fra.js
  src/meta/assessment/col.ts
  src/meta/assessment/cols.ts
  src/server/repository/assessment/section/getManyMetadata.ts
  src/test/dataExportComparison/fetchData.ts
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/deleteWrongCalculatedNodes.ts
  src/test/dataMigration/steps/migratePrimaryForestData.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/dataMigration/steps/validateNodes/validateNodes.ts
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/rowSpec.ts
  src/test/sectionSpec/tableSpec.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getTable.ts
  tools/dataMigration/migrateMetadata/utils.ts
Labels: infrastructure

#1581 Meta/validators private forest
  src/client/pages/AssessmentSection/DataTable/Table/Row/Row.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowValidation/RowValidation.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowValidation/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/i18n/resources/en.js
  src/meta/assessment/row.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorEqualToPrivateForest.ts
  src/test/dataMigration/postDataMigration.ts
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1585 Handle SubSection per cycle anchor
  src/client/components/ButtonCheckBox/ButtonCheckBox.scss
  src/client/components/ButtonCheckBox/ButtonCheckBox.tsx
  src/client/components/CollaboratorAccessModal/CollaboratorAccessModal.tsx
  src/client/components/CollaboratorAccessModal/collaboratorAccessModal.scss
  src/client/components/CollaboratorAccessModal/hooks/useActions.ts
  src/client/components/EditUserForm/CollaboratorPermissions/CollaboratorPermissions.tsx
  src/client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  src/client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  src/client/pages/AssessmentPrint/FraPrint/ContactPersons/ContactPersons.tsx
  src/meta/assessment/index.ts
  src/meta/assessment/section.ts
  src/meta/assessment/subSections.ts
  src/server/repository/assessment/section/getMany.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sectionSpec.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/dataMigration/migrateUsersRole.ts
Labels: enhancement, refactor, infrastructure

#1591 ODP/NationalClass: Display 0% for cell if row is 100%
  src/client/components/Autocomplete/Autocomplete.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx
  src/meta/assessment/originalDataPoint/odps/updateNationalClass.ts
Labels: enhancement

#1593 Meta/unkown other validator greater than or zero
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorGreaterThanOrZero.ts
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1594 Fix print view sub section anchor in title
  src/client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Title/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/AssessmentSection/Title/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/AssessmentSection/Title/Title.tsx
  src/client/pages/AssessmentSection/Title/TitleExcelCalculator/TitleExcelCalculator.tsx
  src/client/pages/AssessmentSection/Title/props.ts
  src/meta/assessment/subSections.ts
Labels: bug

#1595 Migrate per cycle section labels / update label 1c 2025
  src/client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  src/client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  src/client/pages/AssessmentPrint/FraPrint/FraPrint.tsx
  src/client/pages/AssessmentPrint/FraPrint/TableOfContent/TableOfContent.tsx
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Title/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/AssessmentSection/Title/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/AssessmentSection/Title/Title.tsx
  src/client/pages/AssessmentSection/Title/TitleExcelCalculator/TitleExcelCalculator.tsx
  src/client/pages/AssessmentSection/Title/props.ts
  src/i18n/resources/en/fra.js
  src/meta/assessment/cols.ts
  src/meta/assessment/index.ts
  src/meta/assessment/labels.ts
  src/meta/assessment/section.ts
  src/server/repository/assessment/section/getMany.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sectionSpec.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: infrastructure

#1596 Descriptions: Update content:string to value: { text }
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/CommentableDescription.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  src/client/pages/AssessmentSection/Descriptions/Descriptions.tsx
  src/client/store/pages/assessmentSection/actions/getDescription.ts
  src/client/store/pages/assessmentSection/actions/updateDescription.ts
  src/client/store/pages/assessmentSection/hooks/useDescription.ts
  src/client/store/pages/assessmentSection/slice.ts
  src/client/store/pages/assessmentSection/stateType.ts
  src/meta/assessment/commentableDescription.ts
  src/meta/assessment/index.ts
  src/server/api/cycleData/descriptions/getDescription.ts
  src/server/api/cycleData/descriptions/upsertDescription.ts
  src/server/controller/cycleData/upsertDescription.ts
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
  src/server/repository/assessmentCycle/descriptions/getOneOrNone.ts
  src/server/repository/assessmentCycle/descriptions/upsert.ts
  src/test/dataMigration/steps/migrateDescriptions.ts
Labels: enhancement

#1601 2025 Metadata: Section 1
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
Labels: infrastructure

#1606 Metadata 2025: migrate table 2b
  src/client/components/ButtonCheckBox/ButtonCheckBox.scss
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowNoticeMessage/RowNoticeMessage.tsx
  src/client/pages/DataExport/utils/labelKeys.ts
  src/i18n/resources/en.js
  src/i18n/resources/en/fra.js
  src/meta/data/tableDatas.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/evaluators/member.ts
  src/test/dataExportComparison/getMetadata.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: infrastructure

#1617 Meta/2025 meta 7
  src/client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
  src/client/store/pages/assessmentSection/slice.ts
  src/meta/assessment/assessmentMetaCache.ts
  src/meta/assessment/row.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/rowSpec.ts
  tools/dataMigration/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts
  tools/dataMigration/migrateMetadata/getRow.ts
Labels: enhancement

#1620 Autocomplete: Use downshift, update styles
  package.json
  src/client/components/Autocomplete/Autocomplete.scss
  src/client/components/Autocomplete/Autocomplete.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Taxon/Taxon.tsx
  yarn.lock
Labels: enhancement

#1632 Fix auth token expire date
  src/server/api/auth/login.ts
  src/utils/dates.ts
Labels: bug

#1629 2025 Metadata: Introduce categoryLevel and Update table 2a
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/client/styles/fraTable.scss
  src/i18n/resources/en/fra.js
  src/meta/assessment/row.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/rowSpec.ts
  tools/dataMigration/migrateMetadata/getRow.ts
Labels: infrastructure

#1633 Fix issue with unknown calculation where value was not rounded
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
Labels: bug

#1635 calculateRow: Fix rounding
  src/test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
Labels: bug

#1634 update sustainableDevelopment sdgIndicator1 columns
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/sectionSpec/fraSpecs.ts
Labels: infrastructure

#1636 Rollback rounding
  src/server/controller/cycleData/persistNodeValue/calculateDependantNodes/calculateNode.ts
  src/test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
Labels: bug

#1642 Metadata 2025: metadata migration section 8
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/i18n/resources/en/fra.js
  src/meta/assessment/tableSection.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/evaluators/binary.ts
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sectionSpec.ts
  src/utils/numbers.ts
  tools/dataMigration/migrateMetadata/getTableSection.ts
Labels: infrastructure

#1643 Numbers.format: replace -0 with 0
  src/utils/numbers.ts
Labels: bug

#1644 Fix validations for 2a | Fix pasting values | Fix prettier stylelint
  package.json
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  src/server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorSubCategory.ts
Labels: bug

#1645 Metadata 2025: metadata migration section 4a
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1646 Metadata 2025: metadata migration section 4b
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1649 Meta/2025 meta 5
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1656 Meta/2025 meta 3
  src/i18n/resources/en/fra.js
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1659 Metadata 2025: Section 1
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayerOptionsPanel/layerOptionsPanel.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuListElement/geoMapMenuListElement.scss
  src/i18n/resources/en/fra.js
  src/test/dataMigration/postDataMigration.ts
  src/test/dataMigration/steps/add2025Columns/add2025Columns.ts
  src/test/dataMigration/steps/deleteInvalid2025Nodes/deleteInvalid2025Nodes.ts
  src/test/dataMigration/steps/metadataFix/metadataFix.ts
  src/test/dataMigration/steps/migratePrimaryForestData.ts
  src/test/sectionSpec/fraSpecs.ts
  tools/dataMigration/migrateMetadata/getTable.ts
Labels: infrastructure

#1662 Metadata 2025: metadata migration section 6, 7
  src/i18n/resources/en/fra.js
  src/server/repository/assessment/section/getMany.ts
  src/test/dataMigration/steps/postMetadataFix/postMetadataFix.ts
  src/test/sectionSpec/fraSpecs.ts
Labels: enhancement

#1663 fix country navigation
  src/client/store/pages/assessmentSection/hooks/index.ts
Labels: bug
