Repository openforis/fra-platform, pull requests merged in 2023-12, with the labels that each got.

#3277 Geo reviewers only access for geo and beta version message
  src/client/components/PageLayout/Toolbar/Toolbar.scss
  src/client/components/PageLayout/Toolbar/Toolbar.tsx
  src/client/pages/Geo/Geo.tsx
Labels: enhancement

#3287 3221 the writing box is still hard to read if writing a long text
  src/client/components/Inputs/TextArea/TextArea.tsx
  src/client/components/Inputs/TextArea/hooks/useResize.ts
  src/client/components/MessageCenter/Topic/Topic.tsx
  src/client/components/Resizable/Resizable.tsx
Labels: enhancement

#3300 Center FRA Beta message in toolbar in geo page
  src/client/components/PageLayout/Toolbar/Toolbar.scss
  src/client/components/PageLayout/Toolbar/Toolbar.tsx
Labels: enhancement

#3299 3285 guidelines and specifications + tutorials
  src/client/components/CycleSwitch/CycleSwitch.tsx
  src/client/components/CycleSwitch/index.ts
  src/client/components/PageLayout/Footer/Footer.tsx
  src/client/components/PageLayout/Footer/UserGuideLink/UserGuideLink.tsx
  src/client/components/PageLayout/Footer/UserGuideLink/index.ts
  src/client/components/PageLayout/Footer/hooks/useIsFooterVisible.ts
  src/client/pages/Tutorials/GuidelinesAndSpecifications/GuidelinesAndSpecifications.tsx
  src/client/pages/Tutorials/GuidelinesAndSpecifications/index.ts
  src/client/pages/Tutorials/Tutorials.tsx
  src/i18n/resources/ar.js
  src/i18n/resources/ar/common.js
  src/i18n/resources/en.js
  src/i18n/resources/en/common.js
  src/i18n/resources/es.js
  src/i18n/resources/es/common.js
  src/i18n/resources/fr.js
  src/i18n/resources/fr/common.js
  src/i18n/resources/ru.js
  src/i18n/resources/ru/common.js
  src/i18n/resources/zh.js
  src/i18n/resources/zh/common.js
Labels: enhancement

#3315 Geo refactor/recipe selector
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/RecipeSelector/RecipeSelector.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/RecipeSelector/RecipeSelector.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/RecipeSelector/index.ts
  src/client/store/ui/geo/actions/index.ts
  src/client/store/ui/geo/actions/postLayer.ts
  src/client/store/ui/geo/actions/setLayerOpacity.ts
  src/client/store/ui/geo/actions/setLayerSectionRecipe.ts
  src/client/store/ui/geo/actions/setSectionGlobalOpacity.ts
  src/client/store/ui/geo/actions/toggleLayer.ts
  src/client/store/ui/geo/hooks/index.ts
  src/client/store/ui/geo/index.ts
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
  src/meta/geo/forest.ts
  src/meta/geo/index.ts
  src/meta/geo/layer.ts
Labels: enhancement, refactor

#3321 3174 - Contacts: NodeExt migration
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
  src/test/migrations/steps/20231215110302-step-update-node_ext-table.ts
Labels: refactor

#3332 Fix col heading offset bug
  src/client/components/ButtonTableExport/utils.ts
Labels: bug

#3334 3303 geo refactor Agreement Layer / Custom Assets
  src/client/pages/Geo/GeoMap/GeoMap.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/AgreementLevelControl/AgreementLevelControl.tsx
  src/client/pages/Geo/GeoMap/hooks/index.ts
  src/client/pages/Geo/GeoMap/hooks/useCountSectionSelectedLayers.ts
  src/client/pages/Geo/GeoMap/hooks/useCountryIsoChangeHandler.ts
  src/client/pages/Geo/GeoMap/hooks/useFetchAgreementLevelLayer.ts
  src/client/pages/Geo/GeoMap/hooks/useMapLayersHandler.ts
  src/client/store/ui/geo/actions/toggleLayer.ts
  src/client/store/ui/geo/hooks/index.ts
  src/client/store/ui/geo/index.ts
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
Labels: enhancement, refactor

#3345 Add missing cycle name to translation
  src/client/pages/Print/FraPrint/TableOfContent/TableOfContent.tsx
Labels: bug
