Repository openforis/fra-platform, pull requests merged in 2023-07, with the labels that each got.

#2840 Datasources: Freetext for year
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/ColumnYearForDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/datasourceValidators.tsx
Labels: enhancement

#2857 Fix dependencies fetch
  src/client/pages/AssessmentSection/DataTable/hooks/useGetTableData.ts
Labels: bug

#2855 Feat/paneu updates
  src/client/components/ThousandSeparatedIntegerInput/ThousandSeparatedIntegerInput.tsx
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/server/static/definitions/panEuropean/2020/en/rn.md
  src/server/static/definitions/panEuropean/2025/en/rn.md
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/nonWoodGoods.ts
  src/test/sectionSpec/panEuSections/protectedForests.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
  tools/dataMigration/dataTable/mappings/panEuropean/table2_4.ts
Labels: bug, enhancement

#2868 Feat/pan eu fixes
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestHoldings.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/protectedForests.ts
  src/test/sectionSpec/panEuSections/recreationInForest.ts
Labels: bug, enhancement

#2882 Update Reporting Notes
  src/server/static/definitions/panEuropean/2020/en/rn.md
  src/server/static/definitions/panEuropean/2025/en/rn.md
Labels: enhancement

#2885 updates mentioned in the meeting
  src/client/pages/AssessmentHome/PanEuropeanHome/Overview/Overview.tsx
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/forestHoldings.ts
  web-resources/img/partners/skogsstyrelsen.png
  web-resources/img/partners/skogsstyrelsen.svg
Labels: enhancement

#2892 update landing page
  src/i18n/resources/en/area.js
  src/i18n/resources/en/panEuropean/panEuropean.js
Labels: enhancement

#2894 Free text editor: Add spellcheck
  src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx
Labels: enhancement
