Repository openforis/fra-platform, pull requests merged in 2023-10, with the labels that each got.

#3104 ActivityLog: Add pagination and refresh log every hour
  src/client/components/TablePaginated/Body/Body.tsx
  src/client/components/TablePaginated/TablePaginated.scss
  src/client/components/TablePaginated/TablePaginated.tsx
  src/client/components/TablePaginated/hooks/useFetchData.tsx
  src/client/components/TablePaginated/index.ts
  src/client/components/TablePaginated/types.ts
  src/client/pages/CountryHome/FraHome/Links/Links.tsx
  src/client/pages/CountryHome/FraHome/RecentActivity/EmptyActivities/EmptyActivities.tsx
  src/client/pages/CountryHome/FraHome/RecentActivity/EmptyActivities/index.ts
  src/client/pages/CountryHome/FraHome/RecentActivity/RecentActivity.tsx
  src/client/pages/CountryHome/FraHome/RecentActivity/RecentActivityItem/RecentActivityItem.scss
  src/client/pages/CountryHome/FraHome/RecentActivity/RecentActivityItem/RecentActivityItem.tsx
  src/client/pages/CountryHome/FraHome/RecentActivity/hooks/useColumns.tsx
  src/client/pages/CountryHome/FraHome/RecentActivity/limit.ts
  src/client/store/ui/tablePaginated/actions/getCount.ts
  src/client/store/ui/tablePaginated/actions/getData.ts
  src/meta/api/endpoint/ApiEndPoint.ts
  src/meta/api/request/tablePaginated.ts
  src/server/api/cycleData/activities/getActivities.ts
  src/server/api/cycleData/activities/getActivitiesCount.ts
  src/server/api/cycleData/index.ts
  src/server/controller/cycleData/index.ts
  src/server/db/migration/migrations/sqls/20221003094432-table-activity-log-up.sql
  src/server/repository/assessmentCycle/countryActivityLog/_common/acceptedMessages.ts
  src/server/repository/assessmentCycle/countryActivityLog/_common/getMaterializedViewName.ts
  src/server/repository/assessmentCycle/countryActivityLog/_common/hiddenSections.ts
  src/server/repository/assessmentCycle/countryActivityLog/createMaterializedView.ts
  src/server/repository/assessmentCycle/countryActivityLog/getCount.ts
  src/server/repository/assessmentCycle/countryActivityLog/getMany.ts
  src/server/repository/assessmentCycle/countryActivityLog/index.ts
  src/server/repository/assessmentCycle/countryActivityLog/refreshMaterializedView.ts
  src/server/repository/public/activityLog/getCycleDataActivities.ts
  src/server/repository/public/activityLog/index.ts
  src/server/schedulers/index.ts
  src/server/schedulers/initCountryActivityLog.ts
  src/test/migrations/steps/20231002102202-step-activity-log-indexes.ts
  src/test/migrations/steps/20231002130843-step-activity-log-mv-cycle-country.ts
Labels: enhancement

#3117 Translation update: Forest area net change calculated from table 1a
  src/i18n/resources/ar.js
  src/i18n/resources/en.js
  src/i18n/resources/es.js
  src/i18n/resources/fr.js
  src/i18n/resources/ru.js
  src/i18n/resources/zh.js
Labels: enhancement

#3120 Fix imported values for 1b: Primary forest by climatic domain
  src/test/migrations/steps/20231006141043-step-1b-fix-migrated-values-2025-fra.ts
Labels: bug

#3129 Show vertical scrollbar in StatusConfirm
  src/client/components/PageLayout/Toolbar/Status/StatusConfirm.scss
Labels: bug, enhancement

#3128 Larger width for Type of Datasource input
  src/client/pages/Section/Descriptions/CommentableDescription/Description/DataSources/DataSources.scss
Labels: bug, enhancement

#3114 Fix: Section 8 - Sub Indicator 4 wrong calculation results
  src/server/controller/cycleData/updateDependencies/context/contextFactory.ts
  src/server/repository/redis/keys.ts
  src/server/repository/redis/row/getRows.ts
  src/test/migrations/steps/20231005083305-step-fix-sdg-sub4-calculation.ts
  src/test/migrations/steps/utils/calculateRow.ts
  src/test/migrations/steps/utils/runCalculations.ts
  src/test/migrations/steps/utils/updateCalculatedVariable.ts
Labels: bug

#3146 Added migration step to remove fra connection
  src/test/migrations/steps/20231016183656-step-panEu-421-remove-logic-check.ts
Labels: enhancement

#3150 Keep the text in the feedback email in its original format
  src/server/service/mail/assessmentNotifyUsers.ts
Labels: bug, enhancement

#3153 NDP/1b: Allow empty values when calculating primary/introduced values
  package.json
  src/meta/assessment/originalDataPoint/odps/calc.ts
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
  src/server/repository/redis/data/cacheCountryTable.ts
  src/server/repository/redis/data/getCountriesData.ts
  src/server/schedulers/index.ts
  src/test/migrations/steps/20231018130522-step-odp-view-update-primaryforest-introducedforest.ts
Labels: bug, enhancement

#3140 NDP: Year change controller and update dependant tables and values
  src/client/store/data/hooks/useOriginalDataPointYears.ts
  src/meta/assessment/activityLogs.ts
  src/server/api/cycleData/originalDataPoint/updateOriginalDataPointYear.ts
  src/server/controller/cycleData/index.ts
  src/server/controller/cycleData/originalDataPoint/copyOriginalDataPointNationalClasses.ts
  src/server/controller/cycleData/originalDataPoint/createOriginalDataPoint.ts
  src/server/controller/cycleData/originalDataPoint/deleteOriginalDataPointNationalClass.ts
  src/server/controller/cycleData/originalDataPoint/removeOriginalDataPoint.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/notifyClientUpdate.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/updateOriginalDataPointDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/updateOriginalDataPointsDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointOriginalData.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointYear.ts
  src/server/repository/assessmentCycle/countryActivityLog/_common/acceptedMessages.ts
  src/server/repository/assessmentCycle/originalDataPoint/index.ts
  src/server/repository/assessmentCycle/originalDataPoint/updateYear.ts
Labels: enhancement

#3172 3159 disable user backend
  src/meta/user/users.ts
  src/server/api/admin/getUsers.ts
  src/server/api/user/getUser.ts
  src/server/repository/public/user/getMany.ts
  src/server/repository/public/user/getOne.ts
  src/server/repository/public/user/update.ts
Labels: enhancement

#3173 NDP: Refetch reserved years after updating NDP year
  src/client/hooks/useRouteParams.ts
  src/client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  src/client/pages/OriginalDataPoint/hooks/useGetOriginalDataPoint.ts
  src/client/pages/OriginalDataPoint/hooks/useGetReviewStatus.ts
  src/client/pages/OriginalDataPoint/hooks/useReservedYears.ts
  src/client/store/ui/originalDataPoint/slice.ts
  src/meta/socket/sockets.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointYear.ts
Labels: bug

#3152 NDP: Allow changing year
  src/client/hooks/useRouteParams.ts
  src/client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  src/client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
  src/client/pages/OriginalDataPoint/components/YearSelection/hooks/useOnChange.tsx
  src/client/pages/OriginalDataPoint/hooks/useGetOriginalDataPoint.ts
  src/client/pages/OriginalDataPoint/hooks/useGetReviewStatus.ts
  src/client/pages/OriginalDataPoint/hooks/useReservedYears.ts
  src/client/store/data/hooks/useOriginalDataPointYears.ts
  src/client/store/ui/originalDataPoint/actions/updateOriginalDataPointYear.ts
  src/client/store/ui/originalDataPoint/slice.ts
  src/meta/api/endpoint/ApiEndPoint.ts
  src/meta/assessment/activityLogs.ts
  src/meta/socket/sockets.ts
  src/server/api/cycleData/index.ts
  src/server/api/cycleData/originalDataPoint/updateOriginalDataPointYear.ts
  src/server/controller/cycleData/index.ts
  src/server/controller/cycleData/originalDataPoint/copyOriginalDataPointNationalClasses.ts
  src/server/controller/cycleData/originalDataPoint/createOriginalDataPoint.ts
  src/server/controller/cycleData/originalDataPoint/deleteOriginalDataPointNationalClass.ts
  src/server/controller/cycleData/originalDataPoint/removeOriginalDataPoint.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/notifyClientUpdate.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/updateOriginalDataPointDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateDependants/updateOriginalDataPointsDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointDependentNodes.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointOriginalData.ts
  src/server/controller/cycleData/originalDataPoint/updateOriginalDataPointYear.ts
  src/server/repository/assessmentCycle/countryActivityLog/_common/acceptedMessages.ts
  src/server/repository/assessmentCycle/originalDataPoint/index.ts
  src/server/repository/assessmentCycle/originalDataPoint/updateYear.ts
Labels: enhancement

#3180 Datasources: Type of data source cell width
  src/client/pages/Section/Descriptions/CommentableDescription/Description/DataSources/DataSources.scss
Labels: bug

#3202 FIx printing when not logged in
  src/client/store/metadata/hooks/useTableSections.ts
Labels: bug
