Repository openforis/fra-platform, pull requests merged in 2023-04, with the labels that each got.

#2517 updated terms and definitions
  src/server/static/definitions/panEuropean/2025/en/rn.md
  src/server/static/definitions/panEuropean/2025/en/tad.md
Labels: bug

#2518 2506 update reasonableness
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
Labels: enhancement

#2522 2516 update comments fix
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/1.3b_C3.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/2.5_C1.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/3.4_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.9_C1.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.9_C2.csv
Labels: enhancement

#2485 fix data source variables
  src/client/components/Autocomplete/Autocomplete.tsx
  src/client/components/MultiSelect/MultiSelect.tsx
  src/client/components/MultiSelect/option.ts
  src/client/components/UserListFilters/UserListFilters.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Multiselect/Multiselect.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Taxon/Taxon.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnYearForDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  src/client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx
  src/i18n/resources/en/dataSource.js
  src/meta/assessment/descriptions.ts
  src/test/migrations/steps/20230403165717-step-map-datasource-freetext-to-constant.ts
  src/test/migrations/steps/utils/getAssessmentCycle.ts
Labels: bug

#2526 update table 3.4 metadata countrycomments
  src/test/sectionSpec/PanEuropeanSpecs.ts
Labels: enhancement

#2535 Data source bug fixes
  src/client/components/Autocomplete/Autocomplete.tsx
  src/client/components/Autocomplete/AutocompleteInput.tsx
  src/client/components/Navigation/NavAssessment/Section/NavigationSection.tsx
  src/client/components/Navigation/NavAssessment/Section/SectionItemLink/SectionItemLink.tsx
  src/client/pages/AssessmentPrint/FraPrint/FraPrint.tsx
  src/client/pages/AssessmentPrint/FraPrint/TableOfContent/TableOfContent.tsx
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnYearForDataSource.tsx
  src/client/pages/AssessmentSection/Title/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/AssessmentSection/Title/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/AssessmentSection/Title/Title.tsx
  src/client/pages/AssessmentSection/Title/TitleExcelCalculator/TitleExcelCalculator.tsx
  src/client/pages/DataExport/VariableSelect/VariableSelect.tsx
  src/meta/assessment/col.ts
  src/meta/assessment/cols.ts
  src/meta/assessment/description.ts
  src/meta/assessment/index.ts
  src/meta/assessment/labels.ts
  src/meta/assessment/row.ts
  src/test/migrations/steps/20230403165717-step-map-datasource-freetext-to-constant.ts
  src/test/migrations/steps/20230411163053-step-2b-data-source-prefixes.ts
Labels: bug

#2544 use odp for year 2005 in SDG table 1
  src/test/migrations/steps/20230417093931-step-fix-8a-2005-use-odp.ts
Labels: bug, enhancement

#2549 Add missing translations for FR
  src/i18n/resources/fr.js
  src/i18n/resources/fr/common.js
  src/i18n/resources/fr/contentCheck.js
  src/i18n/resources/fr/dataSource.js
  src/i18n/resources/fr/fra.js
  src/i18n/resources/fr/login.js
  src/i18n/resources/fr/uc.js
Labels: translations

#2529 update metadata indicator 2.5
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/i18n/resources/en.js
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/meta/assessment/col.ts
  src/meta/assessment/cols.ts
  src/meta/expressionEvaluator/functions/index.ts
  src/meta/expressionEvaluator/functions/validatorNotEmpty.ts
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  src/test/sectionSpec/panEuSections/forestInvestment.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  tools/dataMigration/dataTable/mappings/panEuropean/table2_5.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
Labels: enhancement

#2553 Update zh/fra.js
  src/i18n/resources/zh/fra.js
Labels: translations

#2541 Update validations 5a/5b
  src/i18n/resources/en.js
  src/meta/expressionEvaluator/functions/index.ts
  src/meta/expressionEvaluator/functions/maxForestArea.ts
  src/meta/expressionEvaluator/functions/maxLandArea.ts
  src/meta/expressionEvaluator/functions/validatorColSumNotGreaterThanForest.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanForest.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanForestOrMaxForest.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanLandArea.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanLandAreaOrMaxLandArea.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanMaxForest.ts
  src/meta/expressionEvaluator/functions/validatorSumNotGreaterThan.ts
  src/meta/expressionEvaluator/functions/validatorSumNotGreaterThanForest.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/call.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/customDepenendencies.ts
  src/test/migrations/steps/20230413122159-step-5a-5b-update-validations.ts
  src/utils/numbers.ts
Labels: enhancement

#2559 fixed md for links
  src/server/static/definitions/panEuropean/2020/en/rn.md
  src/server/static/definitions/panEuropean/2020/en/tad.md
  src/server/static/definitions/panEuropean/2025/en/rn.md
  src/server/static/definitions/panEuropean/2025/en/tad.md
Labels: bug

#2560 2548 pan eu hide sections
  src/meta/assessment/section.ts
  src/server/repository/assessment/section/getMany.ts
  src/server/repository/assessment/section/getManyMetadata.ts
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/forestInvestment.ts
  src/test/sectionSpec/panEuSections/forestWorkforce.ts
  src/test/sectionSpec/sectionSpec.ts
  src/test/sectionSpec/tableSpec.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getSection.ts
Labels: enhancement

#2567 Fix IntroductoryText
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
Labels: bug

#2575 2571 ind 25 text in placeholder
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Text/Text.tsx
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/meta/assessment/col.ts
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  tools/dataMigration/migrateMetadata/getCol.ts
Labels: enhancement
