Repository openforis/fra-platform, pull requests merged in 2023-06, with the labels that each got.

#2744 Github Actions: FIX TEST/BUILD & Reduce mail connections to 1 and use pool
  .github/workflows/test.js.yml
  src/server/service/mail/mail.ts
Labels: bug

#2711 Jsep assessment cycle member
  package.json
  src/meta/assessment/assessmentMetaCache.ts
  src/meta/expressionEvaluator/evaluators/member.ts
  src/meta/expressionEvaluator/index.ts
  src/meta/expressionEvaluator/util/parseMemberVariable.test.ts
  src/meta/expressionEvaluator/util/parseMemberVariable.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts
  src/server/controller/cycleData/getOriginalDataPointVariables.ts
  src/test/generateMetaCache/index.ts
  src/test/generateMetaCache/jest.config.js
  src/tools/generateMetaCache/index.ts
Labels: enhancement, refactor

#2758 Show error if email doesnt exist
  src/client/components/InviteUserForm/InviteUserForm.tsx
  src/server/service/mail/mail.ts
Labels: enhancement

#2755 fix autocomplete
  src/client/components/Autocomplete/Autocomplete.tsx
Labels: bug

#2739 add fixes
  src/i18n/resources/en/panEuropean/countryComments.js
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/4.4_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/migrateCountryComments.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
Labels: bug, enhancement

#2760 DataSources error messages
  src/client/components/DataGrid/DataColumn.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/ColumnComments.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/ColumnReference.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/ColumnYearForDataSource.tsx
  src/i18n/resources/en.js
Labels: enhancement

#2776 Show error if user is logged in
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
Labels: bug

#2777 upgraded landing page as requested
  src/client/pages/AssessmentHome/PanEuropeanHome/Overview/Overview.tsx
  src/i18n/resources/en/panEuropean/panEuropean.js
Labels: enhancement

#2769 PanEuropean: use only English
  src/client/components/PageLayout/Header/LanguageSelector/LanguageSelector.tsx
  src/client/components/PageLayout/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  src/client/pages/Assessment/Assessment.tsx
  src/client/utils/updateLanguage.ts
Labels: enhancement

#2780 Update 4a unknown
  src/test/migrations/steps/20230615121954-step-autocalculate-4a-unknown.ts
  src/test/migrations/steps/utils/updateRowCalculateFn.ts
Labels: enhancement

#2781 ODP: Naturally regenerating forest: hide zero valued fields
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsNaturallyRegeneratingRow.tsx
Labels: bug

#2782 Fix copying rows in table 2a
  src/client/pages/AssessmentSection/DataTable/Table/ButtonCopyValues/ButtonCopyValues.tsx
Labels: bug

#2790 updated cvs files
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.10_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.1_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.5_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.6_C2.csv
  src/test/dataMigration/stepsPanEuropean/countryComments/CSV/6.9_C1.csv
Labels: bug

#2792 Feat/upgrade validations
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
  src/test/sectionSpec/panEuSections/deadwood.ts
  tools/dataMigration/panEuropean.ts
Labels: bug, enhancement
