Repository openforis/fra-platform, pull requests merged in 2023-01, with the labels that each got.

#1942 PanEuropean: 2025 metadata
  src/test/sectionSpec/PanEuropeanSpecs.ts
Labels: enhancement

#1950 ODP Labels by cycle
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  src/client/pages/OriginalDataPoint/components/NationalClasses/NationalClasses.tsx
  src/i18n/resources/ar.js
  src/i18n/resources/en.js
  src/i18n/resources/es.js
  src/i18n/resources/fr.js
  src/i18n/resources/ru.js
  src/i18n/resources/zh.js
Labels: bug, enhancement

#1946 Update unit tests for estimation engine
  src/server/service/estimates/datasets/dataset1.ts
  src/server/service/estimates/datasets/dataset2.ts
  src/server/service/estimates/datasets/dataset3.ts
  src/server/service/estimates/datasets/dataset4.ts
  src/server/service/estimates/datasets/dataset5.ts
  src/server/service/estimates/datasets/dataset6.ts
  src/server/service/estimates/estimationEngine.test.ts
  src/server/service/estimates/estimationEngine.ts
  src/server/service/estimates/getODP.ts
Labels: test

#1959 PanEuropean: 2025 metadata
  src/test/sectionSpec/PanEuropeanSpecs.ts
  tools/dataMigration/migrateMetadata/index.ts
Labels: enhancement

#1990 PanEuropean: custom Cycle page + Header with cycleSwitch and home link
  src/client/components/AssessmentSwitch/AssessmentSwitch.tsx
  src/client/components/PageLayout/Header/PanEuropeanHeader/PanEuropeanHeader.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/Description/Description.tsx
  src/client/pages/AssessmentHome/PanEuropeanHome/PanEuropeanHome.scss
  src/client/pages/Cycle/Cycle.tsx
  src/client/pages/PageRoutes/useTheme.ts
Labels: enhancement

#1962 Section 8 prefill data
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/reportYears.ts
  src/test/sectionSpec/sections/carbonStock.ts
  src/test/sectionSpec/sections/sustainableDevelopment.ts
Labels: enhancement

#2001 Resolve redirect issue when user is logged
  src/client/pages/PageRoutes/PageRoutes.tsx
  src/client/store/assessment/hooks/index.ts
  src/client/store/assessment/index.ts
  src/client/store/assessment/slice.ts
  src/client/store/assessment/stateType.ts
Labels: bug

#2016 update github deploy workflows
  .github/workflows/heroku-development.yml
  .github/workflows/heroku-production.js.yml
  .github/workflows/heroku-staging.yml
  .github/workflows/test.js.yml
Labels: infrastructure

#2018 enable data entry in watch mode and fix infinite redis memory growing by reducing kept queue events (events: { maxLen: 10 })
  src/server/api/cycleData/table/postEstimation.ts
  src/server/controller/assessment/index.ts
  src/server/controller/cycleData/updateDependencies/queueFactory.ts
  src/server/controller/cycleData/updateDependencies/scheduleUpdateDependencies.ts
  src/server/controller/cycleData/updateDependencies/workerFactory.ts
  src/test/dataMigration/steps/updateCalculatedNodes/calculateRow.ts
Labels: infrastructure

#2010 Table 4a calculation issues
  src/server/controller/cycleData/updateDependencies/expressionEvaluator/functions/validatorEqualToPrivateForest.ts
  src/server/controller/cycleData/updateDependencies/updateCalculationDependencies/calculateNode.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/forestOwnership.ts
  src/test/sectionSpec/sections/holderOfManagementRights.ts
Labels: bug, enhancement

#2012 Several fixes for DataSources description
  src/client/components/Autocomplete/Autocomplete.scss
  src/client/components/MultiSelect/MultiSelect.scss
  src/client/components/MultiSelect/MultiSelect.tsx
  src/client/components/UserListFilters/UserListFilters.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceRow.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.scss
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.tsx
  src/client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx
  src/client/styles/checkbox.scss
  src/meta/assessment/commentableDescription.ts
Labels: bug, enhancement

#2028 ci(Mergify): configuration update
  .mergify.yml
Labels: infrastructure

#2031 Fix autocomplete not persisting value (Eg. data sources)
  src/client/components/Autocomplete/Autocomplete.tsx
Labels: bug

#2037 Validation/section 5
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/areaAffectedByFire.ts
  src/test/sectionSpec/sections/disturbances.ts
Labels: enhancement

#2053 Fix calculation for section 4b unknown
  src/test/sectionSpec/sections/holderOfManagementRights.ts
Labels: bug

#2067 Add title for taxon
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Taxon/Taxon.tsx
Labels: enhancement

#2069 collapse sections
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestInvestment.ts
  src/test/sectionSpec/panEuSections/forestWorkforce.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/recreationInForest.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
  tools/dataMigration/dataTable/mappings/panEuropean/countrycomments1.ts
Labels: enhancement

#2066 Assessment status change: Show recipient list, send emails for current cycle only
  src/client/components/EditUserForm/EditUserForm.scss
  src/client/components/PageLayout/Toolbar/Status/StatusConfirm.tsx
  src/client/components/PageLayout/Toolbar/Status/useRecipients.ts
  src/client/components/UserList/CollaboratorListElement/CollaboratorListElement.tsx
  src/client/components/UserList/UserInvitationInfo/UserInvitationInfo.tsx
  src/client/components/UserList/UserList.tsx
  src/client/components/UserList/UserListHeader/UserListHeader.tsx
  src/client/pages/AssessmentHome/AssessmentHome.tsx
  src/client/pages/Country/Country.tsx
  src/client/pages/Country/hooks/useGetUsers.ts
  src/client/styles/buttons.scss
  src/i18n/resources/en/common.js
  src/meta/user/userRoles.ts
  src/server/api/area/postCountry.ts
  src/server/api/user/index.ts
  src/server/repository/public/user/readCountryUsersByRole.ts
  src/server/service/mail/assessmentNotifyUsers.ts
Labels: bug, enhancement

#2075 Section 2a: Update and add validations
  src/i18n/resources/en.js
  src/server/controller/cycleData/updateDependencies/expressionEvaluator/functions/index.ts
  src/server/controller/cycleData/updateDependencies/expressionEvaluator/functions/validatorEqualToPlantedForest.ts
  src/server/controller/cycleData/updateDependencies/expressionEvaluator/functions/validatorEqualToTotalForest.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/growingStock.ts
Labels: enhancement

#2082 fix table 7a calculated variable total
  src/test/dataMigration/steps/metadataFix/metadataFix.ts
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/nonWoodForestProductsRemovals.ts
Labels: bug

#2094 Fix horizontal scroll bug
  src/client/components/PageLayout/Toolbar/Toolbar.scss
Labels: bug

#2087 Redirect user correctly and require user to fill information if role = (NC, ANC, C)
  src/client/pages/Landing/Landing.tsx
  src/client/pages/PageRoutes/PageRoutes.tsx
  src/client/pages/PageRoutes/useUserRedirect.ts
  src/client/pages/User/ButtonContinue.tsx
  src/client/pages/User/User.scss
  src/client/pages/User/User.tsx
  src/client/store/middleware/axios.ts
  src/client/store/middleware/listener.ts
  src/client/store/store.ts
  src/client/store/ui/userManagement/actions/updateUser.ts
  src/client/store/user/slice.ts
  src/i18n/resources/en/common.js
  src/meta/user/userRoles.ts
  src/meta/user/users.ts
Labels: enhancement

#2093 Update comments and descriptions editor
  package.json
  src/client/components/EditorWYSIWYG/EditorWYSIWYG.tsx
  src/client/components/EditorWYSIWYG/index.ts
  src/client/components/MarkdownEditor/MarkdownEditor.tsx
  src/client/components/MarkdownEditor/index.ts
  src/client/components/MarkdownPreview/MarkdownPreview.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  src/client/pages/OriginalDataPoint/components/Comments/CommentsEditor.tsx
  yarn.lock
Labels: enhancement

#2106 Rename labels (ODP, Section anchors)
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristics.tsx
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/sections/nonWoodForestProductsRemovals.ts
  src/test/sectionSpec/sections/sustainableDevelopment.ts
Labels: enhancement

#2109 Generic ODP fixes: labels, calculations, first year empty
  src/client/pages/Country/Country.tsx
  src/client/pages/OriginalDataPoint/OriginalDataPoint.tsx
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForest.tsx
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
  src/client/pages/OriginalDataPoint/components/YearSelection/YearSelection.tsx
Labels: bug, enhancement
