Repository openforis/fra-platform, pull requests merged in 2023-02, with the labels that each got.

#2115 fix getLastRole
  src/meta/user/userRoles.ts
Labels: bug

#2108 Feat/pan eu migration
  src/i18n/resources/en.js
  src/i18n/resources/en/panEuropean/countryComments.js
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestInvestment.ts
  src/test/sectionSpec/panEuSections/forestWorkforce.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/recreationInForest.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
  tools/dataMigration/dataTable/mappings/panEuropean/countrycomments1.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: enhancement

#2122 postDataMigration: disable validate nodes
  README.md
  src/i18n/resources/en.js
  src/server/db/db.ts
  src/server/repository/adapter/col.ts
  src/server/utils/logger.ts
  src/test/dataMigration/jest.config.js
  src/test/dataMigration/postDataMigration.ts
Labels: infrastructure

#2121 Add new AssessmentStatus: Not started
  src/client/components/PageLayout/Toolbar/CountryList/CountryListRow/CountryListRow.tsx
  src/client/components/PageLayout/Toolbar/Status/Status.scss
  src/client/components/PageLayout/Toolbar/Status/Status.tsx
  src/client/components/PopoverControl/PopoverControl.tsx
  src/client/store/assessment/slice.ts
  src/i18n/resources/en.js
  src/i18n/resources/es.js
  src/i18n/resources/fr.js
  src/meta/area/areas.ts
  src/meta/area/country.ts
  src/meta/assessment/assessments.test.ts
  src/meta/assessment/assessments.ts
Labels: enhancement

#2141 Fix printview
  src/client/components/Navigation/Navigation.tsx
  src/client/components/PageLayout/Footer/Footer.tsx
  src/client/components/PageLayout/Toolbar/Toolbar.tsx
  src/client/pages/AssessmentSection/Title/TitleExcelCalculator/TitleExcelCalculator.tsx
Labels: bug

#2143 Fix Regions view
  src/client/pages/Country/Country.tsx
Labels: bug

#2139 Original Data Point: Copy previous values - dont include values for classifications
  src/client/store/ui/originalDataPoint/actions/copyPreviousNationalClasses.ts
Labels: bug, enhancement

#2145 Biomass stock calculator per cycle
  src/client/pages/AssessmentSection/Title/TitleExcelCalculator/ExcelCalculatorDownload.tsx
  src/meta/api/endpoint/ApiEndPoint.ts
  src/meta/api/request/file/biomassStockFile.ts
  src/meta/api/request/index.ts
  src/server/api/file/getBiomassStockFile.ts
  src/server/api/file/index.ts
  src/server/service/file/index.ts
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_boreal_en.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_boreal_es.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_boreal_fr.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_boreal_ru.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_subtropical_en.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_subtropical_es.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_subtropical_fr.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_subtropical_ru.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_temperate_en.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_temperate_es.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_temperate_fr.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_temperate_ru.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_tropical_en.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_tropical_es.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_tropical_fr.xlsx
  src/server/static/fileRepository/fra/2020/biomassStock/calculator_tropical_ru.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_boreal_en.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_boreal_es.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_boreal_fr.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_subtropical_en.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_subtropical_es.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_subtropical_fr.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_temperate_en.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_temperate_es.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_temperate_fr.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_tropical_en.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_tropical_es.xlsx
  src/server/static/fileRepository/fra/2025/biomassStock/calculator_tropical_fr.xlsx
Labels: enhancement

#2153 Remove Clear table from Generate values
  src/client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx
  src/client/pages/AssessmentSection/DataTable/GenerateValues/method.ts
  src/client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValues.ts
  src/server/api/cycleData/table/estimateValues.ts
  src/server/service/estimates/estimationEngine.ts
Labels: enhancement

#2155 Add user uuid & validation
  src/meta/user/user.ts
  src/server/api/auth/strategy/jwt.ts
  src/server/db/migration/migrations/20230206122230-alter-user-uuid.js
  src/server/db/migration/migrations/sqls/20230206122230-alter-user-uuid-down.sql
  src/server/db/migration/migrations/sqls/20230206122230-alter-user-uuid-up.sql
  src/server/repository/public/user/fields.ts
  src/server/repository/public/user/getOne.ts
Labels: bug

#2149 National correspondents can't edit reviewers
  src/client/components/UserList/CollaboratorListElement/CollaboratorListElement.tsx
  src/client/components/UserList/CollaboratorListElement/InvitationColumn.tsx
  src/client/components/UserList/CollaboratorListElement/UserEditColumn.tsx
Labels: enhancement

#2152 Disable content check
  src/client/pages/AssessmentHome/FraHome/hooks/useSections.tsx
Labels: enhancement

#2124 Feat/pan eu migration
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Descriptions/GeneralComments/GeneralComments.tsx
  src/i18n/resources/en/panEuropean/countryComments.js
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestInvestment.ts
  src/test/sectionSpec/panEuSections/forestWorkforce.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/recreationInForest.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
Labels: enhancement

#2147 Missing information toaster
  src/client/pages/User/User.tsx
  src/i18n/resources/en.js
Labels: bug, enhancement

#2146 Copy previous data source entries and fix descriptions
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/ButtonCopyDataSources.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceReferenceColumn.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceRow.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.scss
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.tsx
  src/client/store/assessment/hooks/usePreviousSection.ts
  src/client/store/ui/assessmentSection/actions/copyPreviousDatasources.ts
  src/client/store/ui/assessmentSection/slice.ts
  src/meta/assessment/commentableDescription.ts
  src/meta/assessment/section.ts
  src/meta/assessment/subSections.ts
  src/test/dataMigration/steps/migrateDescriptions.ts
Labels: bug, enhancement

#2170 Fix total calculation for section 7
  src/test/sectionSpec/sections/nonWoodForestProductsRemovals.ts
Labels: bug

#2180 Persist data source copy from previous section
  src/client/store/ui/assessmentSection/actions/copyPreviousDatasources.ts
  src/client/store/ui/assessmentSection/slice.ts
  src/test/integration/mock/section.ts
Labels: bug

#2182 Support FRA values for land area
  src/server/db/migration/migrations/20230208090428-add-table-ext-node.js
  src/server/db/migration/migrations/sqls/20230208090428-add-table-ext-node-down.sql
  src/server/db/migration/migrations/sqls/20230208090428-add-table-ext-node-up.sql
  src/server/repository/assessment/assessment/getCreateSchemaDDL.ts
Labels: bug, enhancement

#2186 Initial commit for dynamic description metadata
  src/client/pages/AssessmentSection/AssessmentSection.tsx
  src/client/pages/AssessmentSection/Descriptions/AnalysisDescriptions/AnalysisDescriptions.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/ButtonCopyDataSources.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnComments.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnFraVariable.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnReference.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnVariable.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/ColumnYearForDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceColumn/DataSourceColumn.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceRow.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/Description.tsx
  src/client/pages/AssessmentSection/Descriptions/Descriptions.tsx
  src/client/pages/AssessmentSection/Descriptions/NationalDataDescriptions/NationalDataDescriptions.tsx
  src/client/store/ui/assessmentSection/actions/copyPreviousDatasources.ts
  src/i18n/resources/en/dataSource.js
  src/meta/assessment/commentableDescription.ts
  src/meta/assessment/description.ts
  src/meta/assessment/subSections.ts
  src/server/repository/adapter/section.ts
  src/test/integration/mock/section.ts
  tools/dataMigration/migrateMetadata/getSection.ts
Labels: bug, enhancement

#2196 ODP: Extent of forest: Fix remaining land area null check
  src/client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx
Labels: bug

#2195 Section 6b: Area Of Permanent Forest Estate column 2025
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/areaOfPermanentForestEstate.ts
Labels: enhancement

#2198 Add status (and tier) tables for 1a, 2a, 2c
  src/i18n/resources/en/common.js
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/biomassStock.ts
  src/test/sectionSpec/sections/common/statusAndTierTable.ts
  src/test/sectionSpec/sections/extentOfForest.ts
  src/test/sectionSpec/sections/growingStock.ts
  tools/dataMigration/migrateData/_repos.ts
Labels: enhancement

#2197 Chart per cycle
  src/client/pages/AssessmentSection/DataTable/DataTable.tsx
  src/meta/assessment/row.ts
  src/server/repository/assessment/row/getOne.ts
  src/server/repository/assessment/section/getManyMetadata.ts
  src/test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts
  src/test/dataMigration/steps/validateNodes/validateNodes.ts
  src/test/sectionSpec/rowSpec.ts
  src/test/sectionSpec/sections/forestCharacteristics.ts
  tools/dataMigration/generateMetaCache/index.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateMetadata/getRow.ts
Labels: enhancement

#2199 DataSources: Review indicator fix
  src/client/components/PageLayout/Header/CycleSwitcher/CycleSwitcher.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSourceRow.tsx
  src/client/pages/AssessmentSection/Descriptions/Description/DataSources/DataSources.tsx
  src/client/store/ui/assessmentSection/actions/copyPreviousDatasources.ts
  src/meta/assessment/commentableDescription.ts
  src/server/repository/assessmentCycle/messageTopicUser/getReviewStatus.ts
  src/server/repository/assessmentCycle/messageTopicUser/getReviewSummary.ts
Labels: bug, enhancement

#2201 Include original data for calculations
  src/client/pages/AssessmentSection/DataTable/hooks/useCalculations.ts
  src/client/pages/AssessmentSection/DataTable/hooks/useGetTableData.ts
  src/client/pages/AssessmentSection/DataTable/hooks/useValidations.ts
  src/client/pages/AssessmentSection/DataTable/hooks/useValidationsAndCalculations.ts
  src/client/store/ui/assessmentSection/actions/getTableData.ts
  src/client/store/ui/assessmentSection/slice.ts
Labels: bug

#2207 Feat/pan eu migration
  src/meta/expressionEvaluator/functions/index.ts
  src/meta/expressionEvaluator/functions/validatorEqualToSum.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  tools/dataMigration/dataTable/mappings/panEuropean/table1_2a.ts
Labels: enhancement

#2228 pre-fill primaryForestByClimaticDomain
  src/i18n/resources/en/fra.js
  src/test/dataMigration/steps/migratePrimaryForestData.ts
  src/test/sectionSpec/sections/forestCharacteristics.ts
Labels: enhancement

#2229 fix country status label when status is null
  src/meta/area/areas.ts
Labels: bug

#2231 insert totalLandArea Atlantis countries 2025
  src/test/dataMigration/steps/migrateNodeExt/migrateNodeExt.ts
Labels: enhancement

#2219 2212 table 2b updates
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Select/Select.tsx
  src/i18n/resources/en/fra.js
  src/test/sectionSpec/fraSpecs.ts
  src/test/sectionSpec/sections/growingStockComposition.ts
Labels: bug, enhancement

#2245 Add copy values button
  src/client/pages/AssessmentSection/DataTable/Table/ButtonCopyValues/ButtonCopyValues.scss
  src/client/pages/AssessmentSection/DataTable/Table/ButtonCopyValues/ButtonCopyValues.tsx
  src/client/pages/AssessmentSection/DataTable/Table/ButtonCopyValues/index.ts
  src/client/pages/AssessmentSection/DataTable/Table/Table.tsx
  src/meta/assessment/table.ts
Labels: enhancement

#2253 Update validations 5b
  src/i18n/resources/en.js
  src/meta/expressionEvaluator/functions/index.ts
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanLandArea.ts
  src/test/sectionSpec/sections/areaAffectedByFire.ts
Labels: bug

#2268 Fix 4b calculations
  src/test/sectionSpec/sections/holderOfManagementRights.ts
Labels: bug

#2273 Revert "Calculation issue in table 2d"
  src/client/pages/AssessmentSection/DataTable/hooks/useCalculations.ts
Labels: invalid

#2278 Hide atlantis from published cycles
  .env.template
  src/server/repository/assessmentCycle/country/getMany.ts
  src/server/repository/assessmentCycle/country/isAtlantisAllowed.ts
  src/server/repository/assessmentCycle/region/getRegionGroups.ts
  src/server/utils/processEnv.ts
Labels: enhancement

#2283 2a, 2c: Switch labels and text for status table
  src/i18n/resources/en/fra.js
Labels: bug

#2291 C1 tab validations
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
Labels: enhancement

#2287 Add migration steps command and generation
  package.json
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/array.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/binary.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/call.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/compound.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/conditional.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/context.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/identifier.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/index.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/literal.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/member.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/sequence.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/this.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/evalDependencies/unary.ts
  src/server/controller/assessment/generateMetaCache/dependencyEvaluator/index.ts
  src/server/controller/assessment/generateMetaCache/index.ts
  src/server/controller/assessment/index.ts
  src/server/db/migration/migrations/20230222094454-migration-steps.js
  src/server/db/migration/migrations/sqls/20230222094454-migration-steps-down.sql
  src/server/db/migration/migrations/sqls/20230222094454-migration-steps-up.sql
  src/test/generateMetaCache/index.ts
  src/test/generateMetaCache/jest.config.js
  src/test/migrations/create-migration-step.sh
  src/test/migrations/index.ts
  src/test/migrations/jest.config.js
  src/test/migrations/steps/20230222121020-step-ext_node-sustainableDevelopment15_2_1_5_forestAreaVerifiedForestManagement.ts
  src/test/migrations/steps/data/certifiedArea.json
  src/test/migrations/steps/template.ts
Labels: enhancement, infrastructure

#2314 step-recalculate-forest-ownership
  src/test/migrations/steps/20230223093323-step-recalculate-forest-ownership.ts
  src/test/migrations/steps/utils/calculateRow.ts
  src/test/migrations/steps/utils/getRow.ts
Labels: bug

#2321 Feat/pan eu validations
  src/meta/expressionEvaluator/functions/validatorEqualToSum.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/utils/numbers.ts
Labels: enhancement

#2322 Add missing Total Land Area (Visible in 1A NDPs)
  src/test/migrations/steps/20230224111303-step-ext_node-extentOfForest-totalLandArea.ts
  src/test/migrations/steps/data/totalLandAreas_1950-2020.json
Labels: bug, enhancement

#2326 Sort migrations
  src/test/migrations/index.ts
Labels: bug, infrastructure

#2332 Show correct country status on country status change
  src/client/store/assessment/slice.ts
Labels: bug

#2342 Update 2a validation
  src/i18n/resources/en.js
  src/meta/expressionEvaluator/functions/validatorEqualToTotalForest.ts
Labels: bug
