Repository openforis/fra-platform, pull requests merged in 2023-05, with the labels that each got.

#2545 Link Data Sources
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSourceColumn/ColumnTypeOfDataSource.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/DataSources.tsx
  src/client/pages/AssessmentSection/Descriptions/CommentableDescription/Description/DataSources/hooks/useGetDataSourcesLinked.tsx
  src/client/store/ui/assessmentSection/actions/getLinkedDataSources.ts
  src/client/store/ui/assessmentSection/hooks/index.ts
  src/client/store/ui/assessmentSection/index.ts
  src/client/store/ui/assessmentSection/slice.ts
  src/client/store/ui/assessmentSection/stateType.ts
  src/i18n/resources/en/panEuropean/panEuropean.js
  src/meta/api/endpoint/ApiEndPoint.ts
  src/meta/assessment/col.ts
  src/meta/assessment/commentableDescription.ts
  src/meta/assessment/description/dataSourceType.ts
  src/meta/assessment/description/description.ts
  src/meta/assessment/description/index.ts
  src/meta/assessment/description/nationalDataDataSourceDescription.ts
  src/meta/assessment/index.ts
  src/server/api/cycleData/descriptions/getDataSources.ts
  src/server/api/cycleData/index.ts
  src/server/controller/cycleData/index.ts
  src/server/repository/assessmentCycle/descriptions/getDataSources.ts
  src/server/repository/assessmentCycle/descriptions/index.ts
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/descriptionsSpec.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/geo/boundsImport.ts
  tools/geo/forestEstimationsImport.ts
Labels: enhancement

#2579 Fix 2b calculations
  src/test/migrations/steps/20230502120206-step-growingStockComposition-fix-calculations.ts
  src/test/migrations/steps/utils/calculateRow.ts
  src/test/migrations/steps/utils/getAssessmentCycle.ts
Labels: bug

#2588 Redirect if from unpublished cycles/user has no cycle
  src/client/pages/Cycle/Cycle.tsx
Labels: bug

#2586 Geo refactor/Render layers section with empty redux state
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/CustomAssetControl.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/CustomAssetControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/index.ts
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/LayerOpacityControl/LayerOpacityControl.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/LayerOpacityControl/LayerOpacityControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/LayerOpacityControl/index.ts
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/index.ts
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/MapVisualizerPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuListElement/GeoMapMenuListElement.tsx
  src/meta/geo/burnedAreaSource.ts
Labels: refactor

#2590 Geo refactor/add redux management to layers control
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/CustomAssetControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/LayerOpacityControl/LayerOpacityControl.tsx
  src/client/store/ui/geo/hooks/index.ts
  src/client/store/ui/geo/index.ts
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
  src/meta/geo/index.ts
  src/meta/geo/sections.ts
Labels: refactor

#2591 Geo refactor/render map layers
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/store/ui/geo/actions/postLayer.ts
  src/client/store/ui/geo/slice.ts
  src/client/utils/mapController.ts
  src/meta/api/request/geo/layer.ts
  src/meta/geo/forest.ts
  src/meta/geo/index.ts
  src/meta/geo/map.ts
  src/meta/geo/protectedAreaSource.ts
  src/meta/geo/sections.ts
Labels: refactor

#2592 Geo refactor/handle custom asset layers
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/CustomAssetControl.tsx
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
Labels: refactor

#2597 Updated validator table 2.5
  src/meta/expressionEvaluator/functions/validatorNotEmpty.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
Labels: enhancement

#2583 2353 paneuropean linked nodes from fra 2025
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useClassName.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/hooks/useOnChange.ts
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/meta/assessment/col.ts
  src/meta/assessment/cols.ts
  src/meta/assessment/cycle.ts
  src/meta/assessment/index.ts
  src/meta/assessment/table.ts
  src/server/db/index.ts
  src/server/db/tables.ts
  src/server/repository/adapter/col.ts
  src/server/repository/assessmentCycle/data/ddl/getTableDataWithODPCreateViewDDL.ts
  src/test/migrations/steps/20230507154018-step-create-table-data-with-dop-views.ts
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/colSpec.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  src/test/sectionSpec/panEuSections/forestHoldings.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/nonWoodGoods.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
  tools/dataMigration/migrateData/_createDataViews.ts
  tools/dataMigration/migrateData/_repos.ts
  tools/dataMigration/migrateData/migrateTablesData.ts
  tools/dataMigration/migrateMetadata/getCol.ts
  tools/dataMigration/migrateMetadata/getSection.ts
  tools/dataMigration/migrateMetadata/utils.ts
Labels: enhancement

#2605 Add support for hidden tables in country comments
  src/test/dataMigration/stepsPanEuropean/countryComments/migrateCountryComments.ts
Labels: bug

#2602 Geo refactor/fetch custom asset layer on submit
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/CustomAssetControl/CustomAssetControl.tsx
  src/client/store/ui/geo/actions/_getLayerRequestBody.ts
  src/client/store/ui/geo/actions/index.ts
  src/client/store/ui/geo/actions/postLayer.ts
  src/client/store/ui/geo/slice.ts
Labels: refactor

#2622 Table 1a fix (odp years map)
  src/server/controller/cycleData/updateDependencies/utils/isODPCell.ts
Labels: bug

#2621 Add 5c degradedAreaForThatYear validation
  src/meta/expressionEvaluator/functions/validatorNotGreaterThanMaxForest.ts
  src/test/migrations/steps/20230511110350-step-update-5c-error-message.ts
Labels: enhancement

#2626 Geo refactor/handle gte tree cover percent layers
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/TreeCoverPercentageControl/TreeCoverPercentageControl.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/TreeCoverPercentageControl/TreeCoverPercentageControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/TreeCoverPercentageControl/index.ts
  src/client/store/ui/geo/hooks/index.ts
  src/client/store/ui/geo/hooks/useGteTreeCoverPercent.ts
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
  src/meta/geo/forest.ts
  src/meta/geo/layer.ts
Labels: refactor

#2632 Add missing translations for RU
  src/i18n/resources/ru.js
  src/i18n/resources/ru/common.js
  src/i18n/resources/ru/contentCheck.js
  src/i18n/resources/ru/dataSource.js
  src/i18n/resources/ru/fra.js
  src/i18n/resources/ru/login.js
  src/i18n/resources/ru/uc.js
Labels: translations

#2637 Update tad.md
  src/server/static/definitions/fra/2025/ru/tad.md
Labels: translations

#2638 Missing translations ru 2
  src/i18n/resources/ar/fra.js
  src/i18n/resources/en/fra.js
  src/i18n/resources/es/fra.js
  src/i18n/resources/fr/fra.js
  src/i18n/resources/ru/fra.js
  src/i18n/resources/zh/fra.js
  src/test/migrations/steps/20230516103111-step-add-sections-2025-labels.ts
Labels: translations

#2654 Update faq.md
  src/server/static/definitions/fra/2025/ru/faq.md
Labels: translations

#2659 Missing translations ru 3
  src/i18n/resources/ar/fra.js
  src/i18n/resources/en/fra.js
  src/i18n/resources/es/fra.js
  src/i18n/resources/fr/fra.js
  src/i18n/resources/ru.js
  src/i18n/resources/ru/common.js
  src/i18n/resources/ru/fra.js
  src/i18n/resources/zh/fra.js
  src/test/migrations/steps/20230519093455-step-update-label-1a-other-wooded-land.ts
Labels: translations

#2647 changed layout table 2.5
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/CellHeader/CellHeader.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/CellHeader/index.tsx
  src/client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
Labels: enhancement

#2664 Geo refactor/add refetch on select to agreement layer
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/AgreementLevelControl/AgreementLevelControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/AgreementLevelControl/AgreementLevelSelector/AgreementLevelSelector.tsx
  src/client/pages/Geo/GeoMap/hooks/useCountSectionSelectedLayers.ts
  src/client/pages/Geo/GeoMap/hooks/useFetchAgreementLevelLayer.ts
  src/client/store/ui/geo/actions/postLayer.ts
  src/client/store/ui/geo/slice.ts
  src/client/store/ui/geo/stateType.ts
  src/meta/api/request/geo/layer.ts
Labels: refactor

#2648 2609 paneu inverse validator
  src/client/pages/AssessmentSection/DataTable/Table/DataValidations/DataValidations.tsx
  src/i18n/resources/en.js
  src/meta/assessment/index.ts
  src/meta/assessment/nodeValueValidation.ts
  src/meta/expressionEvaluator/functions/validatorEqualToSum.ts
  src/test/sectionSpec/PanEuropeanSpecs.ts
  src/test/sectionSpec/panEuHelpers/updatedDataCol.ts
  src/test/sectionSpec/panEuSections/ageClassDistribution.ts
  src/test/sectionSpec/panEuSections/areaWithForestLandDegradation.ts
  src/test/sectionSpec/panEuSections/carbonStock.ts
  src/test/sectionSpec/panEuSections/deadwood.ts
  src/test/sectionSpec/panEuSections/forestArea.ts
  src/test/sectionSpec/panEuSections/forestAreaWithDamage.ts
  src/test/sectionSpec/panEuSections/forestHoldings.ts
  src/test/sectionSpec/panEuSections/growingStock.ts
  src/test/sectionSpec/panEuSections/introducedTreeSpecies.ts
  src/test/sectionSpec/panEuSections/naturalness.ts
  src/test/sectionSpec/panEuSections/protectedForests.ts
  src/test/sectionSpec/panEuSections/protectiveForestsSoilWaterAndOtherEcosystemFunctions.ts
  src/test/sectionSpec/panEuSections/regeneration.ts
Labels: enhancement

#2672 Geo refactor/handle layers with year selector
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/LayersSectionPanel.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/TreeCoverPercentageControl/TreeCoverPercentageControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/YearControl/YearControl.scss
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/YearControl/YearControl.tsx
  src/client/pages/Geo/GeoMap/GeoMapMenuData/MapVisualizerPanel/LayersSectionPanel/components/YearControl/index.ts
  src/client/pages/Geo/GeoMap/hooks/index.ts
  src/client/pages/Geo/GeoMap/hooks/useFetchNewLayerOption.ts
  src/client/store/ui/geo/slice.ts
Labels: refactor

#2677 remove brackets
  src/meta/expressionEvaluator/functions/validatorEqualToSum.ts
Labels: bug
